In [ ]:
# ============================================================
# 01. SELECCIÓN Y VALIDACIÓN DE BASE DE MODELADO
# Nearshoring Project / Market Opportunity Analytics
#
# Input esperado:
# df ya cargado en memoria desde el bloque anterior
#
# Outputs:
# 01_modeling_base_selected_columns.csv
# 02_modeling_base_validation_report.csv
# 03_modeling_base_missing_summary.csv
# 04_modeling_base_numeric_profile.csv
# 05_modeling_base_feature_correlations.csv
# 06_modeling_base_duplicate_keys.csv
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

modeling_path.mkdir(parents=True, exist_ok=True)

print("Modeling output path:")
print(modeling_path)


# ------------------------------------------------------------
# 2. Columnas esperadas
# ------------------------------------------------------------

id_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key"
]

feature_cols = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",
    "denue_manufacturing_establishments",

    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",

    "share_b2b_micro_establishments",
    "share_b2b_small_establishments",
    "share_b2b_medium_establishments",
    "share_b2b_large_establishments",
    "share_b2b_medium_large_establishments",

    "b2b_support_per_100_manufacturing_establishments",
    "b2b_medium_large_per_100_manufacturing_establishments",
    "b2b_large_per_100_manufacturing_establishments",
    "b2b_support_per_1000_manufacturing_workers",
    "b2b_medium_large_per_1000_manufacturing_workers",
    "b2b_large_per_1000_manufacturing_workers"
]

audit_cols = [
    "has_denue_match",
    "has_b2b_support",
    "has_b2b_medium_large",
    "has_b2b_large",
    "b2b_only_micro_small"
]

previous_output_cols = [
    "industrial_capacity_score",
    "industrial_capacity_percentile",
    "rank_industrial_capacity_within_year",
    "industrial_capacity_group",
    "b2b_support_percentile",
    "b2b_medium_large_percentile",
    "b2b_large_percentile",
    "b2b_support_supply_score",
    "b2b_support_supply_percentile",
    "high_industrial_capacity",
    "high_b2b_support",
    "high_b2b_medium_large",
    "high_b2b_large",
    "industrial_b2b_typology_broad",
    "industrial_b2b_typology_scaled"
]


# ------------------------------------------------------------
# 3. Verificar columnas existentes
# ------------------------------------------------------------

expected_cols = id_cols + feature_cols + audit_cols + previous_output_cols

existing_cols = [col for col in expected_cols if col in df.columns]
missing_expected_cols = [col for col in expected_cols if col not in df.columns]

existing_feature_cols = [col for col in feature_cols if col in df.columns]
missing_feature_cols = [col for col in feature_cols if col not in df.columns]

print("Columnas esperadas existentes:", len(existing_cols))
print("Features existentes:", len(existing_feature_cols))

if missing_expected_cols:
    print("\nColumnas esperadas no encontradas:")
    for col in missing_expected_cols:
        print("-", col)


# ------------------------------------------------------------
# 4. Crear base seleccionada
# ------------------------------------------------------------

modeling_base = df[existing_cols].copy()

# Homologar llaves
modeling_base["year"] = pd.to_numeric(
    modeling_base["year"],
    errors="coerce"
).astype("Int64")

modeling_base["entidad_id"] = (
    modeling_base["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

modeling_base["municipio_id"] = (
    modeling_base["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

modeling_base["geo_key"] = (
    modeling_base["entidad_id"] + modeling_base["municipio_id"]
)

# Asegurar numéricos en features
for col in existing_feature_cols:
    modeling_base[col] = pd.to_numeric(
        modeling_base[col],
        errors="coerce"
    )

print("\nBase seleccionada:")
print(f"Filas: {modeling_base.shape[0]:,}")
print(f"Columnas: {modeling_base.shape[1]:,}")

display(modeling_base.head())


# ------------------------------------------------------------
# 5. Validación de llave year × geo_key
# ------------------------------------------------------------

duplicate_keys = (
    modeling_base[
        modeling_base.duplicated(
            subset=["year", "geo_key"],
            keep=False
        )
    ]
    .sort_values(["year", "geo_key"])
    .copy()
)

n_duplicate_rows = len(duplicate_keys)

key_is_unique = n_duplicate_rows == 0


# ------------------------------------------------------------
# 6. Cobertura por año
# ------------------------------------------------------------

coverage_by_year = (
    modeling_base
    .groupby("year", dropna=False)
    .agg(
        n_rows=("geo_key", "size"),
        n_unique_municipalities=("geo_key", "nunique"),
        n_entities=("entidad_id", "nunique")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 7. Missing values
# ------------------------------------------------------------

missing_summary = pd.DataFrame({
    "column": modeling_base.columns,
    "missing_count": modeling_base.isna().sum().values,
    "missing_share": modeling_base.isna().mean().values
}).sort_values(
    ["missing_share", "missing_count"],
    ascending=[False, False]
)


# ------------------------------------------------------------
# 8. Ceros por feature
# ------------------------------------------------------------

zero_summary = []

for col in existing_feature_cols:
    s = modeling_base[col]
    zero_count = (s == 0).sum()
    zero_summary.append({
        "column": col,
        "zero_count": zero_count,
        "zero_share": zero_count / len(modeling_base)
    })

zero_summary = pd.DataFrame(zero_summary)


# ------------------------------------------------------------
# 9. Perfil numérico básico
# ------------------------------------------------------------

numeric_profile = (
    modeling_base[existing_feature_cols]
    .describe(percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99])
    .T
    .reset_index()
    .rename(columns={"index": "feature"})
)

numeric_profile = numeric_profile.merge(
    zero_summary,
    left_on="feature",
    right_on="column",
    how="left"
).drop(columns=["column"])


# ------------------------------------------------------------
# 10. Correlaciones entre features
# ------------------------------------------------------------

feature_correlations = (
    modeling_base[existing_feature_cols]
    .corr(method="pearson")
    .reset_index()
    .rename(columns={"index": "feature"})
)


# ------------------------------------------------------------
# 11. Reporte general de validación
# ------------------------------------------------------------

validation_items = [
    {
        "check": "n_rows",
        "value": modeling_base.shape[0],
        "status": "info"
    },
    {
        "check": "n_columns",
        "value": modeling_base.shape[1],
        "status": "info"
    },
    {
        "check": "n_features_expected",
        "value": len(feature_cols),
        "status": "info"
    },
    {
        "check": "n_features_existing",
        "value": len(existing_feature_cols),
        "status": "ok" if len(missing_feature_cols) == 0 else "warning"
    },
    {
        "check": "year_geo_key_unique",
        "value": key_is_unique,
        "status": "ok" if key_is_unique else "warning"
    },
    {
        "check": "duplicate_key_rows",
        "value": n_duplicate_rows,
        "status": "ok" if n_duplicate_rows == 0 else "warning"
    },
    {
        "check": "n_years",
        "value": modeling_base["year"].nunique(dropna=True),
        "status": "info"
    },
    {
        "check": "years_available",
        "value": ", ".join(
            modeling_base["year"].dropna().astype(str).sort_values().unique()
        ),
        "status": "info"
    },
    {
        "check": "missing_expected_columns",
        "value": ", ".join(missing_expected_cols) if missing_expected_cols else "",
        "status": "ok" if len(missing_expected_cols) == 0 else "warning"
    },
    {
        "check": "missing_feature_columns",
        "value": ", ".join(missing_feature_cols) if missing_feature_cols else "",
        "status": "ok" if len(missing_feature_cols) == 0 else "warning"
    }
]

validation_report = pd.DataFrame(validation_items)


# ------------------------------------------------------------
# 12. Guardar outputs
# ------------------------------------------------------------

modeling_base.to_csv(
    modeling_path / "01_modeling_base_selected_columns.csv",
    index=False,
    encoding="utf-8-sig"
)

validation_report.to_csv(
    modeling_path / "02_modeling_base_validation_report.csv",
    index=False,
    encoding="utf-8-sig"
)

missing_summary.to_csv(
    modeling_path / "03_modeling_base_missing_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

numeric_profile.to_csv(
    modeling_path / "04_modeling_base_numeric_profile.csv",
    index=False,
    encoding="utf-8-sig"
)

feature_correlations.to_csv(
    modeling_path / "05_modeling_base_feature_correlations.csv",
    index=False,
    encoding="utf-8-sig"
)

duplicate_keys.to_csv(
    modeling_path / "06_modeling_base_duplicate_keys.csv",
    index=False,
    encoding="utf-8-sig"
)

coverage_by_year.to_csv(
    modeling_path / "07_modeling_base_coverage_by_year.csv",
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 13. Mostrar resultados clave
# ------------------------------------------------------------

print("\nVALIDATION REPORT")
display(validation_report)

print("\nCOVERAGE BY YEAR")
display(coverage_by_year)

print("\nMISSING SUMMARY")
display(missing_summary.head(20))

print("\nNUMERIC PROFILE")
display(numeric_profile.head(20))

print("\nArchivos guardados en:")
print(modeling_path)

Modeling output path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base
Columnas esperadas existentes: 53
Features existentes: 27

Base seleccionada:
Filas: 4,898
Columnas: 53

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,total_manufacturing_establishments,total_manufacturing_employment,total_manufacturing_value_added,total_manufacturing_income,...,b2b_medium_large_percentile,b2b_large_percentile,b2b_support_supply_score,b2b_support_supply_percentile,high_industrial_capacity,high_b2b_support,high_b2b_medium_large,high_b2b_large,industrial_b2b_typology_broad,industrial_b2b_typology_scaled
0,2018,15,México,106,Toluca,15106,4351.0,83598.0,97605.998,334675.563,...,0.991009,0.994279,0.973590,0.986514,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
1,2018,24,San Luis Potosí,028,San Luis Potosí,24028,3824.0,126640.0,77223.073,274960.549,...,0.995913,0.996731,0.980486,0.993870,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
2,2018,02,Baja California,004,Tijuana,02004,3670.0,270055.0,85526.588,222120.705,...,0.996731,0.995913,0.975429,0.989375,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
3,2018,22,Querétaro,014,Querétaro,22014,3363.0,103369.0,60661.916,229532.904,...,0.997548,0.997548,0.982938,0.996322,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
4,2018,05,Coahuila de Zaragoza,035,Torreón,05035,2046.0,70589.0,72451.993,201548.237,...,0.993053,0.995505,0.982274,0.995505,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub

VALIDATION REPORT

                      check       value status
0                    n_rows        4898   info
1                 n_columns          53   info
2       n_features_expected          27   info
3       n_features_existing          27     ok
4       year_geo_key_unique        True     ok
5        duplicate_key_rows           0     ok
6                   n_years           2   info
7           years_available  2018, 2023   info
8  missing_expected_columns                 ok
9   missing_feature_columns                 ok

COVERAGE BY YEAR

   year  n_rows  n_unique_municipalities  n_entities
0  2018    2447                     2447          32
1  2023    2451                     2451          32

MISSING SUMMARY

,column,missing_count,missing_share
7,total_manufacturing_employment,368,0.075133
8,total_manufacturing_value_added,368,0.075133
9,total_manufacturing_income,368,0.075133
10,total_manufacturing_investment,368,0.075133
30,b2b_support_per_1000_manufacturing_workers,368,0.075133
31,b2b_medium_large_per_1000_manufacturing_workers,368,0.075133
32,b2b_large_per_1000_manufacturing_workers,368,0.075133
38,industrial_capacity_score,368,0.075133
39,industrial_capacity_percentile,368,0.075133
40,rank_industrial_capacity_within_year,368,0.075133
41,industrial_capacity_group,368,0.075133
0,year,0,0.000000
1,entidad_id,0,0.000000
2,entidad_name,0,0.000000
3,municipio_id,0,0.000000
4,municipio_name,0,0.000000
5,geo_key,0,0.000000
6,total_manufacturing_establishments,0,0.000000
11,denue_manufacturing_establishments,0,0.000000
12,denue_b2b_support_establishments,0,0.000000

NUMERIC PROFILE

,feature,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max,zero_count,zero_share
0,total_manufacturing_establishments,4898.0,247.871784,622.304482,1.000,1.00000,4.00000,21.000000,65.000000,208.000000,1026.600000,3061.690000,12015.000,0,0.000000
1,total_manufacturing_employment,4530.0,3018.688079,14862.541454,3.000,8.00000,16.00000,65.000000,217.000000,971.500000,10814.950000,66193.080000,364180.000,0,0.000000
2,total_manufacturing_value_added,4530.0,1894.451026,10348.258186,-11442.849,0.13829,0.50600,3.675750,15.993000,134.570250,6118.078200,51647.924600,226838.388,0,0.000000
3,total_manufacturing_income,4530.0,5773.935490,29826.572473,0.089,0.47329,1.33535,8.705000,37.518500,372.154500,18401.056500,163744.983070,497003.622,0,0.000000
4,total_manufacturing_investment,4530.0,97.521041,831.081055,-19194.283,-58.15498,-0.92725,0.001000,0.137000,2.370750,254.830100,2639.860460,21344.336,298,0.060841
5,denue_manufacturing_establishments,4898.0,232.965292,621.967606,0.000,1.00000,3.00000,17.000000,57.000000,182.000000,973.750000,3001.860000,11709.000,40,0.008167
6,denue_b2b_support_establishments,4898.0,97.418538,384.283393,0.000,0.00000,0.00000,3.000000,11.000000,40.000000,373.000000,1943.270000,7008.000,393,0.080237
7,denue_logistics_storage_establishments,4898.0,16.089628,61.977091,0.000,0.00000,0.00000,0.000000,2.000000,7.000000,61.000000,326.150000,932.000,1627,0.332176
8,denue_professional_technical_establishments,4898.0,43.234381,201.635179,0.000,0.00000,0.00000,0.000000,2.000000,13.000000,167.000000,905.270000,4022.000,1605,0.327685
9,denue_business_support_establishments,4898.0,38.094528,136.177591,0.000,0.00000,0.00000,2.000000,6.000000,19.000000,147.150000,682.120000,2440.000,555,0.113312
10,denue_b2b_support_scian_classes,4898.0,12.183136,18.258444,0.000,0.00000,0.00000,2.000000,5.000000,14.000000,52.000000,93.000000,115.000,393,0.080237
11,denue_b2b_micro_establishments,4898.0,74.580441,266.405451,0.000,0.00000,0.00000,3.000000,10.000000,36.000000,299.150000,1363.270000,4863.000,418,0.085341
12,denue_b2b_small_establishments,4898.0,16.861984,95.859585,0.000,0.00000,0.00000,0.000000,0.000000,3.000000,50.000000,397.450000,1820.000,2602,0.531237
13,denue_b2b_medium_establishments,4898.0,3.773785,22.648342,0.000,0.00000,0.00000,0.000000,0.000000,1.000000,10.150000,90.180000,539.000,3648,0.744794
14,denue_b2b_large_establishments,4898.0,2.202327,14.532610,0.000,0.00000,0.00000,0.000000,0.000000,0.000000,6.000000,60.090000,376.000,4124,0.841976
15,denue_b2b_medium_large_establishments,4898.0,5.976113,36.951138,0.000,0.00000,0.00000,0.000000,0.000000,1.000000,16.150000,156.000000,851.000,3508,0.716211
16,share_b2b_micro_establishments,4898.0,0.836340,0.279287,0.000,0.00000,0.00000,0.829018,0.943217,1.000000,1.000000,1.000000,1.000,418,0.085341
17,share_b2b_small_establishments,4898.0,0.064872,0.112809,0.000,0.00000,0.00000,0.000000,0.000000,0.100000,0.250000,0.500000,1.000,2602,0.531237
18,share_b2b_medium_establishments,4898.0,0.012819,0.038110,0.000,0.00000,0.00000,0.000000,0.000000,0.005284,0.066667,0.166667,1.000,3648,0.744794
19,share_b2b_large_establishments,4898.0,0.005731,0.033429,0.000,0.00000,0.00000,0.000000,0.000000,0.000000,0.029721,0.083333,1.000,4124,0.841976

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base

In [ ]:
# ============================================================
# 02. CREAR BASE MODEL-READY EXCLUYENDO MISSING EN FEATURES
# Nearshoring Project / Market Opportunity Analytics
#
# Input:
# modeling_base ya creada en memoria
#
# Outputs:
# 08_modeling_base_complete_cases.csv
# 09_modeling_base_excluded_missing_cases.csv
# 10_modeling_base_complete_case_report.csv
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np


# ------------------------------------------------------------
# 1. Ruta de salida
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

modeling_path.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# 2. Confirmar features disponibles
# ------------------------------------------------------------

feature_cols = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",
    "denue_manufacturing_establishments",

    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",

    "share_b2b_micro_establishments",
    "share_b2b_small_establishments",
    "share_b2b_medium_establishments",
    "share_b2b_large_establishments",
    "share_b2b_medium_large_establishments",

    "b2b_support_per_100_manufacturing_establishments",
    "b2b_medium_large_per_100_manufacturing_establishments",
    "b2b_large_per_100_manufacturing_establishments",
    "b2b_support_per_1000_manufacturing_workers",
    "b2b_medium_large_per_1000_manufacturing_workers",
    "b2b_large_per_1000_manufacturing_workers"
]

existing_feature_cols = [
    col for col in feature_cols
    if col in modeling_base.columns
]

missing_feature_cols = [
    col for col in feature_cols
    if col not in modeling_base.columns
]

print("Features existentes:", len(existing_feature_cols))
print("Features faltantes:", len(missing_feature_cols))

if missing_feature_cols:
    print("\nFeatures faltantes:")
    for col in missing_feature_cols:
        print("-", col)


# ------------------------------------------------------------
# 3. Crear bandera de casos completos
# ------------------------------------------------------------

modeling_base = modeling_base.copy()

modeling_base["is_complete_case_for_modeling"] = (
    modeling_base[existing_feature_cols]
    .notna()
    .all(axis=1)
)

modeling_base_complete = (
    modeling_base[
        modeling_base["is_complete_case_for_modeling"]
    ]
    .copy()
)

modeling_base_excluded = (
    modeling_base[
        ~modeling_base["is_complete_case_for_modeling"]
    ]
    .copy()
)


# ------------------------------------------------------------
# 4. Reporte de exclusión
# ------------------------------------------------------------

complete_case_report = pd.DataFrame([
    {
        "metric": "original_rows",
        "value": len(modeling_base)
    },
    {
        "metric": "complete_case_rows",
        "value": len(modeling_base_complete)
    },
    {
        "metric": "excluded_rows_due_to_missing_features",
        "value": len(modeling_base_excluded)
    },
    {
        "metric": "excluded_share",
        "value": len(modeling_base_excluded) / len(modeling_base)
    },
    {
        "metric": "n_features_used_for_complete_case_filter",
        "value": len(existing_feature_cols)
    }
])


# ------------------------------------------------------------
# 5. Cobertura por año antes/después
# ------------------------------------------------------------

coverage_original = (
    modeling_base
    .groupby("year")
    .agg(
        original_rows=("geo_key", "size"),
        original_municipalities=("geo_key", "nunique")
    )
    .reset_index()
)

coverage_complete = (
    modeling_base_complete
    .groupby("year")
    .agg(
        complete_rows=("geo_key", "size"),
        complete_municipalities=("geo_key", "nunique")
    )
    .reset_index()
)

coverage_report = coverage_original.merge(
    coverage_complete,
    on="year",
    how="left"
)

coverage_report["excluded_rows"] = (
    coverage_report["original_rows"] -
    coverage_report["complete_rows"]
)

coverage_report["excluded_share"] = (
    coverage_report["excluded_rows"] /
    coverage_report["original_rows"]
)


# ------------------------------------------------------------
# 6. Missing por columna en casos excluidos
# ------------------------------------------------------------

excluded_missing_summary = pd.DataFrame({
    "feature": existing_feature_cols,
    "missing_count_among_excluded": [
        modeling_base_excluded[col].isna().sum()
        for col in existing_feature_cols
    ],
    "missing_share_among_excluded": [
        modeling_base_excluded[col].isna().mean()
        for col in existing_feature_cols
    ]
}).sort_values(
    "missing_count_among_excluded",
    ascending=False
)


# ------------------------------------------------------------
# 7. Guardar outputs
# ------------------------------------------------------------

modeling_base_complete.to_csv(
    modeling_path / "08_modeling_base_complete_cases.csv",
    index=False,
    encoding="utf-8-sig"
)

modeling_base_excluded.to_csv(
    modeling_path / "09_modeling_base_excluded_missing_cases.csv",
    index=False,
    encoding="utf-8-sig"
)

complete_case_report.to_csv(
    modeling_path / "10_modeling_base_complete_case_report.csv",
    index=False,
    encoding="utf-8-sig"
)

coverage_report.to_csv(
    modeling_path / "11_modeling_base_complete_case_coverage_by_year.csv",
    index=False,
    encoding="utf-8-sig"
)

excluded_missing_summary.to_csv(
    modeling_path / "12_modeling_base_excluded_missing_summary.csv",
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 8. Mostrar resultados
# ------------------------------------------------------------

print("\nCOMPLETE CASE REPORT")
display(complete_case_report)

print("\nCOVERAGE BEFORE / AFTER")
display(coverage_report)

print("\nMISSING AMONG EXCLUDED CASES")
display(excluded_missing_summary)

print("\nArchivos guardados en:")
print(modeling_path)

Features existentes: 27
Features faltantes: 0

COMPLETE CASE REPORT

                                     metric        value
0                             original_rows  4898.000000
1                        complete_case_rows  4530.000000
2     excluded_rows_due_to_missing_features   368.000000
3                            excluded_share     0.075133
4  n_features_used_for_complete_case_filter    27.000000

COVERAGE BEFORE / AFTER

,year,original_rows,original_municipalities,complete_rows,complete_municipalities,excluded_rows,excluded_share
0,2018,2447,2447,2245,2245,202,0.082550
1,2023,2451,2451,2285,2285,166,0.067727

MISSING AMONG EXCLUDED CASES

,feature,missing_count_among_excluded,missing_share_among_excluded
1,total_manufacturing_employment,368,1.0
2,total_manufacturing_value_added,368,1.0
3,total_manufacturing_income,368,1.0
4,total_manufacturing_investment,368,1.0
25,b2b_medium_large_per_1000_manufacturing_workers,368,1.0
24,b2b_support_per_1000_manufacturing_workers,368,1.0
26,b2b_large_per_1000_manufacturing_workers,368,1.0
7,denue_logistics_storage_establishments,0,0.0
0,total_manufacturing_establishments,0,0.0
5,denue_manufacturing_establishments,0,0.0
6,denue_b2b_support_establishments,0,0.0
10,denue_b2b_support_scian_classes,0,0.0
9,denue_business_support_establishments,0,0.0
8,denue_professional_technical_establishments,0,0.0
11,denue_b2b_micro_establishments,0,0.0
15,denue_b2b_medium_large_establishments,0,0.0
12,denue_b2b_small_establishments,0,0.0
13,denue_b2b_medium_establishments,0,0.0
14,denue_b2b_large_establishments,0,0.0
18,share_b2b_medium_establishments,0,0.0
17,share_b2b_small_establishments,0,0.0
16,share_b2b_micro_establishments,0,0.0
19,share_b2b_large_establishments,0,0.0
22,b2b_medium_large_per_100_manufacturing_establi...,0,0.0
21,b2b_support_per_100_manufacturing_establishments,0,0.0
20,share_b2b_medium_large_establishments,0,0.0
23,b2b_large_per_100_manufacturing_establishments,0,0.0

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base

In [ ]:
# ============================================================
# 00. CONFIGURAR RUTAS Y CARGAR PANEL BASE
# Nearshoring Project / Market Opportunity Analytics
#
# Busca, en este orden:
# 1. municipality_industrial_b2b_opportunity_panel_curated
# 2. municipality_industrial_b2b_opportunity_panel
# 3. municipality_industrial_b2b_opportunity_panel_raw
#
# Outputs posteriores irán a:
# data/processed/modeling_base/
# ============================================================

from pathlib import Path
import pandas as pd
from google.colab import drive


# ------------------------------------------------------------
# 1. Montar Drive de forma segura
# ------------------------------------------------------------

drive_root = Path("/content/drive/MyDrive")

if not drive_root.exists():
    drive.mount("/content/drive")
else:
    print("Google Drive ya está disponible.")


# ------------------------------------------------------------
# 2. Definir rutas del proyecto
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

processed_path = project_path / "data" / "processed"

modeling_path = processed_path / "modeling_base"
modeling_path.mkdir(parents=True, exist_ok=True)

print("Project path:")
print(project_path)

print("\nProcessed path:")
print(processed_path)

print("\nModeling output path:")
print(modeling_path)


# ------------------------------------------------------------
# 3. Buscar archivo base
# ------------------------------------------------------------

base_names_priority = [
    "municipality_industrial_b2b_opportunity_panel_curated",
    "municipality_industrial_b2b_opportunity_panel",
    "municipality_industrial_b2b_opportunity_panel_raw"
]

allowed_extensions = [".csv", ".xlsx", ".xls", ".parquet"]

matches = []

for base_name in base_names_priority:
    for path in project_path.rglob("*"):
        if path.is_file():
            if base_name.lower() == path.stem.lower() and path.suffix.lower() in allowed_extensions:
                matches.append({
                    "priority_name": base_name,
                    "path": path
                })

print("\nCoincidencias encontradas:")
print("=" * 100)

for i, item in enumerate(matches):
    print(f"{i} -> [{item['priority_name']}] {item['path']}")


# ------------------------------------------------------------
# 4. Validar que exista al menos un archivo
# ------------------------------------------------------------

if len(matches) == 0:
    raise FileNotFoundError(
        "No encontré ningún panel base dentro de Nearshoring_Project. "
        "Revisa si el archivo existe o si fue guardado con otro nombre."
    )


# ------------------------------------------------------------
# 5. Seleccionar el archivo de mayor prioridad
# ------------------------------------------------------------

selected_path = matches[0]["path"]

print("\nArchivo seleccionado:")
print(selected_path)


# ------------------------------------------------------------
# 6. Cargar archivo según extensión
# ------------------------------------------------------------

suffix = selected_path.suffix.lower()

if suffix == ".csv":
    df = pd.read_csv(
        selected_path,
        dtype={
            "year": str,
            "entidad_id": str,
            "municipio_id": str,
            "geo_key": str
        },
        low_memory=False
    )

elif suffix in [".xlsx", ".xls"]:
    df = pd.read_excel(
        selected_path,
        dtype={
            "year": str,
            "entidad_id": str,
            "municipio_id": str,
            "geo_key": str
        }
    )

elif suffix == ".parquet":
    df = pd.read_parquet(selected_path)

else:
    raise ValueError(f"Extensión no soportada: {suffix}")


# ------------------------------------------------------------
# 7. Homologar llaves
# ------------------------------------------------------------

if "year" in df.columns:
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

if "entidad_id" in df.columns:
    df["entidad_id"] = df["entidad_id"].astype(str).str.strip().str.zfill(2)

if "municipio_id" in df.columns:
    df["municipio_id"] = df["municipio_id"].astype(str).str.strip().str.zfill(3)

if {"entidad_id", "municipio_id"}.issubset(df.columns):
    df["geo_key"] = df["entidad_id"] + df["municipio_id"]
elif "geo_key" in df.columns:
    df["geo_key"] = df["geo_key"].astype(str).str.strip().str.zfill(5)


# ------------------------------------------------------------
# 8. Reporte de carga
# ------------------------------------------------------------

print("\nARCHIVO CARGADO CORRECTAMENTE")
print("=" * 100)
print(f"Ruta cargada: {selected_path}")
print(f"Shape: {df.shape[0]:,} filas × {df.shape[1]:,} columnas")

print("\nColumnas disponibles:")
print("=" * 100)

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

print("\nVista rápida:")
display(df.head())

Mounted at /content/drive
Project path:
/content/drive/MyDrive/Nearshoring_Project

Processed path:
/content/drive/MyDrive/Nearshoring_Project/data/processed

Modeling output path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base

Coincidencias encontradas:
====================================================================================================
0 -> [municipality_industrial_b2b_opportunity_panel_curated] /content/drive/MyDrive/Nearshoring_Project/data/processed/municipality_industrial_b2b_opportunity_panel_curated.csv
1 -> [municipality_industrial_b2b_opportunity_panel] /content/drive/MyDrive/Nearshoring_Project/data/processed/municipality_industrial_b2b_opportunity_panel.csv
2 -> [municipality_industrial_b2b_opportunity_panel_raw] /content/drive/MyDrive/Nearshoring_Project/data/processed/municipality_industrial_b2b_opportunity_panel_raw.csv

Archivo seleccionado:
/content/drive/MyDrive/Nearshoring_Project/data/processed/municipality_industrial_b2b_opportunity_panel_curated.csv

ARCHIVO CARGADO CORRECTAMENTE
====================================================================================================
Ruta cargada: /content/drive/MyDrive/Nearshoring_Project/data/processed/municipality_industrial_b2b_opportunity_panel_curated.csv
Shape: 4,898 filas × 53 columnas

Columnas disponibles:
====================================================================================================
1. year
2. entidad_id
3. entidad_name
4. municipio_id
5. municipio_name
6. geo_key
7. industrial_capacity_score
8. industrial_capacity_percentile
9. rank_industrial_capacity_within_year
10. industrial_capacity_group
11. total_manufacturing_establishments
12. total_manufacturing_employment
13. total_manufacturing_value_added
14. total_manufacturing_income
15. total_manufacturing_investment
16. denue_manufacturing_establishments
17. denue_b2b_support_establishments
18. denue_logistics_storage_establishments
19. denue_professional_technical_establishments
20. denue_business_support_establishments
21. denue_b2b_support_scian_classes
22. denue_b2b_micro_establishments
23. denue_b2b_small_establishments
24. denue_b2b_medium_establishments
25. denue_b2b_large_establishments
26. denue_b2b_medium_large_establishments
27. share_b2b_micro_establishments
28. share_b2b_small_establishments
29. share_b2b_medium_establishments
30. share_b2b_large_establishments
31. share_b2b_medium_large_establishments
32. has_denue_match
33. has_b2b_support
34. has_b2b_medium_large
35. has_b2b_large
36. b2b_only_micro_small
37. b2b_support_percentile
38. b2b_medium_large_percentile
39. b2b_large_percentile
40. b2b_support_supply_score
41. b2b_support_supply_percentile
42. b2b_support_per_100_manufacturing_establishments
43. b2b_medium_large_per_100_manufacturing_establishments
44. b2b_large_per_100_manufacturing_establishments
45. b2b_support_per_1000_manufacturing_workers
46. b2b_medium_large_per_1000_manufacturing_workers
47. b2b_large_per_1000_manufacturing_workers
48. high_industrial_capacity
49. high_b2b_support
50. high_b2b_medium_large
51. high_b2b_large
52. industrial_b2b_typology_broad
53. industrial_b2b_typology_scaled

Vista rápida:

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,industrial_capacity_score,industrial_capacity_percentile,rank_industrial_capacity_within_year,industrial_capacity_group,...,b2b_large_per_100_manufacturing_establishments,b2b_support_per_1000_manufacturing_workers,b2b_medium_large_per_1000_manufacturing_workers,b2b_large_per_1000_manufacturing_workers,high_industrial_capacity,high_b2b_support,high_b2b_medium_large,high_b2b_large,industrial_b2b_typology_broad,industrial_b2b_typology_scaled
0,2018,15,México,106,Toluca,15106,0.992818,1.000000,1.0,Top industrial hub,...,1.631809,28.756669,1.746453,0.849303,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
1,2018,24,San Luis Potosí,028,San Luis Potosí,24028,0.992049,0.999555,2.0,Top industrial hub,...,2.327406,24.115603,1.689829,0.702780,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
2,2018,02,Baja California,004,Tijuana,02004,0.990813,0.999109,3.0,Top industrial hub,...,2.179837,15.830109,0.881302,0.296236,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
3,2018,22,Querétaro,014,Querétaro,22014,0.989939,0.998664,4.0,Top industrial hub,...,3.033006,34.275266,2.505587,0.986756,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub
4,2018,05,Coahuila de Zaragoza,035,Torreón,05035,0.989542,0.998218,5.0,Top industrial hub,...,3.861193,27.667200,2.379974,1.119155,1,1,1,1,Industrial ecosystem hub,Scaled industrial ecosystem hub

In [ ]:
# ============================================================
# 03. MUESTRA ALEATORIA: ID BÁSICO + FEATURES CANDIDATAS
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona desde cero después de cerrar sesión.
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
#
# Output:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/13_modeling_base_feature_sample.csv
# ============================================================


# ------------------------------------------------------------
# 0. Montar Google Drive de forma segura
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd

drive_root = Path("/content/drive/MyDrive")

if not drive_root.exists():
    from google.colab import drive
    drive.mount("/content/drive")
else:
    print("Google Drive ya está disponible.")


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

output_path = modeling_path / "13_modeling_base_feature_sample.csv"

print("Input path:")
print(input_path)

print("\nOutput path:")
print(output_path)

if not input_path.exists():
    raise FileNotFoundError(
        f"No encontré el archivo input en: {input_path}"
    )


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df_model = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df_model["year"] = pd.to_numeric(
    df_model["year"],
    errors="coerce"
).astype("Int64")

df_model["entidad_id"] = (
    df_model["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df_model["municipio_id"] = (
    df_model["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df_model["geo_key"] = (
    df_model["entidad_id"] + df_model["municipio_id"]
)

print("\nBase cargada:")
print(f"Filas: {df_model.shape[0]:,}")
print(f"Columnas: {df_model.shape[1]:,}")


# ------------------------------------------------------------
# 3. Definir columnas: SOLO ID básico + features candidatas
# ------------------------------------------------------------

id_cols = [
    "year",
    "entidad_name",
    "municipio_name",
    "geo_key"
]

feature_cols = [
    # Capacidad manufacturera
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",
    "denue_manufacturing_establishments",

    # Oferta B2B
    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    # Tamaño B2B
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",

    # Shares B2B
    "share_b2b_micro_establishments",
    "share_b2b_small_establishments",
    "share_b2b_medium_establishments",
    "share_b2b_large_establishments",
    "share_b2b_medium_large_establishments",

    # Ratios B2B / manufactura
    "b2b_support_per_100_manufacturing_establishments",
    "b2b_medium_large_per_100_manufacturing_establishments",
    "b2b_large_per_100_manufacturing_establishments",
    "b2b_support_per_1000_manufacturing_workers",
    "b2b_medium_large_per_1000_manufacturing_workers",
    "b2b_large_per_1000_manufacturing_workers"
]


# ------------------------------------------------------------
# 4. Seleccionar solo columnas existentes
# ------------------------------------------------------------

selected_cols = id_cols + feature_cols

existing_cols = [
    col for col in selected_cols
    if col in df_model.columns
]

missing_cols = [
    col for col in selected_cols
    if col not in df_model.columns
]

df_selected = df_model[existing_cols].copy()

print("\nColumnas seleccionadas:")
print(f"Existentes: {len(existing_cols)}")
print(f"Faltantes: {len(missing_cols)}")

if missing_cols:
    print("\nColumnas faltantes:")
    for col in missing_cols:
        print("-", col)


# ------------------------------------------------------------
# 5. Crear muestra aleatoria pequeña
# ------------------------------------------------------------

sample_size = 50
random_seed = 123

sample_size = min(sample_size, len(df_selected))

df_sample = (
    df_selected
    .sample(
        n=sample_size,
        random_state=random_seed
    )
    .sort_values(["year", "entidad_name", "municipio_name"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 6. Guardar muestra
# ------------------------------------------------------------

df_sample.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nMuestra creada correctamente")
print("=" * 100)
print(f"Filas: {df_sample.shape[0]:,}")
print(f"Columnas: {df_sample.shape[1]:,}")

print("\nArchivo guardado en:")
print(output_path)

display(df_sample)

Google Drive ya está disponible.
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Output path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/13_modeling_base_feature_sample.csv

Base cargada:
Filas: 4,530
Columnas: 54

Columnas seleccionadas:
Existentes: 31
Faltantes: 0

Muestra creada correctamente
====================================================================================================
Filas: 50
Columnas: 31

Archivo guardado en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/13_modeling_base_feature_sample.csv

,year,entidad_name,municipio_name,geo_key,total_manufacturing_establishments,total_manufacturing_employment,total_manufacturing_value_added,total_manufacturing_income,total_manufacturing_investment,denue_manufacturing_establishments,...,share_b2b_small_establishments,share_b2b_medium_establishments,share_b2b_large_establishments,share_b2b_medium_large_establishments,b2b_support_per_100_manufacturing_establishments,b2b_medium_large_per_100_manufacturing_establishments,b2b_large_per_100_manufacturing_establishments,b2b_support_per_1000_manufacturing_workers,b2b_medium_large_per_1000_manufacturing_workers,b2b_large_per_1000_manufacturing_workers
0,2018,Hidalgo,Pisaflores,13049,30.0,49.0,2.346,6.446,0.365,30.0,...,0.000000,0.000000,0.000000,0.000000,23.333333,0.000000,0.000000,142.857143,0.000000,0.000000
1,2018,Jalisco,Acatlán de Juárez,14002,80.0,1227.0,909.253,2323.086,27.141,84.0,...,0.058824,0.000000,0.000000,0.000000,42.500000,0.000000,0.000000,27.709861,0.000000,0.000000
2,2018,Jalisco,Degollado,14033,169.0,683.0,67.492,169.123,0.462,164.0,...,0.000000,0.000000,0.000000,0.000000,27.218935,0.000000,0.000000,67.349927,0.000000,0.000000
3,2018,Jalisco,Juanacatlán,14051,33.0,628.0,45.653,496.985,20.842,44.0,...,0.071429,0.071429,0.000000,0.071429,42.424242,3.030303,0.000000,22.292994,1.592357,0.000000
4,2018,Michoacán de Ocampo,Pátzcuaro,16066,1022.0,2302.0,159.563,451.710,6.363,936.0,...,0.069444,0.004630,0.004630,0.009259,21.135029,0.195695,0.097847,93.831451,0.868810,0.434405
5,2018,México,Lerma,15051,1000.0,47458.0,30196.534,97585.051,2648.133,931.0,...,0.122302,0.053957,0.035971,0.089928,27.800000,2.500000,1.000000,5.857811,0.526782,0.210713
6,2018,Oaxaca,San Antonio Nanahuatípam,20109,5.0,8.0,0.495,0.845,0.030,3.0,...,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0.000000,125.000000,0.000000,0.000000
7,2018,Oaxaca,San Juan Lachigalla,20203,21.0,58.0,0.709,1.497,0.260,2.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2018,Oaxaca,San Pablo Coatlán,20291,11.0,17.0,1.310,2.333,0.000,7.0,...,0.000000,0.000000,0.000000,0.000000,18.181818,0.000000,0.000000,117.647059,0.000000,0.000000
9,2018,Puebla,Ajalpan,21010,2371.0,8059.0,486.778,890.787,21.721,1620.0,...,0.014286,0.014286,0.000000,0.014286,2.952341,0.042176,0.000000,8.685941,0.124085,0.000000
10,2018,Puebla,Tepango de Rodríguez,21162,45.0,87.0,2.454,6.215,0.005,49.0,...,0.000000,0.000000,0.000000,0.000000,11.111111,0.000000,0.000000,57.471264,0.000000,0.000000
11,2018,Quintana Roo,Othón P. Blanco,23004,578.0,2904.0,650.444,3102.679,40.981,625.0,...,0.159389,0.041485,0.010917,0.052402,79.238754,4.152249,0.865052,157.713499,8.264463,1.721763
12,2018,Sonora,Mazatán,26037,18.0,36.0,1.965,4.891,-0.004,7.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,2018,Tabasco,Teapa,27016,162.0,537.0,93.208,278.659,0.826,162.0,...,0.162500,0.012500,0.012500,0.025000,49.382716,1.234568,0.617284,148.975791,3.724395,1.862197
14,2018,Tamaulipas,González,28012,129.0,767.0,62.327,246.577,2.070,131.0,...,0.054545,0.000000,0.000000,0.000000,42.635659,0.000000,0.000000,71.707953,0.000000,0.000000
15,2018,Tamaulipas,Tula,28039,85.0,188.0,15.592,35.415,0.086,77.0,...,0.111111,0.000000,0.000000,0.000000,31.764706,0.000000,0.000000,143.617021,0.000000,0.000000
16,2018,Tlaxcala,Cuapiaxtla,29008,89.0,611.0,223.527,1048.470,0.795,76.0,...,0.066667,0.000000,0.000000,0.000000,16.853933,0.000000,0.000000,24.549918,0.000000,0.000000
17,2023,Aguascalientes,Asientos,01002,109.0,365.0,56.486,107.353,0.894,88.0,...,0.050000,0.000000,0.000000,0.000000,18.348624,0.000000,0.000000,54.794521,0.000000,0.000000
18,2023,Chiapas,Huehuetán,07037,121.0,291.0,34.479,114.076,0.051,118.0,...,0.178571,0.000000,0.000000,0.000000,23.140496,0.000000,0.000000,96.219931,0.000000,0.000000
19,2023,Chiapas,Osumacinta,07063,17.0,34.0,4.168,7.081,0.017,12.0,...,0.333333,0.000000,0.000000,0.000000,17.647059,0.000000,0.000000,88.235294,0.000000,0.000000
20,2023,Chiapas,Yajalón,07109,191.0,469.0,34.213,93.938,0.059,167.0,...,0.060606,0.075758,0.000000,0.075758,34.554974,2.617801,0.000000,140.724947,10.660981,0.000000
21,2023,Chihuahua,Matachí,08043,9.0,863.0,104.425,150.367,3.051,5.0,...,0.000000,0.000000,0.000000,0.000000,22.222222,0.000000,0.000000,2.317497,0.000000,0.000000
22,2023,Guanajuato,Cuerámaro,11012,175.0,882.0,144.202,354.446,0.286,145.0,...,0.040000,0.000000,0.000000,0.000000,28.571429,0.000000,0.000000,56.689342,0.000000,0.000000
23,2023,Guerrero,Iliatenco,12081,25.0,75.0,6.779,16.735,0.136,14.0,...,0.000000,0.000000,0.000000,0.000000,76.000000,0.000000,0.000000,253.333333,0.000000,0.000000
24,2023,Guerrero,Tlacoachistlahuaca,12062,567.0,652.0,24.150,48.569,-0.139,596.0,...,0.000000,0.000000,0.000000,0.000000,1.058201,0.000000,0.000000,9.202454,0.000000,0.000000
25,2023,Hidalgo,Tulancingo de Bravo,13077,1080.0,5520.0,1205.840,3488.478,23.844,1202.0,...,0.114964,0.012774,0.009124,0.021898,50.740741,1.111111,0.462963,99.275362,2.173913,0.905797
26,2023,Michoacán de Ocampo,Cherán,16024,694.0,1170.0,87.025,192.049,5.156,536.0,...,0.000000,0.000000,0.000000,0.000000,8.213256,0.000000,0.000000,48.717949,0.000000,0.000000
27,2023,México,Chalco,15025,1744.0,14262.0,4209.018,11350.004,90.079,1521.0,...,0.054581,0.007797,0.007797,0.015595,29.415138,0.458716,0.229358,35.969710,0.560931,0.280466
28,2023,México,Jilotepec,15045,292.0,15465.0,8094.194,42852.344,1119.560,248.0,...,0.091603,0.022901,0.007634,0.030534,44.863014,1.369863,0.342466,8.470740,0.258649,0.064662
29,2023,México,Malinalco,15052,257.0,476.0,35.917,92.286,0.501,224.0,...,0.058824,0.000000,0.000000,0.000000,13.229572,0.000000,0.000000,71.428571,0.000000,0.000000
30,2023,México,Teoloyucan,15091,342.0,2509.0,941.686,3080.853,141.768,258.0,...,0.045872,0.027523,0.000000,0.027523,31.871345,0.877193,0.000000,43.443603,1.195695,0.000000
31,2023,Nayarit,Xalisco,18008,257.0,707.0,212.715,481.871,4.346,259.0,...,0.173913,0.028986,0.000000,0.028986,26.848249,0.778210,0.000000,97.595474,2.828854,0.000000
32,2023,Oaxaca,Ciénega de Zimatlán,20013,62.0,131.0,17.430,35.137,0.104,81.0,...,0.111111,0.000000,0.000000,0.000000,14.516129,0.000000,0.000000,68.702290,0.000000,0.000000
33,2023,Oaxaca,San Pedro Mixtepec,20318,828.0,1662.0,222.539,529.973,2.152,659.0,...,0.149194,0.036290,0.004032,0.040323,29.951691,1.207729,0.120773,149.217810,6.016847,0.601685
34,2023,Oaxaca,San Pedro Yólox,20336,6.0,8.0,0.317,0.888,0.027,11.0,...,0.000000,0.000000,0.000000,0.000000,66.666667,0.000000,0.000000,500.000000,0.000000,0.000000
35,2023,Oaxaca,Santiago Tilantongo,20492,10.0,17.0,0.224,1.122,0.010,12.0,...,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,58.823529,0.000000,0.000000
36,2023,Puebla,Zinacatepec,21214,423.0,1256.0,76.844,147.387,-0.768,448.0,...,0.000000,0.000000,0.000000,0.000000,6.619385,0.000000,0.000000,22.292994,0.000000,0.000000
37,2023,Sonora,Huépac,26034,8.0,9.0,0.511,1.109,0.000,3.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,2023,Tlaxcala,Calpulalpan,29006,705.0,2371.0,1106.546,2407.616,45.172,524.0,...,0.125000,0.008929,0.008929,0.017857,15.886525,0.283688,0.141844,47.237453,0.843526,0.421763
39,2023,Tlaxcala,Santa Cruz Tlaxcala,29026,203.0,647.0,76.002,151.135,1.980,130.0,...,0.205882,0.000000,0.000000,0.000000,16.748768,0.000000,0.000000,52.550232,0.000000,0.000000
40,2023,Tlaxcala,Ziltlaltépec de Trinidad Sánchez Santos,29037,92.0,678.0,588.424,2406.182,-64.682,62.0,...,0.000000,0.000000,0.000000,0.000000,4.347826,0.000000,0.000000,5.899705,0.000000,0.000000
41,2023,Veracruz de Ignacio de la Llave,Carlos A. Carrillo,30208,116.0,2024.0,2849.698,5183.715,2.189,106.0,...,0.000000,0.000000,0.000000,0.000000,12.068966,0.000000,0.000000,6.916996,0.000000,0.000000
42,2023,Veracruz de Ignacio de la Llave,Filomeno Mata,30067,69.0,174.0,12.408,31.638,-0.062,65.0,...,0.000000,0.000000,0.000000,0.000000,26.086957,0.000000,0.000000,103.448276,0.000000,0.000000
43,2023,Veracruz de Ignacio de la Llave,Ixhuatlancillo,30081,189.0,341.0,15.678,32.129,-0.002,124.0,...,0.000000,0.076923,0.000000,0.076923,6.878307,0.529101,0.000000,38.123167,2.932551,0.000000
44,2023,Veracruz de Ignacio de la Llave,Papantla,30124,552.0,1177.0,67.701,392.738,1.464,575.0,...,0.058824,0.007353,0.007353,0.014706,24.637681,0.362319,0.181159,115.548003,1.699235,0.849618
45,2023,Veracruz de Ignacio de la Llave,Soconusco,30145,62.0,109.0,5.419,13.990,0.026,52.0,...,0.000000,0.000000,0.000000,0.000000,27.419355,0.000000,0.000000,155.963303,0.000000,0.000000
46,2023,Veracruz de Ignacio de la Llave,Tatahuicapan de Juárez,30209,71.0,164.0,19.697,44.361,0.134,65.0,...,0.000000,0.000000,0.000000,0.000000,15.492958,0.000000,0.000000,67.073171,0.000000,0.000000
47,2023,Veracruz de Ignacio de la Llave,Xalapa,30087,2407.0,7159.0,1298.908,3521.864,64.623,2480.0,...,0.179525,0.022997,0.017804,0.040801,56.003324,2.285002,0.997092,188.294455,7.682637,3.352424
48,2023,Yucatán,Tahmek,31074,33.0,91.0,6.452,15.139,0.019,28.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,2023,Yucatán,Tekantó,31078,77.0,235.0,64.133,76.211,0.034,67.0,...,0.000000,0.000000,0.000000,0.000000,5.194805,0.000000,0.000000,17.021277,0.000000,0.000000

In [ ]:
# ============================================================
# 04. VARIABLE DE CONSISTENCIA ENTRE SAIC Y DENUE MANUFACTURA
# Nearshoring Project / Market Opportunity Analytics
#
# Este script funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Construir variables auxiliares de consistencia entre:
# - total_manufacturing_establishments
# - denue_manufacturing_establishments
#
# Estas variables NO serán input del scoring/clustering.
# Sirven para auditoría, interpretación y conteo de consistencia.
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
#
# Outputs:
# 14_modeling_base_with_manufacturing_consistency.csv
# 15_manufacturing_source_consistency_summary.csv
# 16_manufacturing_source_consistency_examples.csv
# ============================================================


# ------------------------------------------------------------
# 0. Montar Google Drive de forma segura
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np

drive_root = Path("/content/drive/MyDrive")

if not drive_root.exists():
    from google.colab import drive
    drive.mount("/content/drive")
else:
    print("Google Drive ya está disponible.")


# ------------------------------------------------------------
# 1. Definir rutas
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

output_base_path = (
    modeling_path / "14_modeling_base_with_manufacturing_consistency.csv"
)

summary_output_path = (
    modeling_path / "15_manufacturing_source_consistency_summary.csv"
)

examples_output_path = (
    modeling_path / "16_manufacturing_source_consistency_examples.csv"
)

print("Input path:")
print(input_path)

print("\nOutput path:")
print(output_base_path)

if not input_path.exists():
    raise FileNotFoundError(
        f"No encontré el archivo input en: {input_path}"
    )


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(
    df["year"],
    errors="coerce"
).astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = (
    df["entidad_id"] + df["municipio_id"]
)

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Validar columnas necesarias
# ------------------------------------------------------------

saic_col = "total_manufacturing_establishments"
denue_col = "denue_manufacturing_establishments"

required_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",
    saic_col,
    denue_col
]

missing_cols = [
    col for col in required_cols
    if col not in df.columns
]

if missing_cols:
    raise ValueError(
        f"Faltan columnas necesarias en la base: {missing_cols}"
    )

df[saic_col] = pd.to_numeric(
    df[saic_col],
    errors="coerce"
)

df[denue_col] = pd.to_numeric(
    df[denue_col],
    errors="coerce"
)


# ------------------------------------------------------------
# 4. Calcular percentiles por año
# ------------------------------------------------------------
# La comparación se hace dentro de cada año.
# Así evitamos comparar niveles absolutos de 2018 contra 2023.

df["saic_manufacturing_establishments_percentile"] = (
    df
    .groupby("year")[saic_col]
    .rank(pct=True, method="average")
)

df["denue_manufacturing_establishments_percentile"] = (
    df
    .groupby("year")[denue_col]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 5. Calcular diferencia percentil y score de consistencia
# ------------------------------------------------------------

df["manufacturing_source_percentile_gap"] = (
    df["saic_manufacturing_establishments_percentile"]
    - df["denue_manufacturing_establishments_percentile"]
).abs()

df["manufacturing_source_consistency_score"] = (
    1 - df["manufacturing_source_percentile_gap"]
)


# ------------------------------------------------------------
# 6. Crear variable categórica de consistencia
# ------------------------------------------------------------
# Regla:
# gap <= 0.15        -> Alta consistencia
# 0.15 < gap <= 0.30 -> Consistencia media
# gap > 0.30         -> Baja consistencia

def classify_consistency(gap):
    if pd.isna(gap):
        return "Sin información"
    elif gap <= 0.15:
        return "Alta consistencia"
    elif gap <= 0.30:
        return "Consistencia media"
    else:
        return "Baja consistencia"


df["manufacturing_source_consistency_group"] = (
    df["manufacturing_source_percentile_gap"]
    .apply(classify_consistency)
)


# ------------------------------------------------------------
# 7. Resumen por año y grupo
# ------------------------------------------------------------

consistency_summary = (
    df
    .groupby(
        ["year", "manufacturing_source_consistency_group"],
        dropna=False
    )
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_gap=("manufacturing_source_percentile_gap", "mean"),
        avg_consistency_score=("manufacturing_source_consistency_score", "mean"),
        avg_saic_manufacturing_establishments=(saic_col, "mean"),
        avg_denue_manufacturing_establishments=(denue_col, "mean")
    )
    .reset_index()
)

consistency_summary["share_municipality_years"] = (
    consistency_summary["n_municipality_years"]
    / consistency_summary.groupby("year")["n_municipality_years"].transform("sum")
)

# Orden más legible
group_order = {
    "Alta consistencia": 1,
    "Consistencia media": 2,
    "Baja consistencia": 3,
    "Sin información": 4
}

consistency_summary["group_order"] = (
    consistency_summary["manufacturing_source_consistency_group"]
    .map(group_order)
)

consistency_summary = (
    consistency_summary
    .sort_values(["year", "group_order"])
    .drop(columns=["group_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 8. Tabla de ejemplos para revisar municipios
# ------------------------------------------------------------

example_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",
    saic_col,
    denue_col,
    "saic_manufacturing_establishments_percentile",
    "denue_manufacturing_establishments_percentile",
    "manufacturing_source_percentile_gap",
    "manufacturing_source_consistency_score",
    "manufacturing_source_consistency_group"
]

consistency_examples = (
    df[example_cols]
    .sort_values(
        ["year", "manufacturing_source_percentile_gap"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 9. Guardar outputs
# ------------------------------------------------------------

df.to_csv(
    output_base_path,
    index=False,
    encoding="utf-8-sig"
)

consistency_summary.to_csv(
    summary_output_path,
    index=False,
    encoding="utf-8-sig"
)

consistency_examples.to_csv(
    examples_output_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 10. Mostrar resultados
# ------------------------------------------------------------

print("\nRESUMEN DE CONSISTENCIA")
print("=" * 100)
display(consistency_summary)

print("\nEJEMPLOS CON MAYOR DIFERENCIA ENTRE FUENTES")
print("=" * 100)
display(consistency_examples.head(30))

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas originales:", len(df))
print("Missing en percentil SAIC:", df["saic_manufacturing_establishments_percentile"].isna().sum())
print("Missing en percentil DENUE:", df["denue_manufacturing_establishments_percentile"].isna().sum())
print("Missing en gap:", df["manufacturing_source_percentile_gap"].isna().sum())

print("\nArchivos guardados en:")
print(modeling_path)

print("\nArchivo principal con consistencia:")
print(output_base_path)

print("\nResumen de consistencia:")
print(summary_output_path)

print("\nEjemplos de consistencia:")
print(examples_output_path)

Mounted at /content/drive
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Output path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/14_modeling_base_with_manufacturing_consistency.csv

Base cargada:
Filas: 4,530
Columnas: 54

RESUMEN DE CONSISTENCIA
====================================================================================================

,year,manufacturing_source_consistency_group,n_municipality_years,n_municipalities,avg_gap,avg_consistency_score,avg_saic_manufacturing_establishments,avg_denue_manufacturing_establishments,share_municipality_years
0,2018,Alta consistencia,2173,2173,0.037140,0.962860,263.509434,242.213530,0.967929
1,2018,Consistencia media,61,61,0.190095,0.809905,76.754098,43.655738,0.027171
2,2018,Baja consistencia,11,11,0.428002,0.571998,148.909091,17.363636,0.004900
3,2023,Alta consistencia,2238,2238,0.034487,0.965513,281.162645,271.339589,0.979431
4,2023,Consistencia media,38,38,0.191812,0.808188,76.552632,43.763158,0.016630
5,2023,Baja consistencia,9,9,0.530975,0.469025,156.000000,105.333333,0.003939

EJEMPLOS CON MAYOR DIFERENCIA ENTRE FUENTES
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,total_manufacturing_establishments,denue_manufacturing_establishments,saic_manufacturing_establishments_percentile,denue_manufacturing_establishments_percentile,manufacturing_source_percentile_gap,manufacturing_source_consistency_score,manufacturing_source_consistency_group
0,2018,17,Morelos,035,Xoxocotla,17035,208.0,0.0,0.738976,0.001336,0.737639,0.262361,Baja consistencia
1,2018,20,Oaxaca,015,Coatecas Altas,20015,142.0,3.0,0.661693,0.019376,0.642316,0.357684,Baja consistencia
2,2018,20,Oaxaca,534,San Vicente Coatlán,20534,215.0,16.0,0.746993,0.197773,0.549220,0.450780,Baja consistencia
3,2018,17,Morelos,034,Coatetelco,17034,74.0,0.0,0.506904,0.001336,0.505568,0.494432,Baja consistencia
4,2018,20,Oaxaca,182,San Juan Bautista Tlacoatzintepec,20182,44.0,2.0,0.371492,0.010022,0.361470,0.638530,Baja consistencia
5,2018,20,Oaxaca,353,Santa Ana,20353,70.0,13.0,0.494209,0.161693,0.332517,0.667483,Baja consistencia
6,2018,20,Oaxaca,367,Santa Catarina Mechoacán,20367,140.0,30.0,0.657461,0.328508,0.328953,0.671047,Baja consistencia
7,2018,20,Oaxaca,300,San Pedro Amuzgos,20300,477.0,76.0,0.873497,0.551225,0.322272,0.677728,Baja consistencia
8,2018,31,Yucatán,017,Chankom,31017,47.0,7.0,0.389310,0.073942,0.315367,0.684633,Baja consistencia
9,2018,20,Oaxaca,447,Santa María Zacatepec,20447,184.0,41.0,0.715145,0.403118,0.312027,0.687973,Baja consistencia
10,2018,20,Oaxaca,466,Santiago Ixtayutla,20466,37.0,3.0,0.320045,0.019376,0.300668,0.699332,Baja consistencia
11,2018,20,Oaxaca,497,Santiago Yaitepec,20497,278.0,62.0,0.797327,0.506013,0.291314,0.708686,Consistencia media
12,2018,20,Oaxaca,506,Santo Domingo Albarradas,20506,50.0,10.0,0.402227,0.118708,0.283519,0.716481,Consistencia media
13,2018,17,Morelos,015,Miacatlán,17015,49.0,126.0,0.395991,0.676837,0.280846,0.719154,Consistencia media
14,2018,20,Oaxaca,207,San Juan Mazatlán,20207,30.0,2.0,0.282851,0.010022,0.272829,0.727171,Consistencia media
15,2018,20,Oaxaca,105,San Antonino Monte Verde,20105,85.0,24.0,0.542094,0.277506,0.264588,0.735412,Consistencia media
16,2018,20,Oaxaca,412,Santa María Guienagati,20412,76.0,22.0,0.514922,0.258575,0.256347,0.743653,Consistencia media
17,2018,20,Oaxaca,136,San Felipe Usila,20136,138.0,43.0,0.654788,0.414254,0.240535,0.759465,Consistencia media
18,2018,20,Oaxaca,232,San Lucas Ojitlán,20232,202.0,60.0,0.732294,0.496214,0.236080,0.763920,Consistencia media
19,2018,20,Oaxaca,467,Santiago Jamiltepec,20467,251.0,72.0,0.777506,0.541648,0.235857,0.764143,Consistencia media
20,2018,31,Yucatán,060,Quintana Roo,31060,50.0,14.0,0.402227,0.174165,0.228062,0.771938,Consistencia media
21,2018,21,Puebla,078,Huitzilan de Serdán,21078,65.0,21.0,0.473051,0.248552,0.224499,0.775501,Consistencia media
22,2018,20,Oaxaca,111,San Antonio Tepetlapa,20111,41.0,11.0,0.352561,0.130067,0.222494,0.777506,Consistencia media
23,2018,20,Oaxaca,278,San Miguel Soyaltepec,20278,121.0,42.0,0.624944,0.408909,0.216036,0.783964,Consistencia media
24,2018,20,Oaxaca,452,Santiago Apóstol,20452,238.0,79.0,0.766370,0.562584,0.203786,0.796214,Consistencia media
25,2018,20,Oaxaca,309,San Pedro Ixcatlán,20309,105.0,40.0,0.597996,0.396659,0.201336,0.798664,Consistencia media
26,2018,20,Oaxaca,517,Santo Domingo Tepuxtepec,20517,25.0,5.0,0.239866,0.040535,0.199332,0.800668,Consistencia media
27,2018,20,Oaxaca,160,San Jerónimo Silacayoapilla,20160,25.0,48.0,0.239866,0.438085,0.198218,0.801782,Consistencia media
28,2018,20,Oaxaca,203,San Juan Lachigalla,20203,21.0,2.0,0.203341,0.010022,0.193318,0.806682,Consistencia media
29,2018,20,Oaxaca,555,Trinidad Zaachila,20555,21.0,2.0,0.203341,0.010022,0.193318,0.806682,Consistencia media

VALIDACIÓN RÁPIDA
====================================================================================================
Filas originales: 4530
Missing en percentil SAIC: 0
Missing en percentil DENUE: 0
Missing en gap: 0

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base

Archivo principal con consistencia:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/14_modeling_base_with_manufacturing_consistency.csv

Resumen de consistencia:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/15_manufacturing_source_consistency_summary.csv

Ejemplos de consistencia:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/16_manufacturing_source_consistency_examples.csv

In [ ]:
# ============================================================
# 05. DIAGNÓSTICO DEL INDUSTRIAL DEMAND SCORE
# Nearshoring Project / Market Opportunity Analytics
#
# Este script funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Calcular y revisar el componente de demanda industrial,
# sin guardar todavía una nueva base completa de scoring.
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
#
# Outputs:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/
#   01_industrial_demand_score_diagnostic.csv
#   02_industrial_demand_score_summary.csv
#   03_industrial_demand_top_municipalities.csv
#   04_industrial_demand_score_weights.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje seguro de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np

drive_root = Path("/content/drive/MyDrive")

if not drive_root.exists():
    from google.colab import drive
    drive.mount("/content/drive")
else:
    print("Google Drive ya está disponible.")


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = Path("/content/drive/MyDrive/Nearshoring_Project")

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

diagnostics_path = modeling_path / "scoring_diagnostics"
diagnostics_path.mkdir(parents=True, exist_ok=True)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

demand_diagnostic_path = (
    diagnostics_path / "01_industrial_demand_score_diagnostic.csv"
)

demand_summary_path = (
    diagnostics_path / "02_industrial_demand_score_summary.csv"
)

top_demand_path = (
    diagnostics_path / "03_industrial_demand_top_municipalities.csv"
)

weights_path = (
    diagnostics_path / "04_industrial_demand_score_weights.csv"
)

print("Input path:")
print(input_path)

print("\nDiagnostics path:")
print(diagnostics_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(
    df["year"],
    errors="coerce"
).astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Definir variables y pesos del score de demanda
# ------------------------------------------------------------

demand_features = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

demand_weights = {
    "total_manufacturing_establishments": 0.25,
    "total_manufacturing_employment": 0.20,
    "total_manufacturing_value_added": 0.25,
    "total_manufacturing_income": 0.20,
    "total_manufacturing_investment": 0.10
}

missing_features = [
    col for col in demand_features
    if col not in df.columns
]

if missing_features:
    raise ValueError(f"Faltan variables para demanda: {missing_features}")

if not np.isclose(sum(demand_weights.values()), 1.0):
    raise ValueError("Los pesos del score de demanda no suman 1.")


# ------------------------------------------------------------
# 4. Validar y convertir variables
# ------------------------------------------------------------

for col in demand_features:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_demand = df[demand_features].isna().sum()

print("\nMissing en variables de demanda:")
print(missing_demand)

if missing_demand.sum() > 0:
    raise ValueError(
        "Hay missing en variables de demanda. "
        "Revisa que estés usando 08_modeling_base_complete_cases.csv."
    )


# ------------------------------------------------------------
# 5. Normalización por percentiles dentro de cada año
# ------------------------------------------------------------

for col in demand_features:
    percentile_col = f"{col}_demand_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )


# ------------------------------------------------------------
# 6. Construir industrial_demand_score
# ------------------------------------------------------------

df["industrial_demand_score"] = 0.0

for col, weight in demand_weights.items():
    percentile_col = f"{col}_demand_percentile"
    df["industrial_demand_score"] += df[percentile_col] * weight

df["industrial_demand_percentile"] = (
    df
    .groupby("year")["industrial_demand_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 7. Grupo interpretable
# ------------------------------------------------------------

def classify_demand_group(p):
    if pd.isna(p):
        return "Sin información"
    elif p >= 0.90:
        return "Top industrial demand"
    elif p >= 0.75:
        return "High industrial demand"
    elif p >= 0.50:
        return "Medium industrial demand"
    else:
        return "Low industrial demand"


df["industrial_demand_group"] = (
    df["industrial_demand_percentile"]
    .apply(classify_demand_group)
)


# ------------------------------------------------------------
# 8. Crear tabla diagnóstica compacta
# ------------------------------------------------------------

diagnostic_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",
    *demand_features,
    *[f"{col}_demand_percentile" for col in demand_features],
    "industrial_demand_score",
    "industrial_demand_percentile",
    "industrial_demand_group"
]

demand_diagnostic = df[diagnostic_cols].copy()


# ------------------------------------------------------------
# 9. Resumen por año y grupo
# ------------------------------------------------------------

demand_summary = (
    demand_diagnostic
    .groupby(["year", "industrial_demand_group"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_industrial_demand_score=("industrial_demand_score", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_manufacturing_establishments=("total_manufacturing_establishments", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_manufacturing_value_added=("total_manufacturing_value_added", "mean"),
        avg_manufacturing_income=("total_manufacturing_income", "mean"),
        avg_manufacturing_investment=("total_manufacturing_investment", "mean")
    )
    .reset_index()
)

demand_summary["share_municipality_years"] = (
    demand_summary["n_municipality_years"]
    / demand_summary.groupby("year")["n_municipality_years"].transform("sum")
)

group_order = {
    "Top industrial demand": 1,
    "High industrial demand": 2,
    "Medium industrial demand": 3,
    "Low industrial demand": 4,
    "Sin información": 5
}

demand_summary["group_order"] = (
    demand_summary["industrial_demand_group"]
    .map(group_order)
)

demand_summary = (
    demand_summary
    .sort_values(["year", "group_order"])
    .drop(columns=["group_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Top municipios por año
# ------------------------------------------------------------

top_demand = (
    demand_diagnostic
    .sort_values(
        ["year", "industrial_demand_score"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. Tabla de pesos
# ------------------------------------------------------------

weights_table = pd.DataFrame({
    "feature": list(demand_weights.keys()),
    "weight": list(demand_weights.values()),
    "score_block": "industrial_demand_score",
    "normalization": "Percentile rank within year",
    "interpretation": [
        "Base manufacturera amplia; aproxima número potencial de clientes",
        "Escala operativa de la manufactura local",
        "Intensidad productiva y generación de valor",
        "Escala económica del mercado manufacturero",
        "Dinamismo productivo; menor peso por volatilidad"
    ]
})


# ------------------------------------------------------------
# 12. Guardar diagnósticos
# ------------------------------------------------------------

demand_diagnostic.to_csv(
    demand_diagnostic_path,
    index=False,
    encoding="utf-8-sig"
)

demand_summary.to_csv(
    demand_summary_path,
    index=False,
    encoding="utf-8-sig"
)

top_demand.to_csv(
    top_demand_path,
    index=False,
    encoding="utf-8-sig"
)

weights_table.to_csv(
    weights_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 13. Mostrar resultados
# ------------------------------------------------------------

print("\nPESOS")
display(weights_table)

print("\nRESUMEN DEL SCORE DE DEMANDA")
display(demand_summary)

print("\nTOP MUNICIPIOS POR DEMANDA INDUSTRIAL")
display(top_demand.head(30))

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas diagnosticadas:", len(demand_diagnostic))
print("Missing industrial_demand_score:", demand_diagnostic["industrial_demand_score"].isna().sum())
print("Missing industrial_demand_percentile:", demand_diagnostic["industrial_demand_percentile"].isna().sum())
print("Años:", sorted(demand_diagnostic["year"].dropna().unique()))

print("\nArchivos guardados en:")
print(diagnostics_path)

Google Drive ya está disponible.
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Diagnostics path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics

Base cargada:
Filas: 4,530
Columnas: 54

Missing en variables de demanda:
total_manufacturing_establishments    0
total_manufacturing_employment        0
total_manufacturing_value_added       0
total_manufacturing_income            0
total_manufacturing_investment        0
dtype: int64

PESOS

,feature,weight,score_block,normalization,interpretation
0,total_manufacturing_establishments,0.25,industrial_demand_score,Percentile rank within year,Base manufacturera amplia; aproxima número pot...
1,total_manufacturing_employment,0.20,industrial_demand_score,Percentile rank within year,Escala operativa de la manufactura local
2,total_manufacturing_value_added,0.25,industrial_demand_score,Percentile rank within year,Intensidad productiva y generación de valor
3,total_manufacturing_income,0.20,industrial_demand_score,Percentile rank within year,Escala económica del mercado manufacturero
4,total_manufacturing_investment,0.10,industrial_demand_score,Percentile rank within year,Dinamismo productivo; menor peso por volatilidad

RESUMEN DEL SCORE DE DEMANDA

,year,industrial_demand_group,n_municipality_years,n_municipalities,avg_industrial_demand_score,avg_industrial_demand_percentile,avg_manufacturing_establishments,avg_manufacturing_employment,avg_manufacturing_value_added,avg_manufacturing_income,avg_manufacturing_investment,share_municipality_years
0,2018,Top industrial demand,225,225,0.932010,0.950111,1347.062222,24004.884444,12906.339018,44234.194956,868.796707,0.100223
1,2018,High industrial demand,337,337,0.792753,0.824944,408.050445,2073.697329,663.823421,2511.692582,62.575967,0.150111
2,2018,Medium industrial demand,561,561,0.614466,0.624944,173.322638,534.165775,104.028319,511.279567,0.915439,0.249889
3,2018,Low industrial demand,1122,1122,0.268649,0.250111,36.622103,77.178253,4.760471,15.059394,0.112602,0.499777
4,2023,Top industrial demand,229,229,0.927890,0.950109,1410.205240,26176.558952,20923.204515,55949.689664,971.931192,0.100219
5,2023,High industrial demand,343,343,0.788304,0.824945,454.285714,2250.559767,1497.668501,5881.128854,0.694915,0.150109
6,2023,Medium industrial demand,571,571,0.614636,0.624945,186.845884,562.936953,134.185007,353.465674,2.785671,0.249891
7,2023,Low industrial demand,1142,1142,0.270725,0.250109,42.126970,88.134851,7.700065,18.856389,0.141715,0.499781

TOP MUNICIPIOS POR DEMANDA INDUSTRIAL

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,total_manufacturing_establishments,total_manufacturing_employment,total_manufacturing_value_added,total_manufacturing_income,total_manufacturing_investment,total_manufacturing_establishments_demand_percentile,total_manufacturing_employment_demand_percentile,total_manufacturing_value_added_demand_percentile,total_manufacturing_income_demand_percentile,total_manufacturing_investment_demand_percentile,industrial_demand_score,industrial_demand_percentile,industrial_demand_group
0,2018,15,México,106,Toluca,15106,4351.0,83598.0,97605.998,334675.563,3917.262,0.995991,0.994655,1.000000,1.000000,0.993764,0.997305,1.000000,Top industrial demand
1,2018,24,San Luis Potosí,028,San Luis Potosí,24028,3824.0,126640.0,77223.073,274960.549,8373.471,0.993318,0.998218,0.998218,0.998218,0.999555,0.997127,0.999555,Top industrial demand
2,2018,02,Baja California,004,Tijuana,02004,3670.0,270055.0,85526.588,222120.705,5618.985,0.992428,0.999555,0.999109,0.995991,0.998218,0.996815,0.999109,Top industrial demand
3,2018,14,Jalisco,039,Guadalajara,14039,8007.0,113447.0,51727.982,163458.345,2409.978,0.999555,0.996882,0.994655,0.993318,0.987528,0.995345,0.998664,Top industrial demand
4,2018,22,Querétaro,014,Querétaro,22014,3363.0,103369.0,60661.916,229532.904,12126.712,0.991091,0.995991,0.995100,0.996882,1.000000,0.995122,0.998218,Top industrial demand
5,2018,01,Aguascalientes,001,Aguascalientes,01001,3896.0,71120.0,71526.587,257820.921,3845.502,0.994209,0.991982,0.996882,0.997773,0.993318,0.995056,0.997773,Top industrial demand
6,2018,14,Jalisco,120,Zapopan,14120,4395.0,121731.0,51124.248,142709.014,2894.772,0.996437,0.997327,0.993764,0.990646,0.989310,0.994076,0.997327,Top industrial demand
7,2018,19,Nuevo León,039,Monterrey,19039,4729.0,75640.0,49357.178,151078.236,3248.158,0.997327,0.994209,0.993318,0.991091,0.992428,0.993964,0.996882,Top industrial demand
8,2018,08,Chihuahua,037,Juárez,08037,2375.0,329725.0,92715.360,157045.359,3176.689,0.985301,1.000000,0.999555,0.992428,0.991537,0.993853,0.996437,Top industrial demand
9,2018,05,Coahuila de Zaragoza,030,Saltillo,05030,2654.0,71941.0,74250.522,296390.165,3237.461,0.987528,0.992428,0.997773,0.999109,0.991982,0.993831,0.995991,Top industrial demand
10,2018,11,Guanajuato,020,León,11020,10899.0,157799.0,33612.519,108923.306,2270.654,1.000000,0.999109,0.987082,0.984410,0.986637,0.992138,0.995546,Top industrial demand
11,2018,26,Sonora,030,Hermosillo,26030,4103.0,58362.0,62325.936,163624.271,1069.498,0.995100,0.988864,0.995991,0.993764,0.976392,0.991938,0.995100,Top industrial demand
12,2018,15,México,033,Ecatepec de Morelos,15033,6689.0,66671.0,43515.828,122025.177,2494.782,0.998218,0.990646,0.990646,0.985746,0.987973,0.991292,0.994655,Top industrial demand
13,2018,05,Coahuila de Zaragoza,035,Torreón,05035,2046.0,70589.0,72451.993,201548.237,3023.038,0.979955,0.991537,0.997327,0.995100,0.990646,0.990713,0.994209,Top industrial demand
14,2018,08,Chihuahua,019,Chihuahua,08019,2816.0,107597.0,38964.910,102205.521,2053.679,0.988419,0.996437,0.989755,0.983519,0.985746,0.989109,0.993764,Top industrial demand
15,2018,21,Puebla,114,Puebla,21114,6849.0,73573.0,24499.268,107109.244,1999.195,0.998664,0.993318,0.981737,0.983964,0.985301,0.989087,0.993318,Top industrial demand
16,2018,02,Baja California,002,Mexicali,02002,2320.0,91953.0,46895.750,112075.509,1758.925,0.983519,0.995546,0.992428,0.984855,0.983073,0.988374,0.992873,Top industrial demand
17,2018,19,Nuevo León,006,Apodaca,19006,1328.0,123847.0,67665.886,227485.595,3127.568,0.962584,0.997773,0.996437,0.996437,0.991091,0.987706,0.992428,Top industrial demand
18,2018,11,Guanajuato,007,Celaya,11007,2089.0,49066.0,48367.577,140938.963,2132.214,0.980401,0.985746,0.992873,0.990200,0.986192,0.987127,0.991982,Top industrial demand
19,2018,11,Guanajuato,017,Irapuato,11017,1908.0,59650.0,46655.971,129129.759,4152.540,0.976392,0.989310,0.991982,0.987528,0.995546,0.987016,0.991537,Top industrial demand
20,2018,09,Ciudad de México,007,Iztapalapa,09007,7385.0,72978.0,19696.295,63890.154,1331.167,0.999109,0.992873,0.978619,0.976837,0.979065,0.986281,0.991091,Top industrial demand
21,2018,15,México,104,Tlalnepantla de Baz,15104,2380.0,58199.0,27410.555,98739.303,1469.627,0.985746,0.988419,0.983964,0.983073,0.981292,0.984855,0.990646,Top industrial demand
22,2018,09,Ciudad de México,002,Azcapotzalco,09002,1580.0,45951.0,51451.922,128884.783,1951.378,0.970379,0.983964,0.994209,0.987082,0.984855,0.983842,0.990200,Top industrial demand
23,2018,19,Nuevo León,026,Guadalupe,19026,2005.0,69909.0,29140.839,86462.362,1295.058,0.978842,0.991091,0.984410,0.980401,0.978174,0.982929,0.989755,Top industrial demand
24,2018,19,Nuevo León,046,San Nicolás de los Garza,19046,1130.0,53769.0,46574.091,162581.492,3316.959,0.955011,0.987528,0.991091,0.992873,0.992873,0.981893,0.989310,Top industrial demand
25,2018,15,México,057,Naucalpan de Juárez,15057,2327.0,48949.0,23055.275,76139.170,857.121,0.983964,0.985301,0.980401,0.979065,0.972829,0.981247,0.988864,Top industrial demand
26,2018,15,México,121,Cuautitlán Izcalli,15121,1563.0,49731.0,29875.306,93832.759,1665.938,0.969265,0.986192,0.985301,0.982183,0.982628,0.980579,0.988419,Top industrial demand
27,2018,14,Jalisco,098,San Pedro Tlaquepaque,14098,2556.0,41699.0,20622.306,69975.351,644.145,0.987082,0.982628,0.979065,0.977728,0.967483,0.980356,0.987973,Top industrial demand
28,2018,28,Tamaulipas,032,Reynosa,28032,1359.0,142652.0,31077.623,75526.286,890.009,0.963474,0.998664,0.986192,0.978174,0.974165,0.980200,0.987528,Top industrial demand
29,2018,11,Guanajuato,037,Silao de la Victoria,11037,805.0,64242.0,46599.390,278660.416,5507.372,0.926949,0.990200,0.991537,0.998664,0.997773,0.977171,0.987082,Top industrial demand

VALIDACIÓN RÁPIDA
====================================================================================================
Filas diagnosticadas: 4530
Missing industrial_demand_score: 0
Missing industrial_demand_percentile: 0
Años: [np.int64(2018), np.int64(2023)]

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics

In [ ]:
# ============================================================
# 06. DIAGNÓSTICO DEL B2B SUPPLY SCORE
# Nearshoring Project / Market Opportunity Analytics
#
# Este script funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Calcular y revisar el componente de oferta B2B observable,
# sin guardar todavía una nueva base completa de scoring.
#
# Lógica acordada:
# - No usar denue_b2b_support_establishments dentro del score
#   para evitar doble conteo con sus componentes.
#
# B2B supply score =
# 0.35 * P(logística)
# + 0.25 * P(servicios profesionales/técnicos)
# + 0.20 * P(apoyo a negocios)
# + 0.20 * P(diversidad SCIAN B2B)
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
#
# Outputs:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/
#   05_b2b_supply_score_diagnostic.csv
#   06_b2b_supply_score_summary.csv
#   07_b2b_supply_top_municipalities.csv
#   08_b2b_supply_score_weights.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np
import os


def get_drive_root():
    """
    Devuelve la ruta de MyDrive si ya está montado.
    Si no está montado, intenta montarlo.
    Si falla, intenta force_remount.
    """

    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    # 1. Si Drive ya está montado, usarlo
    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    # 2. Intentar montar en /content/drive
    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    # 3. Intentar force_remount
    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    # 4. Si nada funcionó
    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Solución práctica: en Colab ve a Runtime > Restart runtime, "
        "vuelve a ejecutar la celda y autoriza Drive otra vez."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

diagnostics_path = modeling_path / "scoring_diagnostics"
diagnostics_path.mkdir(parents=True, exist_ok=True)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

b2b_diagnostic_path = (
    diagnostics_path / "05_b2b_supply_score_diagnostic.csv"
)

b2b_summary_path = (
    diagnostics_path / "06_b2b_supply_score_summary.csv"
)

top_b2b_path = (
    diagnostics_path / "07_b2b_supply_top_municipalities.csv"
)

weights_path = (
    diagnostics_path / "08_b2b_supply_score_weights.csv"
)

print("\nProject path:")
print(project_path)

print("\nInput path:")
print(input_path)

print("\nDiagnostics path:")
print(diagnostics_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(
    df["year"],
    errors="coerce"
).astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Variables y pesos del B2B supply score
# ------------------------------------------------------------
# Nota metodológica:
# No usamos denue_b2b_support_establishments dentro del score
# para evitar doble conteo con sus componentes.
#
# Pesos:
# logística: 0.35
# servicios profesionales/técnicos: 0.25
# apoyo a negocios: 0.20
# diversidad SCIAN B2B: 0.20

b2b_supply_features = [
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes"
]

b2b_supply_weights = {
    "denue_logistics_storage_establishments": 0.35,
    "denue_professional_technical_establishments": 0.25,
    "denue_business_support_establishments": 0.20,
    "denue_b2b_support_scian_classes": 0.20
}

missing_features = [
    col for col in b2b_supply_features
    if col not in df.columns
]

if missing_features:
    raise ValueError(f"Faltan variables para oferta B2B: {missing_features}")

if not np.isclose(sum(b2b_supply_weights.values()), 1.0):
    raise ValueError("Los pesos del B2B supply score no suman 1.")


# ------------------------------------------------------------
# 4. Validar y convertir variables
# ------------------------------------------------------------

for col in b2b_supply_features:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_b2b = df[b2b_supply_features].isna().sum()

print("\nMissing en variables de oferta B2B:")
print(missing_b2b)

if missing_b2b.sum() > 0:
    raise ValueError(
        "Hay missing en variables B2B. "
        "Revisa que estés usando 08_modeling_base_complete_cases.csv."
    )


# ------------------------------------------------------------
# 5. Normalización por percentiles dentro de cada año
# ------------------------------------------------------------

for col in b2b_supply_features:
    percentile_col = f"{col}_b2b_supply_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )


# ------------------------------------------------------------
# 6. Construir b2b_supply_score
# ------------------------------------------------------------

df["b2b_supply_score"] = 0.0

for col, weight in b2b_supply_weights.items():
    percentile_col = f"{col}_b2b_supply_percentile"
    df["b2b_supply_score"] += df[percentile_col] * weight

df["b2b_supply_percentile"] = (
    df
    .groupby("year")["b2b_supply_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 7. Grupo interpretable
# ------------------------------------------------------------

def classify_b2b_supply_group(p):
    if pd.isna(p):
        return "Sin información"
    elif p >= 0.90:
        return "Top B2B supply"
    elif p >= 0.75:
        return "High B2B supply"
    elif p >= 0.50:
        return "Medium B2B supply"
    else:
        return "Low B2B supply"


df["b2b_supply_group"] = (
    df["b2b_supply_percentile"]
    .apply(classify_b2b_supply_group)
)


# ------------------------------------------------------------
# 8. Tabla diagnóstica compacta
# ------------------------------------------------------------

diagnostic_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",

    # Variable descriptiva, NO usada en el score
    "denue_b2b_support_establishments",

    # Variables usadas en el score
    *b2b_supply_features,

    # Percentiles
    *[f"{col}_b2b_supply_percentile" for col in b2b_supply_features],

    # Score
    "b2b_supply_score",
    "b2b_supply_percentile",
    "b2b_supply_group"
]

diagnostic_cols = [
    col for col in diagnostic_cols
    if col in df.columns
]

b2b_diagnostic = df[diagnostic_cols].copy()


# ------------------------------------------------------------
# 9. Resumen por año y grupo
# ------------------------------------------------------------

b2b_summary = (
    b2b_diagnostic
    .groupby(["year", "b2b_supply_group"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_b2b_supply_score=("b2b_supply_score", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_b2b_total_descriptive=("denue_b2b_support_establishments", "mean"),
        avg_logistics_storage=("denue_logistics_storage_establishments", "mean"),
        avg_professional_technical=("denue_professional_technical_establishments", "mean"),
        avg_business_support=("denue_business_support_establishments", "mean"),
        avg_b2b_scian_classes=("denue_b2b_support_scian_classes", "mean")
    )
    .reset_index()
)

b2b_summary["share_municipality_years"] = (
    b2b_summary["n_municipality_years"]
    / b2b_summary.groupby("year")["n_municipality_years"].transform("sum")
)

group_order = {
    "Top B2B supply": 1,
    "High B2B supply": 2,
    "Medium B2B supply": 3,
    "Low B2B supply": 4,
    "Sin información": 5
}

b2b_summary["group_order"] = (
    b2b_summary["b2b_supply_group"]
    .map(group_order)
)

b2b_summary = (
    b2b_summary
    .sort_values(["year", "group_order"])
    .drop(columns=["group_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Top municipios por año
# ------------------------------------------------------------

top_b2b = (
    b2b_diagnostic
    .sort_values(
        ["year", "b2b_supply_score"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. Tabla de pesos
# ------------------------------------------------------------

weights_table = pd.DataFrame({
    "feature": list(b2b_supply_weights.keys()),
    "weight": list(b2b_supply_weights.values()),
    "score_block": "b2b_supply_score",
    "normalization": "Percentile rank within year",
    "interpretation": [
        "Oferta logística y almacenamiento; mayor peso por relevancia en nearshoring",
        "Oferta profesional, técnica y especializada",
        "Oferta operativa y de apoyo empresarial",
        "Diversidad de clases SCIAN B2B presentes"
    ]
})


# ------------------------------------------------------------
# 12. Guardar diagnósticos
# ------------------------------------------------------------

b2b_diagnostic.to_csv(
    b2b_diagnostic_path,
    index=False,
    encoding="utf-8-sig"
)

b2b_summary.to_csv(
    b2b_summary_path,
    index=False,
    encoding="utf-8-sig"
)

top_b2b.to_csv(
    top_b2b_path,
    index=False,
    encoding="utf-8-sig"
)

weights_table.to_csv(
    weights_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 13. Mostrar resultados
# ------------------------------------------------------------

print("\nPESOS DEL B2B SUPPLY SCORE")
print("=" * 100)
display(weights_table)

print("\nRESUMEN DEL B2B SUPPLY SCORE")
print("=" * 100)
display(b2b_summary)

print("\nTOP MUNICIPIOS POR OFERTA B2B")
print("=" * 100)
display(top_b2b.head(30))

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas diagnosticadas:", len(b2b_diagnostic))
print("Missing b2b_supply_score:", b2b_diagnostic["b2b_supply_score"].isna().sum())
print("Missing b2b_supply_percentile:", b2b_diagnostic["b2b_supply_percentile"].isna().sum())
print("Años:", sorted(b2b_diagnostic["year"].dropna().unique()))

print("\nArchivos guardados en:")
print(diagnostics_path)

print("\nArchivos generados:")
print(b2b_diagnostic_path)
print(b2b_summary_path)
print(top_b2b_path)
print(weights_path)

Google Drive ya está disponible en: /content/drive/MyDrive

Project path:
/content/drive/MyDrive/Nearshoring_Project

Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Diagnostics path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics

Base cargada:
Filas: 4,530
Columnas: 54

Missing en variables de oferta B2B:
denue_logistics_storage_establishments         0
denue_professional_technical_establishments    0
denue_business_support_establishments          0
denue_b2b_support_scian_classes                0
dtype: int64

PESOS DEL B2B SUPPLY SCORE
====================================================================================================

,feature,weight,score_block,normalization,interpretation
0,denue_logistics_storage_establishments,0.35,b2b_supply_score,Percentile rank within year,Oferta logística y almacenamiento; mayor peso ...
1,denue_professional_technical_establishments,0.25,b2b_supply_score,Percentile rank within year,"Oferta profesional, técnica y especializada"
2,denue_business_support_establishments,0.20,b2b_supply_score,Percentile rank within year,Oferta operativa y de apoyo empresarial
3,denue_b2b_support_scian_classes,0.20,b2b_supply_score,Percentile rank within year,Diversidad de clases SCIAN B2B presentes

RESUMEN DEL B2B SUPPLY SCORE
====================================================================================================

,year,b2b_supply_group,n_municipality_years,n_municipalities,avg_b2b_supply_score,avg_b2b_supply_percentile,avg_b2b_total_descriptive,avg_logistics_storage,avg_professional_technical,avg_business_support,avg_b2b_scian_classes,share_municipality_years
0,2018,Top B2B supply,225,225,0.946121,0.950111,872.311111,132.333333,391.475556,348.502222,58.191111,0.100223
1,2018,High B2B supply,337,337,0.813972,0.824944,92.302671,15.350148,31.314540,45.637982,21.881306,0.150111
2,2018,Medium B2B supply,561,561,0.608399,0.624944,26.572193,4.611408,7.108734,14.852050,9.575758,0.249889
3,2018,Low B2B supply,1122,1122,0.262480,0.250111,5.160428,0.687166,0.834225,3.639037,2.559715,0.499777
4,2023,Top B2B supply,229,229,0.946545,0.950109,789.187773,139.393013,392.633188,257.161572,61.449782,0.100219
5,2023,High B2B supply,343,343,0.813241,0.824945,83.772595,15.381924,35.396501,32.994169,23.061224,0.150109
6,2023,Medium B2B supply,571,571,0.607477,0.624945,24.173380,4.231173,8.500876,11.441331,10.099825,0.249891
7,2023,Low B2B supply,1142,1142,0.263074,0.250109,4.551664,0.614711,1.074431,2.862522,2.500000,0.499781

TOP MUNICIPIOS POR OFERTA B2B
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,denue_logistics_storage_establishments_b2b_supply_percentile,denue_professional_technical_establishments_b2b_supply_percentile,denue_business_support_establishments_b2b_supply_percentile,denue_b2b_support_scian_classes_b2b_supply_percentile,b2b_supply_score,b2b_supply_percentile,b2b_supply_group
0,2018,14,Jalisco,039,Guadalajara,14039,7008.0,817.0,3751.0,2440.0,110.0,0.999555,0.999555,1.000000,1.000000,0.999733,1.000000,Top B2B supply
1,2018,02,Baja California,004,Tijuana,02004,4275.0,782.0,1905.0,1588.0,105.0,0.999109,0.997327,0.997773,0.998886,0.998352,0.999555,Top B2B supply
2,2018,21,Puebla,114,Puebla,21114,5014.0,611.0,2303.0,2100.0,107.0,0.997327,0.997773,0.999555,0.999555,0.998330,0.999109,Top B2B supply
3,2018,19,Nuevo León,039,Monterrey,19039,4737.0,627.0,2543.0,1567.0,102.0,0.998218,0.998664,0.997327,0.997327,0.997973,0.998664,Top B2B supply
4,2018,09,Ciudad de México,015,Cuauhtémoc,09015,6122.0,459.0,4022.0,1641.0,99.0,0.995100,1.000000,0.998218,0.995546,0.997038,0.998218,Top B2B supply
5,2018,11,Guanajuato,020,León,11020,4220.0,539.0,1837.0,1844.0,98.0,0.995991,0.996882,0.999109,0.994432,0.996526,0.997773,Top B2B supply
6,2018,22,Querétaro,014,Querétaro,22014,3543.0,427.0,1809.0,1307.0,103.0,0.994655,0.996437,0.996437,0.997773,0.996080,0.997327,Top B2B supply
7,2018,24,San Luis Potosí,028,San Luis Potosí,24028,3054.0,486.0,1448.0,1120.0,99.0,0.995546,0.995546,0.994209,0.995546,0.995278,0.996882,Top B2B supply
8,2018,09,Ciudad de México,016,Miguel Hidalgo,09016,3945.0,353.0,2510.0,1082.0,104.0,0.992428,0.998218,0.993318,0.998218,0.995212,0.996437,Top B2B supply
9,2018,31,Yucatán,050,Mérida,31050,3121.0,412.0,1575.0,1134.0,100.0,0.994209,0.995991,0.994655,0.996437,0.995189,0.995991,Top B2B supply
10,2018,01,Aguascalientes,001,Aguascalientes,01001,2938.0,352.0,1395.0,1191.0,99.0,0.991982,0.995100,0.995100,0.995546,0.994098,0.995546,Top B2B supply
11,2018,14,Jalisco,120,Zapopan,14120,2728.0,334.0,1177.0,1217.0,101.0,0.991091,0.993764,0.995991,0.996882,0.993898,0.995100,Top B2B supply
12,2018,09,Ciudad de México,014,Benito Juárez,09014,4296.0,299.0,2983.0,1014.0,105.0,0.988196,0.999109,0.991537,0.998886,0.993731,0.994655,Top B2B supply
13,2018,08,Chihuahua,019,Chihuahua,08019,2153.0,377.0,1094.0,682.0,98.0,0.993318,0.993318,0.987528,0.994432,0.992383,0.994209,Top B2B supply
14,2018,08,Chihuahua,037,Juárez,08037,2135.0,553.0,799.0,783.0,93.0,0.996437,0.987528,0.990646,0.991982,0.992160,0.993764,Top B2B supply
15,2018,26,Sonora,030,Hermosillo,26030,2256.0,346.0,1283.0,627.0,97.0,0.991537,0.994655,0.984855,0.993764,0.991425,0.993318,Top B2B supply
16,2018,09,Ciudad de México,007,Iztapalapa,09007,2974.0,299.0,978.0,1697.0,88.0,0.988196,0.991537,0.998664,0.989310,0.991347,0.992873,Top B2B supply
17,2018,15,México,106,Toluca,15106,2404.0,311.0,885.0,1208.0,92.0,0.988864,0.989310,0.995546,0.991314,0.990802,0.992428,Top B2B supply
18,2018,09,Ciudad de México,005,Gustavo A. Madero,09005,2293.0,409.0,827.0,1057.0,85.0,0.993764,0.988419,0.991982,0.986414,0.990601,0.991982,Top B2B supply
19,2018,30,Veracruz de Ignacio de la Llave,193,Veracruz,30193,2005.0,572.0,747.0,686.0,86.0,0.996882,0.985746,0.987973,0.987751,0.990490,0.991537,Top B2B supply
20,2018,02,Baja California,002,Mexicali,02002,1904.0,375.0,905.0,624.0,95.0,0.992873,0.990200,0.984410,0.992428,0.990423,0.991091,Top B2B supply
21,2018,25,Sinaloa,006,Culiacán,25006,1943.0,317.0,914.0,712.0,90.0,0.989532,0.990646,0.989310,0.990646,0.989989,0.990646,Top B2B supply
22,2018,23,Quintana Roo,005,Benito Juárez,23005,2197.0,264.0,868.0,1065.0,96.0,0.986637,0.988864,0.992428,0.993096,0.989644,0.990200,Top B2B supply
23,2018,16,Michoacán de Ocampo,053,Morelia,16053,2612.0,252.0,1280.0,1080.0,88.0,0.984410,0.994209,0.992873,0.989310,0.989532,0.989755,Top B2B supply
24,2018,05,Coahuila de Zaragoza,035,Torreón,05035,1953.0,280.0,1012.0,661.0,92.0,0.987082,0.992428,0.986637,0.991314,0.989176,0.989310,Top B2B supply
25,2018,07,Chiapas,101,Tuxtla Gutiérrez,07101,2242.0,320.0,999.0,923.0,78.0,0.990200,0.991982,0.991091,0.976392,0.988062,0.988864,Top B2B supply
26,2018,09,Ciudad de México,017,Venustiano Carranza,09017,1624.0,736.0,388.0,500.0,82.0,0.998664,0.973719,0.979955,0.983073,0.985568,0.988419,Top B2B supply
27,2018,20,Oaxaca,067,Oaxaca de Juárez,20067,1983.0,222.0,1062.0,699.0,80.0,0.980846,0.992873,0.988641,0.979955,0.985234,0.987973,Top B2B supply
28,2018,05,Coahuila de Zaragoza,030,Saltillo,05030,1608.0,240.0,712.0,656.0,86.0,0.983742,0.983964,0.986192,0.987751,0.985089,0.987528,Top B2B supply
29,2018,15,México,104,Tlalnepantla de Baz,15104,1690.0,231.0,739.0,720.0,83.0,0.982183,0.984855,0.989755,0.984855,0.984900,0.987082,Top B2B supply

VALIDACIÓN RÁPIDA
====================================================================================================
Filas diagnosticadas: 4530
Missing b2b_supply_score: 0
Missing b2b_supply_percentile: 0
Años: [np.int64(2018), np.int64(2023)]

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics

Archivos generados:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/05_b2b_supply_score_diagnostic.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/06_b2b_supply_score_summary.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/07_b2b_supply_top_municipalities.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/08_b2b_supply_score_weights.csv

In [ ]:
# ============================================================
# 06B. VISTAS INTERESANTES: DEMANDA INDUSTRIAL × OFERTA B2B
# Nearshoring Project / Market Opportunity Analytics
#
# Este script funciona aunque hayas cerrado sesión.
#
# Inputs:
# scoring_diagnostics/01_industrial_demand_score_diagnostic.csv
# scoring_diagnostics/05_b2b_supply_score_diagnostic.csv
#
# Outputs:
# scoring_diagnostics/09_top_b2b_supply_municipalities.csv
# scoring_diagnostics/10_bottom_b2b_supply_municipalities.csv
# scoring_diagnostics/11_high_demand_low_b2b_supply_candidates.csv
# scoring_diagnostics/12_high_demand_high_b2b_supply_hubs.csv
# scoring_diagnostics/13_demand_supply_cross_tab.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

diagnostics_path = (
    project_path / "data" / "processed" / "modeling_base" / "scoring_diagnostics"
)

demand_path = diagnostics_path / "01_industrial_demand_score_diagnostic.csv"
b2b_path = diagnostics_path / "05_b2b_supply_score_diagnostic.csv"

print("Demand input:")
print(demand_path)

print("\nB2B input:")
print(b2b_path)

if not demand_path.exists():
    raise FileNotFoundError(f"No encontré el diagnóstico de demanda: {demand_path}")

if not b2b_path.exists():
    raise FileNotFoundError(f"No encontré el diagnóstico de oferta B2B: {b2b_path}")


# ------------------------------------------------------------
# 2. Cargar diagnósticos
# ------------------------------------------------------------

demand = pd.read_csv(
    demand_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

b2b = pd.read_csv(
    b2b_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

for df in [demand, b2b]:
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
    df["entidad_id"] = df["entidad_id"].astype(str).str.strip().str.zfill(2)
    df["municipio_id"] = df["municipio_id"].astype(str).str.strip().str.zfill(3)
    df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nDemanda:")
print(demand.shape)

print("\nOferta B2B:")
print(b2b.shape)


# ------------------------------------------------------------
# 3. Seleccionar columnas y cruzar
# ------------------------------------------------------------

demand_keep = [
    "year",
    "geo_key",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "industrial_demand_score",
    "industrial_demand_percentile",
    "industrial_demand_group",
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

b2b_keep = [
    "year",
    "geo_key",
    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",
    "b2b_supply_score",
    "b2b_supply_percentile",
    "b2b_supply_group"
]

demand_keep = [col for col in demand_keep if col in demand.columns]
b2b_keep = [col for col in b2b_keep if col in b2b.columns]

combined = demand[demand_keep].merge(
    b2b[b2b_keep],
    on=["year", "geo_key"],
    how="inner"
)

print("\nBase combinada:")
print(combined.shape)


# ------------------------------------------------------------
# 4. Crear etiquetas cruzadas
# ------------------------------------------------------------

def classify_cross(row):
    demand_p = row["industrial_demand_percentile"]
    b2b_p = row["b2b_supply_percentile"]

    if demand_p >= 0.75 and b2b_p < 0.50:
        return "High demand + low B2B supply"
    elif demand_p >= 0.75 and b2b_p >= 0.75:
        return "High demand + high B2B supply"
    elif demand_p < 0.50 and b2b_p >= 0.75:
        return "Low demand + high B2B supply"
    elif demand_p < 0.50 and b2b_p < 0.50:
        return "Low demand + low B2B supply"
    else:
        return "Middle cases"


combined["demand_supply_profile"] = combined.apply(classify_cross, axis=1)


# ------------------------------------------------------------
# 5. Tablas interesantes
# ------------------------------------------------------------

top_b2b_supply = (
    combined
    .sort_values(["year", "b2b_supply_score"], ascending=[True, False])
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

bottom_b2b_supply = (
    combined
    .sort_values(["year", "b2b_supply_score"], ascending=[True, True])
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

high_demand_low_b2b = (
    combined[
        (combined["industrial_demand_percentile"] >= 0.75) &
        (combined["b2b_supply_percentile"] < 0.50)
    ]
    .sort_values(
        ["year", "industrial_demand_percentile", "b2b_supply_percentile"],
        ascending=[True, False, True]
    )
    .reset_index(drop=True)
)

high_demand_high_b2b = (
    combined[
        (combined["industrial_demand_percentile"] >= 0.75) &
        (combined["b2b_supply_percentile"] >= 0.75)
    ]
    .sort_values(
        ["year", "industrial_demand_percentile", "b2b_supply_percentile"],
        ascending=[True, False, False]
    )
    .reset_index(drop=True)
)

cross_tab = (
    combined
    .groupby(["year", "demand_supply_profile"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_industrial_demand_score=("industrial_demand_score", "mean"),
        avg_b2b_supply_score=("b2b_supply_score", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_logistics=("denue_logistics_storage_establishments", "mean")
    )
    .reset_index()
)

cross_tab["share_municipality_years"] = (
    cross_tab["n_municipality_years"] /
    cross_tab.groupby("year")["n_municipality_years"].transform("sum")
)


# ------------------------------------------------------------
# 6. Guardar outputs
# ------------------------------------------------------------

top_b2b_supply.to_csv(
    diagnostics_path / "09_top_b2b_supply_municipalities.csv",
    index=False,
    encoding="utf-8-sig"
)

bottom_b2b_supply.to_csv(
    diagnostics_path / "10_bottom_b2b_supply_municipalities.csv",
    index=False,
    encoding="utf-8-sig"
)

high_demand_low_b2b.to_csv(
    diagnostics_path / "11_high_demand_low_b2b_supply_candidates.csv",
    index=False,
    encoding="utf-8-sig"
)

high_demand_high_b2b.to_csv(
    diagnostics_path / "12_high_demand_high_b2b_supply_hubs.csv",
    index=False,
    encoding="utf-8-sig"
)

cross_tab.to_csv(
    diagnostics_path / "13_demand_supply_cross_tab.csv",
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 7. Mostrar resultados
# ------------------------------------------------------------

print("\nTOP B2B SUPPLY")
display(top_b2b_supply.head(20))

print("\nBOTTOM B2B SUPPLY")
display(bottom_b2b_supply.head(20))

print("\nHIGH DEMAND + LOW B2B SUPPLY")
display(high_demand_low_b2b.head(30))

print("\nHIGH DEMAND + HIGH B2B SUPPLY")
display(high_demand_high_b2b.head(30))

print("\nCROSS TAB")
display(cross_tab)

print("\nArchivos guardados en:")
print(diagnostics_path)

Google Drive ya está disponible en: /content/drive/MyDrive
Demand input:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/01_industrial_demand_score_diagnostic.csv

B2B input:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/05_b2b_supply_score_diagnostic.csv

Demanda:
(4530, 19)

Oferta B2B:
(4530, 18)

Base combinada:
(4530, 22)

TOP B2B SUPPLY

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,total_manufacturing_investment,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile
0,2018,14039,14,Jalisco,039,Guadalajara,0.995345,0.998664,Top industrial demand,8007.0,...,2409.978,7008.0,817.0,3751.0,2440.0,110.0,0.999733,1.000000,Top B2B supply,High demand + high B2B supply
1,2018,02004,02,Baja California,004,Tijuana,0.996815,0.999109,Top industrial demand,3670.0,...,5618.985,4275.0,782.0,1905.0,1588.0,105.0,0.998352,0.999555,Top B2B supply,High demand + high B2B supply
2,2018,21114,21,Puebla,114,Puebla,0.989087,0.993318,Top industrial demand,6849.0,...,1999.195,5014.0,611.0,2303.0,2100.0,107.0,0.998330,0.999109,Top B2B supply,High demand + high B2B supply
3,2018,19039,19,Nuevo León,039,Monterrey,0.993964,0.996882,Top industrial demand,4729.0,...,3248.158,4737.0,627.0,2543.0,1567.0,102.0,0.997973,0.998664,Top B2B supply,High demand + high B2B supply
4,2018,09015,09,Ciudad de México,015,Cuauhtémoc,0.976570,0.985746,Top industrial demand,3979.0,...,288.735,6122.0,459.0,4022.0,1641.0,99.0,0.997038,0.998218,Top B2B supply,High demand + high B2B supply
5,2018,11020,11,Guanajuato,020,León,0.992138,0.995546,Top industrial demand,10899.0,...,2270.654,4220.0,539.0,1837.0,1844.0,98.0,0.996526,0.997773,Top B2B supply,High demand + high B2B supply
6,2018,22014,22,Querétaro,014,Querétaro,0.995122,0.998218,Top industrial demand,3363.0,...,12126.712,3543.0,427.0,1809.0,1307.0,103.0,0.996080,0.997327,Top B2B supply,High demand + high B2B supply
7,2018,24028,24,San Luis Potosí,028,San Luis Potosí,0.997127,0.999555,Top industrial demand,3824.0,...,8373.471,3054.0,486.0,1448.0,1120.0,99.0,0.995278,0.996882,Top B2B supply,High demand + high B2B supply
8,2018,09016,09,Ciudad de México,016,Miguel Hidalgo,0.972294,0.979955,Top industrial demand,1233.0,...,1207.735,3945.0,353.0,2510.0,1082.0,104.0,0.995212,0.996437,Top B2B supply,High demand + high B2B supply
9,2018,31050,31,Yucatán,050,Mérida,0.976548,0.985301,Top industrial demand,3850.0,...,348.294,3121.0,412.0,1575.0,1134.0,100.0,0.995189,0.995991,Top B2B supply,High demand + high B2B supply
10,2018,01001,01,Aguascalientes,001,Aguascalientes,0.995056,0.997773,Top industrial demand,3896.0,...,3845.502,2938.0,352.0,1395.0,1191.0,99.0,0.994098,0.995546,Top B2B supply,High demand + high B2B supply
11,2018,14120,14,Jalisco,120,Zapopan,0.994076,0.997327,Top industrial demand,4395.0,...,2894.772,2728.0,334.0,1177.0,1217.0,101.0,0.993898,0.995100,Top B2B supply,High demand + high B2B supply
12,2018,09014,09,Ciudad de México,014,Benito Juárez,0.961938,0.974610,Top industrial demand,1271.0,...,361.465,4296.0,299.0,2983.0,1014.0,105.0,0.993731,0.994655,Top B2B supply,High demand + high B2B supply
13,2018,08019,08,Chihuahua,019,Chihuahua,0.989109,0.993764,Top industrial demand,2816.0,...,2053.679,2153.0,377.0,1094.0,682.0,98.0,0.992383,0.994209,Top B2B supply,High demand + high B2B supply
14,2018,08037,08,Chihuahua,037,Juárez,0.993853,0.996437,Top industrial demand,2375.0,...,3176.689,2135.0,553.0,799.0,783.0,93.0,0.992160,0.993764,Top B2B supply,High demand + high B2B supply
15,2018,26030,26,Sonora,030,Hermosillo,0.991938,0.995100,Top industrial demand,4103.0,...,1069.498,2256.0,346.0,1283.0,627.0,97.0,0.991425,0.993318,Top B2B supply,High demand + high B2B supply
16,2018,09007,09,Ciudad de México,007,Iztapalapa,0.986281,0.991091,Top industrial demand,7385.0,...,1331.167,2974.0,299.0,978.0,1697.0,88.0,0.991347,0.992873,Top B2B supply,High demand + high B2B supply
17,2018,15106,15,México,106,Toluca,0.997305,1.000000,Top industrial demand,4351.0,...,3917.262,2404.0,311.0,885.0,1208.0,92.0,0.990802,0.992428,Top B2B supply,High demand + high B2B supply
18,2018,09005,09,Ciudad de México,005,Gustavo A. Madero,0.974187,0.981737,Top industrial demand,3749.0,...,428.880,2293.0,409.0,827.0,1057.0,85.0,0.990601,0.991982,Top B2B supply,High demand + high B2B supply
19,2018,30193,30,Veracruz de Ignacio de la Llave,193,Veracruz,0.971570,0.979510,Top industrial demand,1541.0,...,1349.989,2005.0,572.0,747.0,686.0,86.0,0.990490,0.991537,Top B2B supply,High demand + high B2B supply

BOTTOM B2B SUPPLY

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,total_manufacturing_investment,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile
0,2018,19016,19,Nuevo León,016,Doctor González,0.558018,0.559911,Medium industrial demand,8.0,...,54.833,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
1,2018,17035,17,Morelos,035,Xoxocotla,0.560624,0.563920,Medium industrial demand,208.0,...,-0.014,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
2,2018,31016,31,Yucatán,016,Chacsinkín,0.576325,0.584855,Medium industrial demand,448.0,...,-0.005,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
3,2018,17034,17,Morelos,034,Coatetelco,0.475234,0.465479,Low industrial demand,74.0,...,-0.009,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
4,2018,20497,20,Oaxaca,497,Santiago Yaitepec,0.569644,0.575501,Medium industrial demand,278.0,...,0.071,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
5,2018,29003,29,Tlaxcala,003,Atlangatepec,0.491726,0.485078,Low industrial demand,7.0,...,10.594,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
6,2018,20328,20,Oaxaca,328,San Pedro Taviche,0.555223,0.556347,Medium industrial demand,296.0,...,0.001,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
7,2018,20313,20,Oaxaca,313,San Pedro Jocotipac,0.520991,0.522049,Medium industrial demand,195.0,...,0.002,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
8,2018,20533,20,Oaxaca,533,Santo Tomás Tamazulapan,0.425490,0.418263,Low industrial demand,15.0,...,0.571,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
9,2018,20564,20,Oaxaca,564,Yutanduchi de Guerrero,0.515212,0.513586,Medium industrial demand,264.0,...,0.004,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
10,2018,21193,21,Puebla,193,Tzicatlacoyan,0.518920,0.519822,Medium industrial demand,207.0,...,0.269,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases
11,2018,20416,20,Oaxaca,416,Santa María Ixcatlán,0.464978,0.456570,Low industrial demand,155.0,...,-0.004,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
12,2018,20080,20,Oaxaca,080,San Agustín Amatengo,0.408396,0.393987,Low industrial demand,49.0,...,0.105,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
13,2018,08051,08,Chihuahua,051,Ocampo,0.317160,0.301559,Low industrial demand,12.0,...,0.031,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
14,2018,21095,21,Puebla,095,La Magdalena Tlatlauquitepec,0.308096,0.292205,Low industrial demand,23.0,...,0.002,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
15,2018,31086,31,Yucatán,086,Tepakán,0.366893,0.351448,Low industrial demand,82.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
16,2018,20311,20,Oaxaca,311,San Pedro Jaltepetongo,0.416336,0.406236,Low industrial demand,137.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
17,2018,20113,20,Oaxaca,113,San Baltazar Loxicha,0.388875,0.371938,Low industrial demand,71.0,...,0.553,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
18,2018,20146,20,Oaxaca,146,San Francisco Logueche,0.355089,0.337639,Low industrial demand,120.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply
19,2018,20095,20,Oaxaca,095,San Andrés Paxtlán,0.274376,0.259688,Low industrial demand,34.0,...,0.006,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply

HIGH DEMAND + LOW B2B SUPPLY

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,total_manufacturing_investment,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile
0,2018,21104,21,Puebla,104,Nopalucan,0.865913,0.894432,High industrial demand,168.0,...,118.116,20.0,3.0,0.0,17.0,5.0,0.463051,0.478396,Low B2B supply,High demand + low B2B supply
1,2018,12074,12,Guerrero,074,Zitlala,0.828441,0.862806,High industrial demand,1972.0,...,2.375,12.0,0.0,3.0,9.0,3.0,0.346102,0.365256,Low B2B supply,High demand + low B2B supply
2,2018,29019,29,Tlaxcala,019,Tepetitla de Lardizábal,0.828163,0.862361,High industrial demand,180.0,...,44.483,38.0,0.0,6.0,32.0,7.0,0.475022,0.488196,Low B2B supply,High demand + low B2B supply
3,2018,31080,31,Yucatán,080,Tekit,0.827439,0.861470,High industrial demand,1052.0,...,1.976,7.0,0.0,2.0,5.0,4.0,0.317394,0.328508,Low B2B supply,High demand + low B2B supply
4,2018,29059,29,Tlaxcala,059,Santa Cruz Quilehtla,0.820067,0.858352,High industrial demand,165.0,...,1.694,12.0,1.0,2.0,9.0,4.0,0.421849,0.438753,Low B2B supply,High demand + low B2B supply
5,2018,21149,21,Puebla,149,Santiago Miahuatlán,0.815056,0.852116,High industrial demand,220.0,...,24.887,17.0,1.0,2.0,14.0,6.0,0.464655,0.480178,Low B2B supply,High demand + low B2B supply
6,2018,17033,17,Morelos,033,Temoac,0.799577,0.836080,High industrial demand,690.0,...,0.841,27.0,1.0,0.0,26.0,3.0,0.378831,0.397773,Low B2B supply,High demand + low B2B supply
7,2018,15072,15,México,072,Rayón,0.794254,0.830290,High industrial demand,171.0,...,21.259,22.0,1.0,2.0,19.0,5.0,0.466971,0.482851,Low B2B supply,High demand + low B2B supply
8,2018,21124,21,Puebla,124,San Gabriel Chilac,0.778029,0.810245,High industrial demand,600.0,...,1.337,10.0,0.0,1.0,9.0,5.0,0.335412,0.350111,Low B2B supply,High demand + low B2B supply
9,2018,31085,31,Yucatán,085,Temozón,0.776782,0.808909,High industrial demand,1044.0,...,7.544,6.0,0.0,1.0,5.0,2.0,0.260401,0.260134,Low B2B supply,High demand + low B2B supply
10,2018,12019,12,Guerrero,019,Copalillo,0.770512,0.802673,High industrial demand,1063.0,...,0.187,10.0,0.0,1.0,9.0,2.0,0.288463,0.289978,Low B2B supply,High demand + low B2B supply
11,2018,15056,15,México,056,Morelos,0.766604,0.799109,High industrial demand,203.0,...,1.887,22.0,0.0,1.0,21.0,2.0,0.324989,0.337194,Low B2B supply,High demand + low B2B supply
12,2018,29037,29,Tlaxcala,037,Ziltlaltépec de Trinidad Sánchez Santos,0.764220,0.795991,High industrial demand,57.0,...,91.488,7.0,0.0,1.0,6.0,3.0,0.287929,0.289532,Low B2B supply,High demand + low B2B supply
13,2018,31053,31,Yucatán,053,Muna,0.761180,0.791537,High industrial demand,282.0,...,15.282,13.0,1.0,3.0,9.0,6.0,0.460401,0.476615,Low B2B supply,High demand + low B2B supply
14,2018,31002,31,Yucatán,002,Acanceh,0.760390,0.791091,High industrial demand,90.0,...,25.402,7.0,1.0,0.0,6.0,2.0,0.295267,0.297105,Low B2B supply,High demand + low B2B supply
15,2018,30052,30,Veracruz de Ignacio de la Llave,052,Cuichapa,0.757572,0.787528,High industrial demand,51.0,...,172.319,7.0,2.0,2.0,3.0,4.0,0.414688,0.432517,Low B2B supply,High demand + low B2B supply
16,2018,14109,14,Jalisco,109,Unión de San Antonio,0.757439,0.787082,High industrial demand,64.0,...,13.989,13.0,0.0,10.0,3.0,7.0,0.392840,0.408909,Low B2B supply,High demand + low B2B supply
17,2018,19034,19,Nuevo León,034,Marín,0.743118,0.771938,High industrial demand,27.0,...,323.172,6.0,3.0,1.0,2.0,5.0,0.416514,0.435635,Low B2B supply,High demand + low B2B supply
18,2018,20475,20,Oaxaca,475,Santiago Matatlán,0.735924,0.763920,High industrial demand,230.0,...,4.605,13.0,1.0,3.0,9.0,4.0,0.437773,0.449889,Low B2B supply,High demand + low B2B supply
19,2018,20045,20,Oaxaca,045,Magdalena Apasco,0.734844,0.762138,High industrial demand,82.0,...,33.451,7.0,0.0,3.0,4.0,5.0,0.335367,0.349666,Low B2B supply,High demand + low B2B supply
20,2018,01009,01,Aguascalientes,009,Tepezalá,0.732739,0.760356,High industrial demand,40.0,...,35.064,11.0,0.0,2.0,9.0,4.0,0.345457,0.362584,Low B2B supply,High demand + low B2B supply
21,2018,31004,31,Yucatán,004,Baca,0.730902,0.758129,High industrial demand,38.0,...,46.053,9.0,1.0,2.0,6.0,3.0,0.386927,0.404009,Low B2B supply,High demand + low B2B supply
22,2018,15006,15,México,006,Almoloya del Río,0.723898,0.751002,High industrial demand,575.0,...,0.022,25.0,0.0,6.0,19.0,5.0,0.437739,0.449443,Low B2B supply,High demand + low B2B supply
23,2023,24059,24,San Luis Potosí,059,Villa de Pozos,0.936258,0.957987,Top industrial demand,460.0,...,922.764,0.0,0.0,0.0,0.0,0.0,0.101127,0.028665,Low B2B supply,High demand + low B2B supply
24,2023,21104,21,Puebla,104,Nopalucan,0.859781,0.899781,High industrial demand,284.0,...,194.415,17.0,1.0,2.0,14.0,6.0,0.476871,0.495842,Low B2B supply,High demand + low B2B supply
25,2023,31080,31,Yucatán,080,Tekit,0.843972,0.881400,High industrial demand,1156.0,...,10.610,7.0,1.0,2.0,4.0,5.0,0.407287,0.426477,Low B2B supply,High demand + low B2B supply
26,2023,16025,16,Michoacán de Ocampo,025,Chilchota,0.838140,0.876149,High industrial demand,2114.0,...,0.471,30.0,0.0,12.0,18.0,6.0,0.477713,0.496280,Low B2B supply,High demand + low B2B supply
27,2023,29059,29,Tlaxcala,059,Santa Cruz Quilehtla,0.828556,0.867396,High industrial demand,224.0,...,193.382,8.0,1.0,1.0,6.0,3.0,0.377812,0.396061,Low B2B supply,High demand + low B2B supply
28,2023,31033,31,Yucatán,033,Halachó,0.823009,0.863020,High industrial demand,461.0,...,4.528,8.0,0.0,4.0,4.0,3.0,0.327987,0.343107,Low B2B supply,High demand + low B2B supply
29,2023,30208,30,Veracruz de Ignacio de la Llave,208,Carlos A. Carrillo,0.797659,0.842013,High industrial demand,116.0,...,2.189,14.0,1.0,3.0,10.0,6.0,0.478545,0.496718,Low B2B supply,High demand + low B2B supply

HIGH DEMAND + HIGH B2B SUPPLY

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,total_manufacturing_investment,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile
0,2018,15106,15,México,106,Toluca,0.997305,1.000000,Top industrial demand,4351.0,...,3917.262,2404.0,311.0,885.0,1208.0,92.0,0.990802,0.992428,Top B2B supply,High demand + high B2B supply
1,2018,24028,24,San Luis Potosí,028,San Luis Potosí,0.997127,0.999555,Top industrial demand,3824.0,...,8373.471,3054.0,486.0,1448.0,1120.0,99.0,0.995278,0.996882,Top B2B supply,High demand + high B2B supply
2,2018,02004,02,Baja California,004,Tijuana,0.996815,0.999109,Top industrial demand,3670.0,...,5618.985,4275.0,782.0,1905.0,1588.0,105.0,0.998352,0.999555,Top B2B supply,High demand + high B2B supply
3,2018,14039,14,Jalisco,039,Guadalajara,0.995345,0.998664,Top industrial demand,8007.0,...,2409.978,7008.0,817.0,3751.0,2440.0,110.0,0.999733,1.000000,Top B2B supply,High demand + high B2B supply
4,2018,22014,22,Querétaro,014,Querétaro,0.995122,0.998218,Top industrial demand,3363.0,...,12126.712,3543.0,427.0,1809.0,1307.0,103.0,0.996080,0.997327,Top B2B supply,High demand + high B2B supply
5,2018,01001,01,Aguascalientes,001,Aguascalientes,0.995056,0.997773,Top industrial demand,3896.0,...,3845.502,2938.0,352.0,1395.0,1191.0,99.0,0.994098,0.995546,Top B2B supply,High demand + high B2B supply
6,2018,14120,14,Jalisco,120,Zapopan,0.994076,0.997327,Top industrial demand,4395.0,...,2894.772,2728.0,334.0,1177.0,1217.0,101.0,0.993898,0.995100,Top B2B supply,High demand + high B2B supply
7,2018,19039,19,Nuevo León,039,Monterrey,0.993964,0.996882,Top industrial demand,4729.0,...,3248.158,4737.0,627.0,2543.0,1567.0,102.0,0.997973,0.998664,Top B2B supply,High demand + high B2B supply
8,2018,08037,08,Chihuahua,037,Juárez,0.993853,0.996437,Top industrial demand,2375.0,...,3176.689,2135.0,553.0,799.0,783.0,93.0,0.992160,0.993764,Top B2B supply,High demand + high B2B supply
9,2018,05030,05,Coahuila de Zaragoza,030,Saltillo,0.993831,0.995991,Top industrial demand,2654.0,...,3237.461,1608.0,240.0,712.0,656.0,86.0,0.985089,0.987528,Top B2B supply,High demand + high B2B supply
10,2018,11020,11,Guanajuato,020,León,0.992138,0.995546,Top industrial demand,10899.0,...,2270.654,4220.0,539.0,1837.0,1844.0,98.0,0.996526,0.997773,Top B2B supply,High demand + high B2B supply
11,2018,26030,26,Sonora,030,Hermosillo,0.991938,0.995100,Top industrial demand,4103.0,...,1069.498,2256.0,346.0,1283.0,627.0,97.0,0.991425,0.993318,Top B2B supply,High demand + high B2B supply
12,2018,15033,15,México,033,Ecatepec de Morelos,0.991292,0.994655,Top industrial demand,6689.0,...,2494.782,2562.0,181.0,897.0,1484.0,75.0,0.983408,0.985746,Top B2B supply,High demand + high B2B supply
13,2018,05035,05,Coahuila de Zaragoza,035,Torreón,0.990713,0.994209,Top industrial demand,2046.0,...,3023.038,1953.0,280.0,1012.0,661.0,92.0,0.989176,0.989310,Top B2B supply,High demand + high B2B supply
14,2018,08019,08,Chihuahua,019,Chihuahua,0.989109,0.993764,Top industrial demand,2816.0,...,2053.679,2153.0,377.0,1094.0,682.0,98.0,0.992383,0.994209,Top B2B supply,High demand + high B2B supply
15,2018,21114,21,Puebla,114,Puebla,0.989087,0.993318,Top industrial demand,6849.0,...,1999.195,5014.0,611.0,2303.0,2100.0,107.0,0.998330,0.999109,Top B2B supply,High demand + high B2B supply
16,2018,02002,02,Baja California,002,Mexicali,0.988374,0.992873,Top industrial demand,2320.0,...,1758.925,1904.0,375.0,905.0,624.0,95.0,0.990423,0.991091,Top B2B supply,High demand + high B2B supply
17,2018,19006,19,Nuevo León,006,Apodaca,0.987706,0.992428,Top industrial demand,1328.0,...,3127.568,770.0,317.0,175.0,278.0,74.0,0.971136,0.970601,Top B2B supply,High demand + high B2B supply
18,2018,11007,11,Guanajuato,007,Celaya,0.987127,0.991982,Top industrial demand,2089.0,...,2132.214,1412.0,177.0,667.0,568.0,79.0,0.979421,0.982183,Top B2B supply,High demand + high B2B supply
19,2018,11017,11,Guanajuato,017,Irapuato,0.987016,0.991537,Top industrial demand,1908.0,...,4152.540,1444.0,184.0,676.0,584.0,80.0,0.980200,0.982628,Top B2B supply,High demand + high B2B supply
20,2018,09007,09,Ciudad de México,007,Iztapalapa,0.986281,0.991091,Top industrial demand,7385.0,...,1331.167,2974.0,299.0,978.0,1697.0,88.0,0.991347,0.992873,Top B2B supply,High demand + high B2B supply
21,2018,15104,15,México,104,Tlalnepantla de Baz,0.984855,0.990646,Top industrial demand,2380.0,...,1469.627,1690.0,231.0,739.0,720.0,83.0,0.984900,0.987082,Top B2B supply,High demand + high B2B supply
22,2018,09002,09,Ciudad de México,002,Azcapotzalco,0.983842,0.990200,Top industrial demand,1580.0,...,1951.378,1081.0,258.0,386.0,437.0,83.0,0.980512,0.983073,Top B2B supply,High demand + high B2B supply
23,2018,19026,19,Nuevo León,026,Guadalupe,0.982929,0.989755,Top industrial demand,2005.0,...,1295.058,1012.0,233.0,356.0,423.0,78.0,0.976849,0.977283,Top B2B supply,High demand + high B2B supply
24,2018,19046,19,Nuevo León,046,San Nicolás de los Garza,0.981893,0.989310,Top industrial demand,1130.0,...,3316.959,864.0,209.0,342.0,313.0,81.0,0.974499,0.973719,Top B2B supply,High demand + high B2B supply
25,2018,15057,15,México,057,Naucalpan de Juárez,0.981247,0.988864,Top industrial demand,2327.0,...,857.121,1563.0,118.0,690.0,755.0,81.0,0.978530,0.980401,Top B2B supply,High demand + high B2B supply
26,2018,15121,15,México,121,Cuautitlán Izcalli,0.980579,0.988419,Top industrial demand,1563.0,...,1665.938,930.0,163.0,339.0,428.0,73.0,0.973029,0.972829,Top B2B supply,High demand + high B2B supply
27,2018,14098,14,Jalisco,098,San Pedro Tlaquepaque,0.980356,0.987973,Top industrial demand,2556.0,...,644.145,975.0,262.0,206.0,507.0,70.0,0.974588,0.974610,Top B2B supply,High demand + high B2B supply
28,2018,28032,28,Tamaulipas,032,Reynosa,0.980200,0.987528,Top industrial demand,1359.0,...,890.009,1284.0,331.0,485.0,468.0,80.0,0.982984,0.984855,Top B2B supply,High demand + high B2B supply
29,2018,11037,11,Guanajuato,037,Silao de la Victoria,0.977171,0.987082,Top industrial demand,805.0,...,5507.372,372.0,74.0,117.0,181.0,57.0,0.948207,0.952339,Top B2B supply,High demand + high B2B supply

CROSS TAB

,year,demand_supply_profile,n_municipality_years,n_municipalities,avg_industrial_demand_score,avg_b2b_supply_score,avg_manufacturing_employment,avg_b2b_total,avg_logistics,share_municipality_years
0,2018,High demand + high B2B supply,429,429,0.869226,0.888273,13580.337995,506.440559,76.895105,0.191091
1,2018,High demand + low B2B supply,23,23,0.777090,0.380611,2040.826087,13.956522,0.695652,0.010245
2,2018,Low demand + high B2B supply,5,5,0.447517,0.761236,138.200000,49.600000,12.400000,0.002227
3,2018,Low demand + low B2B supply,944,944,0.242500,0.249937,67.639831,4.417373,0.658898,0.420490
4,2018,Middle cases,844,844,0.593686,0.584633,650.176540,30.889810,5.471564,0.375947
5,2023,High demand + high B2B supply,436,436,0.864035,0.889232,14813.130734,459.068807,81.133028,0.190810
6,2023,High demand + low B2B supply,30,30,0.771449,0.381920,2319.266667,11.833333,0.533333,0.013129
7,2023,Low demand + high B2B supply,6,6,0.407566,0.763120,144.166667,45.500000,12.833333,0.002626
8,2023,Low demand + low B2B supply,963,963,0.245205,0.249678,77.427830,3.922118,0.595016,0.421444
9,2023,Middle cases,850,850,0.593599,0.586845,688.152941,28.117647,5.029412,0.371991

Archivos guardados en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics

In [ ]:
# ============================================================
# 06B. VISTAS DE DEMANDA INDUSTRIAL × OFERTA B2B
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Revisar en pantalla:
# 1. Top B2B supply
# 2. Bottom B2B supply
# 3. High demand + low B2B supply
# 4. High demand + high B2B supply
# 5. Tabla cruzada demanda-oferta
#
# NO GUARDA ARCHIVOS.
#
# Inputs:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/
#   01_industrial_demand_score_diagnostic.csv
#   05_b2b_supply_score_diagnostic.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    """
    Devuelve MyDrive si ya está montado.
    Si no, intenta montar Drive.
    """

    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

diagnostics_path = (
    project_path / "data" / "processed" / "modeling_base" / "scoring_diagnostics"
)

demand_path = diagnostics_path / "01_industrial_demand_score_diagnostic.csv"
b2b_path = diagnostics_path / "05_b2b_supply_score_diagnostic.csv"

print("Demand input:")
print(demand_path)

print("\nB2B input:")
print(b2b_path)

if not demand_path.exists():
    raise FileNotFoundError(f"No encontré el diagnóstico de demanda: {demand_path}")

if not b2b_path.exists():
    raise FileNotFoundError(f"No encontré el diagnóstico de oferta B2B: {b2b_path}")


# ------------------------------------------------------------
# 2. Cargar diagnósticos
# ------------------------------------------------------------

demand = pd.read_csv(
    demand_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

b2b = pd.read_csv(
    b2b_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

for data in [demand, b2b]:
    data["year"] = pd.to_numeric(data["year"], errors="coerce").astype("Int64")
    data["entidad_id"] = data["entidad_id"].astype(str).str.strip().str.zfill(2)
    data["municipio_id"] = data["municipio_id"].astype(str).str.strip().str.zfill(3)
    data["geo_key"] = data["entidad_id"] + data["municipio_id"]

print("\nDiagnóstico de demanda:")
print(f"Filas: {demand.shape[0]:,} | Columnas: {demand.shape[1]:,}")

print("\nDiagnóstico de oferta B2B:")
print(f"Filas: {b2b.shape[0]:,} | Columnas: {b2b.shape[1]:,}")


# ------------------------------------------------------------
# 3. Validar columnas mínimas
# ------------------------------------------------------------

required_demand_cols = [
    "year",
    "geo_key",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "industrial_demand_score",
    "industrial_demand_percentile",
    "industrial_demand_group",
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

required_b2b_cols = [
    "year",
    "geo_key",
    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",
    "b2b_supply_score",
    "b2b_supply_percentile",
    "b2b_supply_group"
]

missing_demand_cols = [
    col for col in required_demand_cols
    if col not in demand.columns
]

missing_b2b_cols = [
    col for col in required_b2b_cols
    if col not in b2b.columns
]

if missing_demand_cols:
    raise ValueError(f"Faltan columnas en demanda: {missing_demand_cols}")

if missing_b2b_cols:
    raise ValueError(f"Faltan columnas en oferta B2B: {missing_b2b_cols}")


# ------------------------------------------------------------
# 4. Cruzar demanda + oferta B2B
# ------------------------------------------------------------

combined = demand[required_demand_cols].merge(
    b2b[required_b2b_cols],
    on=["year", "geo_key"],
    how="inner"
)

print("\nBase combinada:")
print(f"Filas: {combined.shape[0]:,}")
print(f"Columnas: {combined.shape[1]:,}")


# ------------------------------------------------------------
# 5. Crear perfiles cruzados
# ------------------------------------------------------------

def classify_demand_supply_profile(row):
    demand_p = row["industrial_demand_percentile"]
    b2b_p = row["b2b_supply_percentile"]

    if demand_p >= 0.75 and b2b_p < 0.50:
        return "High demand + low B2B supply"

    elif demand_p >= 0.75 and b2b_p >= 0.75:
        return "High demand + high B2B supply"

    elif demand_p < 0.50 and b2b_p >= 0.75:
        return "Low demand + high B2B supply"

    elif demand_p < 0.50 and b2b_p < 0.50:
        return "Low demand + low B2B supply"

    else:
        return "Middle cases"


combined["demand_supply_profile"] = combined.apply(
    classify_demand_supply_profile,
    axis=1
)

combined["demand_minus_b2b_supply_percentile"] = (
    combined["industrial_demand_percentile"]
    - combined["b2b_supply_percentile"]
)


# ------------------------------------------------------------
# 6. Crear tablas interesantes
# ------------------------------------------------------------

top_b2b_supply = (
    combined
    .sort_values(
        ["year", "b2b_supply_score"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

bottom_b2b_supply = (
    combined
    .sort_values(
        ["year", "b2b_supply_score"],
        ascending=[True, True]
    )
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

high_demand_low_b2b = (
    combined[
        (combined["industrial_demand_percentile"] >= 0.75) &
        (combined["b2b_supply_percentile"] < 0.50)
    ]
    .sort_values(
        [
            "year",
            "demand_minus_b2b_supply_percentile",
            "industrial_demand_percentile",
            "b2b_supply_percentile"
        ],
        ascending=[True, False, False, True]
    )
    .reset_index(drop=True)
)

high_demand_high_b2b = (
    combined[
        (combined["industrial_demand_percentile"] >= 0.75) &
        (combined["b2b_supply_percentile"] >= 0.75)
    ]
    .sort_values(
        [
            "year",
            "industrial_demand_percentile",
            "b2b_supply_percentile"
        ],
        ascending=[True, False, False]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 7. Tabla cruzada resumen
# ------------------------------------------------------------

cross_tab = (
    combined
    .groupby(["year", "demand_supply_profile"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_industrial_demand_score=("industrial_demand_score", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_b2b_supply_score=("b2b_supply_score", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_demand_minus_b2b_supply_percentile=("demand_minus_b2b_supply_percentile", "mean"),
        avg_manufacturing_establishments=("total_manufacturing_establishments", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_b2b_total_descriptive=("denue_b2b_support_establishments", "mean"),
        avg_logistics=("denue_logistics_storage_establishments", "mean"),
        avg_professional_technical=("denue_professional_technical_establishments", "mean"),
        avg_business_support=("denue_business_support_establishments", "mean"),
        avg_b2b_scian_classes=("denue_b2b_support_scian_classes", "mean")
    )
    .reset_index()
)

cross_tab["share_municipality_years"] = (
    cross_tab["n_municipality_years"] /
    cross_tab.groupby("year")["n_municipality_years"].transform("sum")
)

profile_order = {
    "High demand + low B2B supply": 1,
    "High demand + high B2B supply": 2,
    "Low demand + high B2B supply": 3,
    "Low demand + low B2B supply": 4,
    "Middle cases": 5
}

cross_tab["profile_order"] = (
    cross_tab["demand_supply_profile"]
    .map(profile_order)
)

cross_tab = (
    cross_tab
    .sort_values(["year", "profile_order"])
    .drop(columns=["profile_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 8. Mostrar resultados
# ------------------------------------------------------------

print("\nTOP B2B SUPPLY")
print("=" * 100)
display(top_b2b_supply.head(20))

print("\nBOTTOM B2B SUPPLY")
print("=" * 100)
display(bottom_b2b_supply.head(20))

print("\nHIGH DEMAND + LOW B2B SUPPLY")
print("=" * 100)
display(high_demand_low_b2b.head(30))

print("\nHIGH DEMAND + HIGH B2B SUPPLY")
print("=" * 100)
display(high_demand_high_b2b.head(30))

print("\nCROSS TAB")
print("=" * 100)
display(cross_tab)

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas demanda:", len(demand))
print("Filas B2B:", len(b2b))
print("Filas combinadas:", len(combined))
print("Missing industrial_demand_percentile:", combined["industrial_demand_percentile"].isna().sum())
print("Missing b2b_supply_percentile:", combined["b2b_supply_percentile"].isna().sum())

Montando Google Drive en /content/drive...
Mounted at /content/drive
Google Drive montado correctamente en: /content/drive/MyDrive
Demand input:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/01_industrial_demand_score_diagnostic.csv

B2B input:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/scoring_diagnostics/05_b2b_supply_score_diagnostic.csv

Diagnóstico de demanda:
Filas: 4,530 | Columnas: 19

Diagnóstico de oferta B2B:
Filas: 4,530 | Columnas: 18

Base combinada:
Filas: 4,530
Columnas: 22

TOP B2B SUPPLY
====================================================================================================

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile,demand_minus_b2b_supply_percentile
0,2018,14039,14,Jalisco,039,Guadalajara,0.995345,0.998664,Top industrial demand,8007.0,...,7008.0,817.0,3751.0,2440.0,110.0,0.999733,1.000000,Top B2B supply,High demand + high B2B supply,-0.001336
1,2018,02004,02,Baja California,004,Tijuana,0.996815,0.999109,Top industrial demand,3670.0,...,4275.0,782.0,1905.0,1588.0,105.0,0.998352,0.999555,Top B2B supply,High demand + high B2B supply,-0.000445
2,2018,21114,21,Puebla,114,Puebla,0.989087,0.993318,Top industrial demand,6849.0,...,5014.0,611.0,2303.0,2100.0,107.0,0.998330,0.999109,Top B2B supply,High demand + high B2B supply,-0.005791
3,2018,19039,19,Nuevo León,039,Monterrey,0.993964,0.996882,Top industrial demand,4729.0,...,4737.0,627.0,2543.0,1567.0,102.0,0.997973,0.998664,Top B2B supply,High demand + high B2B supply,-0.001782
4,2018,09015,09,Ciudad de México,015,Cuauhtémoc,0.976570,0.985746,Top industrial demand,3979.0,...,6122.0,459.0,4022.0,1641.0,99.0,0.997038,0.998218,Top B2B supply,High demand + high B2B supply,-0.012472
5,2018,11020,11,Guanajuato,020,León,0.992138,0.995546,Top industrial demand,10899.0,...,4220.0,539.0,1837.0,1844.0,98.0,0.996526,0.997773,Top B2B supply,High demand + high B2B supply,-0.002227
6,2018,22014,22,Querétaro,014,Querétaro,0.995122,0.998218,Top industrial demand,3363.0,...,3543.0,427.0,1809.0,1307.0,103.0,0.996080,0.997327,Top B2B supply,High demand + high B2B supply,0.000891
7,2018,24028,24,San Luis Potosí,028,San Luis Potosí,0.997127,0.999555,Top industrial demand,3824.0,...,3054.0,486.0,1448.0,1120.0,99.0,0.995278,0.996882,Top B2B supply,High demand + high B2B supply,0.002673
8,2018,09016,09,Ciudad de México,016,Miguel Hidalgo,0.972294,0.979955,Top industrial demand,1233.0,...,3945.0,353.0,2510.0,1082.0,104.0,0.995212,0.996437,Top B2B supply,High demand + high B2B supply,-0.016481
9,2018,31050,31,Yucatán,050,Mérida,0.976548,0.985301,Top industrial demand,3850.0,...,3121.0,412.0,1575.0,1134.0,100.0,0.995189,0.995991,Top B2B supply,High demand + high B2B supply,-0.010690
10,2018,01001,01,Aguascalientes,001,Aguascalientes,0.995056,0.997773,Top industrial demand,3896.0,...,2938.0,352.0,1395.0,1191.0,99.0,0.994098,0.995546,Top B2B supply,High demand + high B2B supply,0.002227
11,2018,14120,14,Jalisco,120,Zapopan,0.994076,0.997327,Top industrial demand,4395.0,...,2728.0,334.0,1177.0,1217.0,101.0,0.993898,0.995100,Top B2B supply,High demand + high B2B supply,0.002227
12,2018,09014,09,Ciudad de México,014,Benito Juárez,0.961938,0.974610,Top industrial demand,1271.0,...,4296.0,299.0,2983.0,1014.0,105.0,0.993731,0.994655,Top B2B supply,High demand + high B2B supply,-0.020045
13,2018,08019,08,Chihuahua,019,Chihuahua,0.989109,0.993764,Top industrial demand,2816.0,...,2153.0,377.0,1094.0,682.0,98.0,0.992383,0.994209,Top B2B supply,High demand + high B2B supply,-0.000445
14,2018,08037,08,Chihuahua,037,Juárez,0.993853,0.996437,Top industrial demand,2375.0,...,2135.0,553.0,799.0,783.0,93.0,0.992160,0.993764,Top B2B supply,High demand + high B2B supply,0.002673
15,2018,26030,26,Sonora,030,Hermosillo,0.991938,0.995100,Top industrial demand,4103.0,...,2256.0,346.0,1283.0,627.0,97.0,0.991425,0.993318,Top B2B supply,High demand + high B2B supply,0.001782
16,2018,09007,09,Ciudad de México,007,Iztapalapa,0.986281,0.991091,Top industrial demand,7385.0,...,2974.0,299.0,978.0,1697.0,88.0,0.991347,0.992873,Top B2B supply,High demand + high B2B supply,-0.001782
17,2018,15106,15,México,106,Toluca,0.997305,1.000000,Top industrial demand,4351.0,...,2404.0,311.0,885.0,1208.0,92.0,0.990802,0.992428,Top B2B supply,High demand + high B2B supply,0.007572
18,2018,09005,09,Ciudad de México,005,Gustavo A. Madero,0.974187,0.981737,Top industrial demand,3749.0,...,2293.0,409.0,827.0,1057.0,85.0,0.990601,0.991982,Top B2B supply,High demand + high B2B supply,-0.010245
19,2018,30193,30,Veracruz de Ignacio de la Llave,193,Veracruz,0.971570,0.979510,Top industrial demand,1541.0,...,2005.0,572.0,747.0,686.0,86.0,0.990490,0.991537,Top B2B supply,High demand + high B2B supply,-0.012027

BOTTOM B2B SUPPLY
====================================================================================================

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile,demand_minus_b2b_supply_percentile
0,2018,19016,19,Nuevo León,016,Doctor González,0.558018,0.559911,Medium industrial demand,8.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.537194
1,2018,17035,17,Morelos,035,Xoxocotla,0.560624,0.563920,Medium industrial demand,208.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.541203
2,2018,31016,31,Yucatán,016,Chacsinkín,0.576325,0.584855,Medium industrial demand,448.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.562138
3,2018,17034,17,Morelos,034,Coatetelco,0.475234,0.465479,Low industrial demand,74.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.442762
4,2018,20497,20,Oaxaca,497,Santiago Yaitepec,0.569644,0.575501,Medium industrial demand,278.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.552784
5,2018,29003,29,Tlaxcala,003,Atlangatepec,0.491726,0.485078,Low industrial demand,7.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.462361
6,2018,20328,20,Oaxaca,328,San Pedro Taviche,0.555223,0.556347,Medium industrial demand,296.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.533630
7,2018,20313,20,Oaxaca,313,San Pedro Jocotipac,0.520991,0.522049,Medium industrial demand,195.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.499332
8,2018,20533,20,Oaxaca,533,Santo Tomás Tamazulapan,0.425490,0.418263,Low industrial demand,15.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.395546
9,2018,20564,20,Oaxaca,564,Yutanduchi de Guerrero,0.515212,0.513586,Medium industrial demand,264.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.490869
10,2018,21193,21,Puebla,193,Tzicatlacoyan,0.518920,0.519822,Medium industrial demand,207.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Middle cases,0.497105
11,2018,20416,20,Oaxaca,416,Santa María Ixcatlán,0.464978,0.456570,Low industrial demand,155.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.433853
12,2018,20080,20,Oaxaca,080,San Agustín Amatengo,0.408396,0.393987,Low industrial demand,49.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.371269
13,2018,08051,08,Chihuahua,051,Ocampo,0.317160,0.301559,Low industrial demand,12.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.278842
14,2018,21095,21,Puebla,095,La Magdalena Tlatlauquitepec,0.308096,0.292205,Low industrial demand,23.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.269488
15,2018,31086,31,Yucatán,086,Tepakán,0.366893,0.351448,Low industrial demand,82.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.328731
16,2018,20311,20,Oaxaca,311,San Pedro Jaltepetongo,0.416336,0.406236,Low industrial demand,137.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.383519
17,2018,20113,20,Oaxaca,113,San Baltazar Loxicha,0.388875,0.371938,Low industrial demand,71.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.349220
18,2018,20146,20,Oaxaca,146,San Francisco Logueche,0.355089,0.337639,Low industrial demand,120.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.314922
19,2018,20095,20,Oaxaca,095,San Andrés Paxtlán,0.274376,0.259688,Low industrial demand,34.0,...,0.0,0.0,0.0,0.0,0.0,0.098118,0.022717,Low B2B supply,Low demand + low B2B supply,0.236971

HIGH DEMAND + LOW B2B SUPPLY
====================================================================================================

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile,demand_minus_b2b_supply_percentile
0,2018,31085,31,Yucatán,085,Temozón,0.776782,0.808909,High industrial demand,1044.0,...,6.0,0.0,1.0,5.0,2.0,0.260401,0.260134,Low B2B supply,High demand + low B2B supply,0.548775
1,2018,31080,31,Yucatán,080,Tekit,0.827439,0.861470,High industrial demand,1052.0,...,7.0,0.0,2.0,5.0,4.0,0.317394,0.328508,Low B2B supply,High demand + low B2B supply,0.532962
2,2018,12019,12,Guerrero,019,Copalillo,0.770512,0.802673,High industrial demand,1063.0,...,10.0,0.0,1.0,9.0,2.0,0.288463,0.289978,Low B2B supply,High demand + low B2B supply,0.512695
3,2018,29037,29,Tlaxcala,037,Ziltlaltépec de Trinidad Sánchez Santos,0.764220,0.795991,High industrial demand,57.0,...,7.0,0.0,1.0,6.0,3.0,0.287929,0.289532,Low B2B supply,High demand + low B2B supply,0.506459
4,2018,12074,12,Guerrero,074,Zitlala,0.828441,0.862806,High industrial demand,1972.0,...,12.0,0.0,3.0,9.0,3.0,0.346102,0.365256,Low B2B supply,High demand + low B2B supply,0.497550
5,2018,31002,31,Yucatán,002,Acanceh,0.760390,0.791091,High industrial demand,90.0,...,7.0,1.0,0.0,6.0,2.0,0.295267,0.297105,Low B2B supply,High demand + low B2B supply,0.493987
6,2018,15056,15,México,056,Morelos,0.766604,0.799109,High industrial demand,203.0,...,22.0,0.0,1.0,21.0,2.0,0.324989,0.337194,Low B2B supply,High demand + low B2B supply,0.461915
7,2018,21124,21,Puebla,124,San Gabriel Chilac,0.778029,0.810245,High industrial demand,600.0,...,10.0,0.0,1.0,9.0,5.0,0.335412,0.350111,Low B2B supply,High demand + low B2B supply,0.460134
8,2018,17033,17,Morelos,033,Temoac,0.799577,0.836080,High industrial demand,690.0,...,27.0,1.0,0.0,26.0,3.0,0.378831,0.397773,Low B2B supply,High demand + low B2B supply,0.438307
9,2018,29059,29,Tlaxcala,059,Santa Cruz Quilehtla,0.820067,0.858352,High industrial demand,165.0,...,12.0,1.0,2.0,9.0,4.0,0.421849,0.438753,Low B2B supply,High demand + low B2B supply,0.419599
10,2018,21104,21,Puebla,104,Nopalucan,0.865913,0.894432,High industrial demand,168.0,...,20.0,3.0,0.0,17.0,5.0,0.463051,0.478396,Low B2B supply,High demand + low B2B supply,0.416036
11,2018,20045,20,Oaxaca,045,Magdalena Apasco,0.734844,0.762138,High industrial demand,82.0,...,7.0,0.0,3.0,4.0,5.0,0.335367,0.349666,Low B2B supply,High demand + low B2B supply,0.412472
12,2018,01009,01,Aguascalientes,009,Tepezalá,0.732739,0.760356,High industrial demand,40.0,...,11.0,0.0,2.0,9.0,4.0,0.345457,0.362584,Low B2B supply,High demand + low B2B supply,0.397773
13,2018,14109,14,Jalisco,109,Unión de San Antonio,0.757439,0.787082,High industrial demand,64.0,...,13.0,0.0,10.0,3.0,7.0,0.392840,0.408909,Low B2B supply,High demand + low B2B supply,0.378174
14,2018,29019,29,Tlaxcala,019,Tepetitla de Lardizábal,0.828163,0.862361,High industrial demand,180.0,...,38.0,0.0,6.0,32.0,7.0,0.475022,0.488196,Low B2B supply,High demand + low B2B supply,0.374165
15,2018,21149,21,Puebla,149,Santiago Miahuatlán,0.815056,0.852116,High industrial demand,220.0,...,17.0,1.0,2.0,14.0,6.0,0.464655,0.480178,Low B2B supply,High demand + low B2B supply,0.371938
16,2018,30052,30,Veracruz de Ignacio de la Llave,052,Cuichapa,0.757572,0.787528,High industrial demand,51.0,...,7.0,2.0,2.0,3.0,4.0,0.414688,0.432517,Low B2B supply,High demand + low B2B supply,0.355011
17,2018,31004,31,Yucatán,004,Baca,0.730902,0.758129,High industrial demand,38.0,...,9.0,1.0,2.0,6.0,3.0,0.386927,0.404009,Low B2B supply,High demand + low B2B supply,0.354120
18,2018,15072,15,México,072,Rayón,0.794254,0.830290,High industrial demand,171.0,...,22.0,1.0,2.0,19.0,5.0,0.466971,0.482851,Low B2B supply,High demand + low B2B supply,0.347439
19,2018,19034,19,Nuevo León,034,Marín,0.743118,0.771938,High industrial demand,27.0,...,6.0,3.0,1.0,2.0,5.0,0.416514,0.435635,Low B2B supply,High demand + low B2B supply,0.336303
20,2018,31053,31,Yucatán,053,Muna,0.761180,0.791537,High industrial demand,282.0,...,13.0,1.0,3.0,9.0,6.0,0.460401,0.476615,Low B2B supply,High demand + low B2B supply,0.314922
21,2018,20475,20,Oaxaca,475,Santiago Matatlán,0.735924,0.763920,High industrial demand,230.0,...,13.0,1.0,3.0,9.0,4.0,0.437773,0.449889,Low B2B supply,High demand + low B2B supply,0.314031
22,2018,15006,15,México,006,Almoloya del Río,0.723898,0.751002,High industrial demand,575.0,...,25.0,0.0,6.0,19.0,5.0,0.437739,0.449443,Low B2B supply,High demand + low B2B supply,0.301559
23,2023,24059,24,San Luis Potosí,059,Villa de Pozos,0.936258,0.957987,Top industrial demand,460.0,...,0.0,0.0,0.0,0.0,0.0,0.101127,0.028665,Low B2B supply,High demand + low B2B supply,0.929322
24,2023,25019,25,Sinaloa,019,Eldorado,0.734387,0.762801,High industrial demand,186.0,...,0.0,0.0,0.0,0.0,0.0,0.101127,0.028665,Low B2B supply,High demand + low B2B supply,0.734136
25,2023,31033,31,Yucatán,033,Halachó,0.823009,0.863020,High industrial demand,461.0,...,8.0,0.0,4.0,4.0,3.0,0.327987,0.343107,Low B2B supply,High demand + low B2B supply,0.519912
26,2023,07007,07,Chiapas,007,Amatenango del Valle,0.742582,0.771991,High industrial demand,1147.0,...,6.0,0.0,1.0,5.0,2.0,0.270263,0.272648,Low B2B supply,High demand + low B2B supply,0.499344
27,2023,31075,31,Yucatán,075,Teabo,0.729245,0.755799,High industrial demand,1156.0,...,3.0,1.0,0.0,2.0,2.0,0.261849,0.256674,Low B2B supply,High demand + low B2B supply,0.499125
28,2023,29059,29,Tlaxcala,059,Santa Cruz Quilehtla,0.828556,0.867396,High industrial demand,224.0,...,8.0,1.0,1.0,6.0,3.0,0.377812,0.396061,Low B2B supply,High demand + low B2B supply,0.471335
29,2023,12074,12,Guerrero,074,Zitlala,0.770788,0.806346,High industrial demand,1732.0,...,13.0,0.0,1.0,12.0,3.0,0.330919,0.347046,Low B2B supply,High demand + low B2B supply,0.459300

HIGH DEMAND + HIGH B2B SUPPLY
====================================================================================================

,year,geo_key,entidad_id,entidad_name,municipio_id,municipio_name,industrial_demand_score,industrial_demand_percentile,industrial_demand_group,total_manufacturing_establishments,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,b2b_supply_score,b2b_supply_percentile,b2b_supply_group,demand_supply_profile,demand_minus_b2b_supply_percentile
0,2018,15106,15,México,106,Toluca,0.997305,1.000000,Top industrial demand,4351.0,...,2404.0,311.0,885.0,1208.0,92.0,0.990802,0.992428,Top B2B supply,High demand + high B2B supply,0.007572
1,2018,24028,24,San Luis Potosí,028,San Luis Potosí,0.997127,0.999555,Top industrial demand,3824.0,...,3054.0,486.0,1448.0,1120.0,99.0,0.995278,0.996882,Top B2B supply,High demand + high B2B supply,0.002673
2,2018,02004,02,Baja California,004,Tijuana,0.996815,0.999109,Top industrial demand,3670.0,...,4275.0,782.0,1905.0,1588.0,105.0,0.998352,0.999555,Top B2B supply,High demand + high B2B supply,-0.000445
3,2018,14039,14,Jalisco,039,Guadalajara,0.995345,0.998664,Top industrial demand,8007.0,...,7008.0,817.0,3751.0,2440.0,110.0,0.999733,1.000000,Top B2B supply,High demand + high B2B supply,-0.001336
4,2018,22014,22,Querétaro,014,Querétaro,0.995122,0.998218,Top industrial demand,3363.0,...,3543.0,427.0,1809.0,1307.0,103.0,0.996080,0.997327,Top B2B supply,High demand + high B2B supply,0.000891
5,2018,01001,01,Aguascalientes,001,Aguascalientes,0.995056,0.997773,Top industrial demand,3896.0,...,2938.0,352.0,1395.0,1191.0,99.0,0.994098,0.995546,Top B2B supply,High demand + high B2B supply,0.002227
6,2018,14120,14,Jalisco,120,Zapopan,0.994076,0.997327,Top industrial demand,4395.0,...,2728.0,334.0,1177.0,1217.0,101.0,0.993898,0.995100,Top B2B supply,High demand + high B2B supply,0.002227
7,2018,19039,19,Nuevo León,039,Monterrey,0.993964,0.996882,Top industrial demand,4729.0,...,4737.0,627.0,2543.0,1567.0,102.0,0.997973,0.998664,Top B2B supply,High demand + high B2B supply,-0.001782
8,2018,08037,08,Chihuahua,037,Juárez,0.993853,0.996437,Top industrial demand,2375.0,...,2135.0,553.0,799.0,783.0,93.0,0.992160,0.993764,Top B2B supply,High demand + high B2B supply,0.002673
9,2018,05030,05,Coahuila de Zaragoza,030,Saltillo,0.993831,0.995991,Top industrial demand,2654.0,...,1608.0,240.0,712.0,656.0,86.0,0.985089,0.987528,Top B2B supply,High demand + high B2B supply,0.008463
10,2018,11020,11,Guanajuato,020,León,0.992138,0.995546,Top industrial demand,10899.0,...,4220.0,539.0,1837.0,1844.0,98.0,0.996526,0.997773,Top B2B supply,High demand + high B2B supply,-0.002227
11,2018,26030,26,Sonora,030,Hermosillo,0.991938,0.995100,Top industrial demand,4103.0,...,2256.0,346.0,1283.0,627.0,97.0,0.991425,0.993318,Top B2B supply,High demand + high B2B supply,0.001782
12,2018,15033,15,México,033,Ecatepec de Morelos,0.991292,0.994655,Top industrial demand,6689.0,...,2562.0,181.0,897.0,1484.0,75.0,0.983408,0.985746,Top B2B supply,High demand + high B2B supply,0.008909
13,2018,05035,05,Coahuila de Zaragoza,035,Torreón,0.990713,0.994209,Top industrial demand,2046.0,...,1953.0,280.0,1012.0,661.0,92.0,0.989176,0.989310,Top B2B supply,High demand + high B2B supply,0.004900
14,2018,08019,08,Chihuahua,019,Chihuahua,0.989109,0.993764,Top industrial demand,2816.0,...,2153.0,377.0,1094.0,682.0,98.0,0.992383,0.994209,Top B2B supply,High demand + high B2B supply,-0.000445
15,2018,21114,21,Puebla,114,Puebla,0.989087,0.993318,Top industrial demand,6849.0,...,5014.0,611.0,2303.0,2100.0,107.0,0.998330,0.999109,Top B2B supply,High demand + high B2B supply,-0.005791
16,2018,02002,02,Baja California,002,Mexicali,0.988374,0.992873,Top industrial demand,2320.0,...,1904.0,375.0,905.0,624.0,95.0,0.990423,0.991091,Top B2B supply,High demand + high B2B supply,0.001782
17,2018,19006,19,Nuevo León,006,Apodaca,0.987706,0.992428,Top industrial demand,1328.0,...,770.0,317.0,175.0,278.0,74.0,0.971136,0.970601,Top B2B supply,High demand + high B2B supply,0.021826
18,2018,11007,11,Guanajuato,007,Celaya,0.987127,0.991982,Top industrial demand,2089.0,...,1412.0,177.0,667.0,568.0,79.0,0.979421,0.982183,Top B2B supply,High demand + high B2B supply,0.009800
19,2018,11017,11,Guanajuato,017,Irapuato,0.987016,0.991537,Top industrial demand,1908.0,...,1444.0,184.0,676.0,584.0,80.0,0.980200,0.982628,Top B2B supply,High demand + high B2B supply,0.008909
20,2018,09007,09,Ciudad de México,007,Iztapalapa,0.986281,0.991091,Top industrial demand,7385.0,...,2974.0,299.0,978.0,1697.0,88.0,0.991347,0.992873,Top B2B supply,High demand + high B2B supply,-0.001782
21,2018,15104,15,México,104,Tlalnepantla de Baz,0.984855,0.990646,Top industrial demand,2380.0,...,1690.0,231.0,739.0,720.0,83.0,0.984900,0.987082,Top B2B supply,High demand + high B2B supply,0.003563
22,2018,09002,09,Ciudad de México,002,Azcapotzalco,0.983842,0.990200,Top industrial demand,1580.0,...,1081.0,258.0,386.0,437.0,83.0,0.980512,0.983073,Top B2B supply,High demand + high B2B supply,0.007127
23,2018,19026,19,Nuevo León,026,Guadalupe,0.982929,0.989755,Top industrial demand,2005.0,...,1012.0,233.0,356.0,423.0,78.0,0.976849,0.977283,Top B2B supply,High demand + high B2B supply,0.012472
24,2018,19046,19,Nuevo León,046,San Nicolás de los Garza,0.981893,0.989310,Top industrial demand,1130.0,...,864.0,209.0,342.0,313.0,81.0,0.974499,0.973719,Top B2B supply,High demand + high B2B supply,0.015590
25,2018,15057,15,México,057,Naucalpan de Juárez,0.981247,0.988864,Top industrial demand,2327.0,...,1563.0,118.0,690.0,755.0,81.0,0.978530,0.980401,Top B2B supply,High demand + high B2B supply,0.008463
26,2018,15121,15,México,121,Cuautitlán Izcalli,0.980579,0.988419,Top industrial demand,1563.0,...,930.0,163.0,339.0,428.0,73.0,0.973029,0.972829,Top B2B supply,High demand + high B2B supply,0.015590
27,2018,14098,14,Jalisco,098,San Pedro Tlaquepaque,0.980356,0.987973,Top industrial demand,2556.0,...,975.0,262.0,206.0,507.0,70.0,0.974588,0.974610,Top B2B supply,High demand + high B2B supply,0.013363
28,2018,28032,28,Tamaulipas,032,Reynosa,0.980200,0.987528,Top industrial demand,1359.0,...,1284.0,331.0,485.0,468.0,80.0,0.982984,0.984855,Top B2B supply,High demand + high B2B supply,0.002673
29,2018,11037,11,Guanajuato,037,Silao de la Victoria,0.977171,0.987082,Top industrial demand,805.0,...,372.0,74.0,117.0,181.0,57.0,0.948207,0.952339,Top B2B supply,High demand + high B2B supply,0.034744

CROSS TAB
====================================================================================================

,year,demand_supply_profile,n_municipality_years,n_municipalities,avg_industrial_demand_score,avg_industrial_demand_percentile,avg_b2b_supply_score,avg_b2b_supply_percentile,avg_demand_minus_b2b_supply_percentile,avg_manufacturing_establishments,avg_manufacturing_employment,avg_b2b_total_descriptive,avg_logistics,avg_professional_technical,avg_business_support,avg_b2b_scian_classes,share_municipality_years
0,2018,High demand + low B2B supply,23,23,0.777090,0.808676,0.380611,0.393619,0.415058,394.086957,2040.826087,13.956522,0.695652,2.347826,10.913043,4.173913,0.010245
1,2018,High demand + high B2B supply,429,429,0.869226,0.894290,0.888273,0.895293,-0.001004,912.946387,13580.337995,506.440559,76.895105,222.174825,207.370629,41.550117,0.191091
2,2018,Low demand + high B2B supply,5,5,0.447517,0.437416,0.761236,0.775323,-0.337906,58.400000,138.200000,49.600000,12.400000,16.400000,20.800000,16.800000,0.002227
3,2018,Low demand + low B2B supply,944,944,0.242500,0.222661,0.249937,0.235095,-0.012434,33.556144,67.639831,4.417373,0.658898,0.679025,3.079449,2.398305,0.420490
4,2018,Middle cases,844,844,0.593686,0.602336,0.584633,0.597227,0.005109,173.268957,650.176540,30.889810,5.471564,8.849526,16.568720,10.002370,0.375947
5,2023,High demand + low B2B supply,30,30,0.771449,0.803807,0.381920,0.392560,0.411247,550.033333,2319.266667,11.833333,0.533333,3.233333,8.066667,4.533333,0.013129
6,2023,High demand + high B2B supply,436,436,0.864035,0.893709,0.889232,0.896240,-0.002531,978.694954,14813.130734,459.068807,81.133028,225.089450,152.846330,43.997706,0.190810
7,2023,Low demand + high B2B supply,6,6,0.407566,0.396426,0.763120,0.777899,-0.381473,56.833333,144.166667,45.500000,12.833333,15.333333,17.333333,18.333333,0.002626
8,2023,Low demand + low B2B supply,963,963,0.245205,0.222812,0.249678,0.233529,-0.010717,38.688474,77.427830,3.922118,0.595016,0.852544,2.474559,2.299065,0.421444
9,2023,Middle cases,850,850,0.593599,0.602685,0.586845,0.601067,0.001618,179.700000,688.152941,28.117647,5.029412,10.571765,12.516471,10.542353,0.371991

VALIDACIÓN RÁPIDA
====================================================================================================
Filas demanda: 4530
Filas B2B: 4530
Filas combinadas: 4530
Missing industrial_demand_percentile: 0
Missing b2b_supply_percentile: 0

In [ ]:
# ============================================================
# 07. DIAGNÓSTICO DEL SCALED B2B SUPPLY SCORE
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Construir y revisar en pantalla una medida de oferta B2B escalada.
#
# No guarda archivos.
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
#
# Lógica:
# b2b_scaled_capacity_proxy =
# 65.5 * denue_b2b_medium_establishments
# + 150 * denue_b2b_large_establishments
#
# scaled_b2b_supply_score =
# percentil anual de b2b_scaled_capacity_proxy
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

print("Input path:")
print(input_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(
    df["year"],
    errors="coerce"
).astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Validar variables necesarias
# ------------------------------------------------------------

required_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "denue_b2b_support_establishments",
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments"
]

missing_cols = [
    col for col in required_cols
    if col not in df.columns
]

if missing_cols:
    raise ValueError(f"Faltan columnas necesarias: {missing_cols}")

numeric_cols = [
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "denue_b2b_support_establishments",
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_numeric = df[numeric_cols].isna().sum()

print("\nMissing en variables B2B de tamaño:")
print(missing_numeric)

if missing_numeric.sum() > 0:
    raise ValueError(
        "Hay missing en variables B2B de tamaño. "
        "Revisa que estés usando la base complete-case correcta."
    )


# ------------------------------------------------------------
# 4. Construir proxy de capacidad B2B escalada
# ------------------------------------------------------------

medium_expected_workers = 65.5
large_expected_workers = 150

df["b2b_scaled_capacity_proxy"] = (
    medium_expected_workers * df["denue_b2b_medium_establishments"]
    + large_expected_workers * df["denue_b2b_large_establishments"]
)


# ------------------------------------------------------------
# 5. Normalizar por percentil anual
# ------------------------------------------------------------

df["scaled_b2b_supply_score"] = (
    df
    .groupby("year")["b2b_scaled_capacity_proxy"]
    .rank(pct=True, method="average")
)

df["scaled_b2b_supply_percentile"] = df["scaled_b2b_supply_score"]


# ------------------------------------------------------------
# 6. Crear grupo interpretable
# ------------------------------------------------------------

def classify_scaled_b2b_group(p):
    if pd.isna(p):
        return "Sin información"
    elif p >= 0.90:
        return "Top scaled B2B supply"
    elif p >= 0.75:
        return "High scaled B2B supply"
    elif p >= 0.50:
        return "Medium scaled B2B supply"
    else:
        return "Low scaled B2B supply"


df["scaled_b2b_supply_group"] = (
    df["scaled_b2b_supply_percentile"]
    .apply(classify_scaled_b2b_group)
)


# ------------------------------------------------------------
# 7. Crear variables auxiliares de atomización
# ------------------------------------------------------------

df["b2b_micro_small_establishments"] = (
    df["denue_b2b_micro_establishments"]
    + df["denue_b2b_small_establishments"]
)

df["b2b_micro_small_share"] = np.where(
    df["denue_b2b_support_establishments"] > 0,
    df["b2b_micro_small_establishments"] / df["denue_b2b_support_establishments"],
    np.nan
)

df["has_scaled_b2b_supply"] = (
    df["denue_b2b_medium_large_establishments"] > 0
).astype(int)

df["only_micro_small_b2b_supply"] = (
    (df["denue_b2b_support_establishments"] > 0) &
    (df["denue_b2b_medium_large_establishments"] == 0)
).astype(int)


# ------------------------------------------------------------
# 8. Tabla diagnóstica compacta
# ------------------------------------------------------------

scaled_diagnostic_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",
    "denue_b2b_support_establishments",
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "b2b_micro_small_establishments",
    "b2b_micro_small_share",
    "has_scaled_b2b_supply",
    "only_micro_small_b2b_supply",
    "b2b_scaled_capacity_proxy",
    "scaled_b2b_supply_score",
    "scaled_b2b_supply_percentile",
    "scaled_b2b_supply_group"
]

scaled_diagnostic = df[scaled_diagnostic_cols].copy()


# ------------------------------------------------------------
# 9. Resumen por año y grupo
# ------------------------------------------------------------

scaled_summary = (
    scaled_diagnostic
    .groupby(["year", "scaled_b2b_supply_group"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_scaled_b2b_supply_score=("scaled_b2b_supply_score", "mean"),
        avg_scaled_capacity_proxy=("b2b_scaled_capacity_proxy", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium=("denue_b2b_medium_establishments", "mean"),
        avg_b2b_large=("denue_b2b_large_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean"),
        avg_micro_small_share=("b2b_micro_small_share", "mean"),
        municipalities_with_scaled_b2b=("has_scaled_b2b_supply", "sum"),
        municipalities_only_micro_small=("only_micro_small_b2b_supply", "sum")
    )
    .reset_index()
)

scaled_summary["share_municipality_years"] = (
    scaled_summary["n_municipality_years"] /
    scaled_summary.groupby("year")["n_municipality_years"].transform("sum")
)

group_order = {
    "Top scaled B2B supply": 1,
    "High scaled B2B supply": 2,
    "Medium scaled B2B supply": 3,
    "Low scaled B2B supply": 4,
    "Sin información": 5
}

scaled_summary["group_order"] = (
    scaled_summary["scaled_b2b_supply_group"]
    .map(group_order)
)

scaled_summary = (
    scaled_summary
    .sort_values(["year", "group_order"])
    .drop(columns=["group_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Vistas interesantes
# ------------------------------------------------------------

top_scaled_b2b = (
    scaled_diagnostic
    .sort_values(
        ["year", "scaled_b2b_supply_score"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(30)
    .reset_index(drop=True)
)

bottom_scaled_b2b = (
    scaled_diagnostic
    .sort_values(
        ["year", "scaled_b2b_supply_score"],
        ascending=[True, True]
    )
    .groupby("year")
    .head(30)
    .reset_index(drop=True)
)

only_micro_small_cases = (
    scaled_diagnostic[
        scaled_diagnostic["only_micro_small_b2b_supply"] == 1
    ]
    .sort_values(
        ["year", "denue_b2b_support_establishments"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(30)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. Mostrar resultados
# ------------------------------------------------------------

print("\nPARÁMETROS DE LA PROXY")
print("=" * 100)
print(f"Medium expected workers: {medium_expected_workers}")
print(f"Large expected workers: {large_expected_workers}")

print("\nRESUMEN DEL SCALED B2B SUPPLY SCORE")
print("=" * 100)
display(scaled_summary)

print("\nTOP SCALED B2B SUPPLY")
print("=" * 100)
display(top_scaled_b2b)

print("\nBOTTOM SCALED B2B SUPPLY")
print("=" * 100)
display(bottom_scaled_b2b)

print("\nCASOS CON B2B SOLO MICRO/SMALL")
print("=" * 100)
display(only_micro_small_cases)

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas diagnosticadas:", len(scaled_diagnostic))
print("Missing b2b_scaled_capacity_proxy:", scaled_diagnostic["b2b_scaled_capacity_proxy"].isna().sum())
print("Missing scaled_b2b_supply_score:", scaled_diagnostic["scaled_b2b_supply_score"].isna().sum())
print("Años:", sorted(scaled_diagnostic["year"].dropna().unique()))

Google Drive ya está disponible en: /content/drive/MyDrive
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Base cargada:
Filas: 4,530
Columnas: 54

Missing en variables B2B de tamaño:
denue_b2b_medium_establishments          0
denue_b2b_large_establishments           0
denue_b2b_medium_large_establishments    0
denue_b2b_support_establishments         0
denue_b2b_micro_establishments           0
denue_b2b_small_establishments           0
dtype: int64

PARÁMETROS DE LA PROXY
====================================================================================================
Medium expected workers: 65.5
Large expected workers: 150

RESUMEN DEL SCALED B2B SUPPLY SCORE
====================================================================================================

,year,scaled_b2b_supply_group,n_municipality_years,n_municipalities,avg_scaled_b2b_supply_score,avg_scaled_capacity_proxy,avg_b2b_total,avg_b2b_medium,avg_b2b_large,avg_b2b_medium_large,avg_micro_small_share,municipalities_with_scaled_b2b,municipalities_only_micro_small,share_municipality_years
0,2018,Top scaled B2B supply,225,225,0.950111,5511.453333,842.986667,35.706667,21.151111,56.857778,0.933456,225,0,0.100223
1,2018,High scaled B2B supply,247,247,0.844989,232.414980,101.089069,1.712551,0.801619,2.514170,0.953742,247,0,0.110022
2,2018,Medium scaled B2B supply,184,184,0.748998,65.500000,52.173913,1.000000,0.000000,1.000000,0.944743,184,0,0.081960
3,2018,Low scaled B2B supply,1589,1589,0.354120,0.000000,14.998112,0.000000,0.000000,0.000000,1.000000,0,1488,0.707795
4,2023,Top scaled B2B supply,229,229,0.950109,6280.600437,760.314410,39.585153,24.585153,64.170306,0.916977,229,0,0.100219
5,2023,High scaled B2B supply,286,286,0.837418,231.277972,88.643357,1.961538,0.685315,2.646853,0.938071,286,0,0.125164
6,2023,Medium scaled B2B supply,210,210,0.728884,65.500000,43.442857,1.000000,0.000000,1.000000,0.936142,210,0,0.091904
7,2023,Low scaled B2B supply,1560,1560,0.341575,0.000000,12.738462,0.000000,0.000000,0.000000,1.000000,0,1430,0.682713

TOP SCALED B2B SUPPLY
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,denue_b2b_support_establishments,denue_b2b_micro_establishments,denue_b2b_small_establishments,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_establishments,b2b_micro_small_share,has_scaled_b2b_supply,only_micro_small_b2b_supply,b2b_scaled_capacity_proxy,scaled_b2b_supply_score,scaled_b2b_supply_percentile,scaled_b2b_supply_group
0,2018,09,Ciudad de México,016,Miguel Hidalgo,09016,3945.0,1552.0,1544.0,539.0,310.0,849.0,3096.0,0.784791,1,0,81804.5,1.000000,1.000000,Top scaled B2B supply
1,2018,09,Ciudad de México,015,Cuauhtémoc,09015,6122.0,3722.0,1820.0,362.0,218.0,580.0,5542.0,0.905260,1,0,56411.0,0.999555,0.999555,Top scaled B2B supply
2,2018,19,Nuevo León,039,Monterrey,19039,4737.0,2999.0,1201.0,319.0,218.0,537.0,4200.0,0.886637,1,0,53594.5,0.999109,0.999109,Top scaled B2B supply
3,2018,09,Ciudad de México,014,Benito Juárez,09014,4296.0,2017.0,1697.0,404.0,178.0,582.0,3714.0,0.864525,1,0,53162.0,0.998664,0.998664,Top scaled B2B supply
4,2018,14,Jalisco,039,Guadalajara,14039,7008.0,4863.0,1690.0,294.0,161.0,455.0,6553.0,0.935074,1,0,43407.0,0.998218,0.998218,Top scaled B2B supply
5,2018,09,Ciudad de México,010,Álvaro Obregón,09010,1679.0,934.0,469.0,167.0,109.0,276.0,1403.0,0.835616,1,0,27288.5,0.997773,0.997773,Top scaled B2B supply
6,2018,22,Querétaro,014,Querétaro,22014,3543.0,2493.0,791.0,157.0,102.0,259.0,3284.0,0.926898,1,0,25583.5,0.997327,0.997327,Top scaled B2B supply
7,2018,11,Guanajuato,020,León,11020,4220.0,3307.0,681.0,132.0,100.0,232.0,3988.0,0.945024,1,0,23646.0,0.996882,0.996882,Top scaled B2B supply
8,2018,21,Puebla,114,Puebla,21114,5014.0,4017.0,748.0,163.0,86.0,249.0,4765.0,0.950339,1,0,23576.5,0.996437,0.996437,Top scaled B2B supply
9,2018,02,Baja California,004,Tijuana,02004,4275.0,3264.0,773.0,158.0,80.0,238.0,4037.0,0.944327,1,0,22349.0,0.995991,0.995991,Top scaled B2B supply
10,2018,24,San Luis Potosí,028,San Luis Potosí,24028,3054.0,2306.0,534.0,125.0,89.0,214.0,2840.0,0.929928,1,0,21537.5,0.995546,0.995546,Top scaled B2B supply
11,2018,31,Yucatán,050,Mérida,31050,3121.0,2232.0,693.0,126.0,70.0,196.0,2925.0,0.937200,1,0,18753.0,0.995100,0.995100,Top scaled B2B supply
12,2018,08,Chihuahua,037,Juárez,08037,2135.0,1502.0,436.0,130.0,67.0,197.0,1938.0,0.907728,1,0,18565.0,0.994655,0.994655,Top scaled B2B supply
13,2018,09,Ciudad de México,017,Venustiano Carranza,09017,1624.0,1097.0,346.0,103.0,78.0,181.0,1443.0,0.888547,1,0,18446.5,0.994209,0.994209,Top scaled B2B supply
14,2018,23,Quintana Roo,005,Benito Juárez,23005,2197.0,1464.0,545.0,121.0,67.0,188.0,2009.0,0.914429,1,0,17975.5,0.993764,0.993764,Top scaled B2B supply
15,2018,14,Jalisco,120,Zapopan,14120,2728.0,1979.0,559.0,127.0,63.0,190.0,2538.0,0.930352,1,0,17768.5,0.993318,0.993318,Top scaled B2B supply
16,2018,05,Coahuila de Zaragoza,035,Torreón,05035,1953.0,1388.0,397.0,89.0,79.0,168.0,1785.0,0.913978,1,0,17679.5,0.992873,0.992873,Top scaled B2B supply
17,2018,26,Sonora,030,Hermosillo,26030,2256.0,1446.0,638.0,105.0,67.0,172.0,2084.0,0.923759,1,0,16927.5,0.992428,0.992428,Top scaled B2B supply
18,2018,09,Ciudad de México,002,Azcapotzalco,09002,1081.0,707.0,218.0,79.0,77.0,156.0,925.0,0.855689,1,0,16724.5,0.991982,0.991982,Top scaled B2B supply
19,2018,19,Nuevo León,019,San Pedro Garza García,19019,1223.0,598.0,461.0,99.0,65.0,164.0,1059.0,0.865904,1,0,16234.5,0.991537,0.991537,Top scaled B2B supply
20,2018,15,México,106,Toluca,15106,2404.0,1967.0,291.0,75.0,71.0,146.0,2258.0,0.939268,1,0,15562.5,0.991091,0.991091,Top scaled B2B supply
21,2018,09,Ciudad de México,005,Gustavo A. Madero,09005,2293.0,1828.0,309.0,96.0,60.0,156.0,2137.0,0.931967,1,0,15288.0,0.990646,0.990646,Top scaled B2B supply
22,2018,08,Chihuahua,019,Chihuahua,08019,2153.0,1433.0,577.0,88.0,55.0,143.0,2010.0,0.933581,1,0,14014.0,0.990200,0.990200,Top scaled B2B supply
23,2018,30,Veracruz de Ignacio de la Llave,193,Veracruz,30193,2005.0,1397.0,467.0,85.0,56.0,141.0,1864.0,0.929676,1,0,13967.5,0.989755,0.989755,Top scaled B2B supply
24,2018,09,Ciudad de México,004,Cuajimalpa de Morelos,09004,626.0,341.0,156.0,65.0,64.0,129.0,497.0,0.793930,1,0,13857.5,0.989310,0.989310,Top scaled B2B supply
25,2018,27,Tabasco,004,Centro,27004,1613.0,1138.0,327.0,103.0,45.0,148.0,1465.0,0.908246,1,0,13496.5,0.988864,0.988864,Top scaled B2B supply
26,2018,02,Baja California,002,Mexicali,02002,1904.0,1327.0,439.0,88.0,50.0,138.0,1766.0,0.927521,1,0,13264.0,0.988419,0.988419,Top scaled B2B supply
27,2018,19,Nuevo León,006,Apodaca,19006,770.0,466.0,180.0,68.0,56.0,124.0,646.0,0.838961,1,0,12854.0,0.987973,0.987973,Top scaled B2B supply
28,2018,25,Sinaloa,006,Culiacán,25006,1943.0,1397.0,413.0,85.0,48.0,133.0,1810.0,0.931549,1,0,12767.5,0.987528,0.987528,Top scaled B2B supply
29,2018,01,Aguascalientes,001,Aguascalientes,01001,2938.0,2262.0,536.0,99.0,41.0,140.0,2798.0,0.952349,1,0,12634.5,0.987082,0.987082,Top scaled B2B supply
30,2023,09,Ciudad de México,016,Miguel Hidalgo,09016,3349.0,1161.0,1337.0,475.0,376.0,851.0,2498.0,0.745894,1,0,87512.5,1.000000,1.000000,Top scaled B2B supply
31,2023,19,Nuevo León,039,Monterrey,19039,4888.0,2663.0,1558.0,407.0,260.0,667.0,4221.0,0.863543,1,0,65658.5,0.999562,0.999562,Top scaled B2B supply
32,2023,09,Ciudad de México,014,Benito Juárez,09014,3846.0,1659.0,1549.0,372.0,266.0,638.0,3208.0,0.834113,1,0,64266.0,0.999125,0.999125,Top scaled B2B supply
33,2023,09,Ciudad de México,015,Cuauhtémoc,09015,4790.0,2694.0,1490.0,325.0,281.0,606.0,4184.0,0.873486,1,0,63437.5,0.998687,0.998687,Top scaled B2B supply
34,2023,14,Jalisco,039,Guadalajara,14039,5649.0,3428.0,1734.0,291.0,196.0,487.0,5162.0,0.913790,1,0,48460.5,0.998249,0.998249,Top scaled B2B supply
35,2023,22,Querétaro,014,Querétaro,22014,3191.0,1959.0,883.0,203.0,146.0,349.0,2842.0,0.890630,1,0,35196.5,0.997812,0.997812,Top scaled B2B supply
36,2023,09,Ciudad de México,010,Álvaro Obregón,09010,1626.0,791.0,503.0,181.0,151.0,332.0,1294.0,0.795818,1,0,34505.5,0.997374,0.997374,Top scaled B2B supply
37,2023,02,Baja California,004,Tijuana,02004,4190.0,2833.0,1030.0,221.0,106.0,327.0,3863.0,0.921957,1,0,30375.5,0.996937,0.996937,Top scaled B2B supply
38,2023,21,Puebla,114,Puebla,21114,4506.0,3282.0,906.0,210.0,108.0,318.0,4188.0,0.929427,1,0,29955.0,0.996499,0.996499,Top scaled B2B supply
39,2023,24,San Luis Potosí,028,San Luis Potosí,24028,2779.0,1872.0,623.0,195.0,89.0,284.0,2495.0,0.897805,1,0,26122.5,0.996061,0.996061,Top scaled B2B supply
40,2023,14,Jalisco,120,Zapopan,14120,2500.0,1619.0,646.0,145.0,90.0,235.0,2265.0,0.906000,1,0,22997.5,0.995624,0.995624,Top scaled B2B supply
41,2023,08,Chihuahua,037,Juárez,08037,1869.0,1147.0,496.0,132.0,94.0,226.0,1643.0,0.879080,1,0,22746.0,0.995186,0.995186,Top scaled B2B supply
42,2023,11,Guanajuato,020,León,11020,3572.0,2594.0,739.0,158.0,81.0,239.0,3333.0,0.933091,1,0,22499.0,0.994748,0.994748,Top scaled B2B supply
43,2023,31,Yucatán,050,Mérida,31050,3185.0,1982.0,963.0,160.0,80.0,240.0,2945.0,0.924647,1,0,22480.0,0.994311,0.994311,Top scaled B2B supply
44,2023,23,Quintana Roo,005,Benito Juárez,23005,1748.0,1009.0,528.0,133.0,78.0,211.0,1537.0,0.879291,1,0,20411.5,0.993873,0.993873,Top scaled B2B supply
45,2023,26,Sonora,030,Hermosillo,26030,2300.0,1363.0,740.0,121.0,76.0,197.0,2103.0,0.914348,1,0,19325.5,0.993435,0.993435,Top scaled B2B supply
46,2023,19,Nuevo León,019,San Pedro Garza García,19019,1379.0,641.0,543.0,121.0,74.0,195.0,1184.0,0.858593,1,0,19025.5,0.992998,0.992998,Top scaled B2B supply
47,2023,15,México,106,Toluca,15106,2458.0,1929.0,350.0,97.0,82.0,179.0,2279.0,0.927177,1,0,18653.5,0.992560,0.992560,Top scaled B2B supply
48,2023,19,Nuevo León,006,Apodaca,19006,848.0,404.0,263.0,105.0,76.0,181.0,667.0,0.786557,1,0,18277.5,0.992123,0.992123,Top scaled B2B supply
49,2023,09,Ciudad de México,004,Cuajimalpa de Morelos,09004,647.0,303.0,181.0,76.0,87.0,163.0,484.0,0.748068,1,0,18028.0,0.991685,0.991685,Top scaled B2B supply
50,2023,09,Ciudad de México,017,Venustiano Carranza,09017,1354.0,818.0,367.0,90.0,79.0,169.0,1185.0,0.875185,1,0,17745.0,0.991247,0.991247,Top scaled B2B supply
51,2023,09,Ciudad de México,002,Azcapotzalco,09002,1007.0,621.0,230.0,78.0,78.0,156.0,851.0,0.845084,1,0,16809.0,0.990810,0.990810,Top scaled B2B supply
52,2023,05,Coahuila de Zaragoza,035,Torreón,05035,1810.0,1126.0,516.0,103.0,65.0,168.0,1642.0,0.907182,1,0,16496.5,0.990372,0.990372,Top scaled B2B supply
53,2023,01,Aguascalientes,001,Aguascalientes,01001,2673.0,1841.0,665.0,104.0,63.0,167.0,2506.0,0.937523,1,0,16262.0,0.989934,0.989934,Top scaled B2B supply
54,2023,15,México,057,Naucalpan de Juárez,15057,1605.0,1121.0,332.0,79.0,73.0,152.0,1453.0,0.905296,1,0,16124.5,0.989497,0.989497,Top scaled B2B supply
55,2023,02,Baja California,002,Mexicali,02002,1752.0,1084.0,492.0,123.0,53.0,176.0,1576.0,0.899543,1,0,16006.5,0.989059,0.989059,Top scaled B2B supply
56,2023,30,Veracruz de Ignacio de la Llave,193,Veracruz,30193,1701.0,1041.0,483.0,125.0,52.0,177.0,1524.0,0.895944,1,0,15987.5,0.988621,0.988621,Top scaled B2B supply
57,2023,08,Chihuahua,019,Chihuahua,08019,2164.0,1372.0,622.0,116.0,54.0,170.0,1994.0,0.921442,1,0,15698.0,0.988184,0.988184,Top scaled B2B supply
58,2023,28,Tamaulipas,027,Nuevo Laredo,28027,1379.0,689.0,519.0,119.0,52.0,171.0,1208.0,0.875997,1,0,15594.5,0.987746,0.987746,Top scaled B2B supply
59,2023,25,Sinaloa,006,Culiacán,25006,1964.0,1235.0,563.0,111.0,55.0,166.0,1798.0,0.915479,1,0,15520.5,0.987309,0.987309,Top scaled B2B supply

BOTTOM SCALED B2B SUPPLY
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,denue_b2b_support_establishments,denue_b2b_micro_establishments,denue_b2b_small_establishments,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_establishments,b2b_micro_small_share,has_scaled_b2b_supply,only_micro_small_b2b_supply,b2b_scaled_capacity_proxy,scaled_b2b_supply_score,scaled_b2b_supply_percentile,scaled_b2b_supply_group
0,2018,15,México,101,Tianguistenco,15101,167.0,159.0,8.0,0.0,0.0,0.0,167.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
1,2018,29,Tlaxcala,013,Huamantla,29013,174.0,163.0,11.0,0.0,0.0,0.0,174.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
2,2018,14,Jalisco,008,Arandas,14008,187.0,176.0,11.0,0.0,0.0,0.0,187.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
3,2018,11,Guanajuato,004,Apaseo el Alto,11004,111.0,106.0,5.0,0.0,0.0,0.0,111.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
4,2018,31,Yucatán,041,Kanasín,31041,57.0,49.0,8.0,0.0,0.0,0.0,57.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
5,2018,30,Veracruz de Ignacio de la Llave,123,Pánuco,30123,112.0,101.0,11.0,0.0,0.0,0.0,112.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
6,2018,14,Jalisco,083,Tala,14083,109.0,97.0,12.0,0.0,0.0,0.0,109.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
7,2018,31,Yucatán,038,Hunucmá,31038,41.0,40.0,1.0,0.0,0.0,0.0,41.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
8,2018,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,76.0,75.0,1.0,0.0,0.0,0.0,76.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
9,2018,22,Querétaro,007,Ezequiel Montes,22007,99.0,96.0,3.0,0.0,0.0,0.0,99.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
10,2018,13,Hidalgo,081,Zacualtipán de Ángeles,13081,71.0,68.0,3.0,0.0,0.0,0.0,71.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
11,2018,15,México,092,Teotihuacán,15092,126.0,116.0,10.0,0.0,0.0,0.0,126.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
12,2018,26,Sonora,041,Nacozari de García,26041,24.0,23.0,1.0,0.0,0.0,0.0,24.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
13,2018,29,Tlaxcala,034,Tlaxco,29034,43.0,40.0,3.0,0.0,0.0,0.0,43.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
14,2018,14,Jalisco,016,Ayotlán,14016,78.0,77.0,1.0,0.0,0.0,0.0,78.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
15,2018,29,Tlaxcala,015,Ixtacuixtla de Mariano Matamoros,29015,54.0,52.0,2.0,0.0,0.0,0.0,54.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
16,2018,29,Tlaxcala,019,Tepetitla de Lardizábal,29019,38.0,38.0,0.0,0.0,0.0,0.0,38.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
17,2018,08,Chihuahua,045,Meoqui,08045,55.0,50.0,5.0,0.0,0.0,0.0,55.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
18,2018,29,Tlaxcala,059,Santa Cruz Quilehtla,29059,12.0,12.0,0.0,0.0,0.0,0.0,12.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
19,2018,04,Campeche,001,Calkiní,04001,73.0,70.0,3.0,0.0,0.0,0.0,73.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
20,2018,15,México,019,Capulhuac,15019,78.0,77.0,1.0,0.0,0.0,0.0,78.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
21,2018,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,30160,142.0,138.0,4.0,0.0,0.0,0.0,142.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
22,2018,21,Puebla,125,San Gregorio Atzompa,21125,13.0,13.0,0.0,0.0,0.0,0.0,13.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
23,2018,05,Coahuila de Zaragoza,009,Francisco I. Madero,05009,61.0,57.0,4.0,0.0,0.0,0.0,61.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
24,2018,15,México,120,Zumpango,15120,319.0,294.0,25.0,0.0,0.0,0.0,319.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
25,2018,29,Tlaxcala,042,Xicohtzinco,29042,26.0,25.0,1.0,0.0,0.0,0.0,26.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
26,2018,21,Puebla,161,Tepanco de López,21161,26.0,25.0,1.0,0.0,0.0,0.0,26.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
27,2018,15,México,073,San Antonio la Isla,15073,42.0,41.0,1.0,0.0,0.0,0.0,42.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
28,2018,09,Ciudad de México,009,Milpa Alta,09009,236.0,234.0,2.0,0.0,0.0,0.0,236.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
29,2018,30,Veracruz de Ignacio de la Llave,173,Tezonapa,30173,46.0,45.0,1.0,0.0,0.0,0.0,46.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
30,2023,24,San Luis Potosí,059,Villa de Pozos,24059,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0.0,0.341575,0.341575,Low scaled B2B supply
31,2023,29,Tlaxcala,013,Huamantla,29013,158.0,145.0,13.0,0.0,0.0,0.0,158.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
32,2023,31,Yucatán,041,Kanasín,31041,68.0,52.0,16.0,0.0,0.0,0.0,68.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
33,2023,29,Tlaxcala,041,Papalotla de Xicohténcatl,29041,36.0,32.0,4.0,0.0,0.0,0.0,36.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
34,2023,14,Jalisco,008,Arandas,14008,219.0,200.0,19.0,0.0,0.0,0.0,219.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
35,2023,29,Tlaxcala,028,Teolocholco,29028,43.0,42.0,1.0,0.0,0.0,0.0,43.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
36,2023,29,Tlaxcala,015,Ixtacuixtla de Mariano Matamoros,29015,44.0,42.0,2.0,0.0,0.0,0.0,44.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
37,2023,30,Veracruz de Ignacio de la Llave,123,Pánuco,30123,102.0,83.0,19.0,0.0,0.0,0.0,102.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
38,2023,11,Guanajuato,030,San Felipe,11030,100.0,89.0,11.0,0.0,0.0,0.0,100.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
39,2023,01,Aguascalientes,007,Rincón de Romos,01007,57.0,56.0,1.0,0.0,0.0,0.0,57.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
40,2023,29,Tlaxcala,034,Tlaxco,29034,46.0,42.0,4.0,0.0,0.0,0.0,46.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
41,2023,30,Veracruz de Ignacio de la Llave,207,Tres Valles,30207,53.0,48.0,5.0,0.0,0.0,0.0,53.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
42,2023,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,63.0,61.0,2.0,0.0,0.0,0.0,63.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
43,2023,14,Jalisco,044,Ixtlahuacán de los Membrillos,14044,30.0,26.0,4.0,0.0,0.0,0.0,30.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
44,2023,13,Hidalgo,081,Zacualtipán de Ángeles,13081,74.0,69.0,5.0,0.0,0.0,0.0,74.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
45,2023,21,Puebla,010,Ajalpan,21010,63.0,60.0,3.0,0.0,0.0,0.0,63.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
46,2023,11,Guanajuato,001,Abasolo,11001,88.0,79.0,9.0,0.0,0.0,0.0,88.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
47,2023,29,Tlaxcala,048,La Magdalena Tlaltelulco,29048,25.0,24.0,1.0,0.0,0.0,0.0,25.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
48,2023,14,Jalisco,105,Tototlán,14105,31.0,28.0,3.0,0.0,0.0,0.0,31.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
49,2023,14,Jalisco,016,Ayotlán,14016,68.0,63.0,5.0,0.0,0.0,0.0,68.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
50,2023,29,Tlaxcala,019,Tepetitla de Lardizábal,29019,29.0,29.0,0.0,0.0,0.0,0.0,29.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
51,2023,21,Puebla,125,San Gregorio Atzompa,21125,19.0,19.0,0.0,0.0,0.0,0.0,19.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
52,2023,08,Chihuahua,011,Camargo,08011,101.0,89.0,12.0,0.0,0.0,0.0,101.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
53,2023,15,México,005,Almoloya de Juárez,15005,117.0,113.0,4.0,0.0,0.0,0.0,117.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
54,2023,15,México,073,San Antonio la Isla,15073,38.0,38.0,0.0,0.0,0.0,0.0,38.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
55,2023,32,Zacatecas,020,Jerez,32020,163.0,151.0,12.0,0.0,0.0,0.0,163.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
56,2023,16,Michoacán de Ocampo,105,Vista Hermosa,16105,22.0,15.0,7.0,0.0,0.0,0.0,22.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
57,2023,30,Veracruz de Ignacio de la Llave,208,Carlos A. Carrillo,30208,14.0,14.0,0.0,0.0,0.0,0.0,14.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
58,2023,13,Hidalgo,029,Huichapan,13029,89.0,79.0,10.0,0.0,0.0,0.0,89.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
59,2023,15,México,067,Otzolotepec,15067,85.0,84.0,1.0,0.0,0.0,0.0,85.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply

CASOS CON B2B SOLO MICRO/SMALL
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,denue_b2b_support_establishments,denue_b2b_micro_establishments,denue_b2b_small_establishments,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_establishments,b2b_micro_small_share,has_scaled_b2b_supply,only_micro_small_b2b_supply,b2b_scaled_capacity_proxy,scaled_b2b_supply_score,scaled_b2b_supply_percentile,scaled_b2b_supply_group
0,2018,20,Oaxaca,039,Heroica Ciudad de Huajuapan de León,20039,375.0,351.0,24.0,0.0,0.0,0.0,375.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
1,2018,15,México,120,Zumpango,15120,319.0,294.0,25.0,0.0,0.0,0.0,319.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
2,2018,09,Ciudad de México,009,Milpa Alta,09009,236.0,234.0,2.0,0.0,0.0,0.0,236.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
3,2018,14,Jalisco,008,Arandas,14008,187.0,176.0,11.0,0.0,0.0,0.0,187.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
4,2018,29,Tlaxcala,013,Huamantla,29013,174.0,163.0,11.0,0.0,0.0,0.0,174.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
5,2018,15,México,088,Tenancingo,15088,169.0,160.0,9.0,0.0,0.0,0.0,169.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
6,2018,15,México,101,Tianguistenco,15101,167.0,159.0,8.0,0.0,0.0,0.0,167.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
7,2018,14,Jalisco,015,Autlán de Navarro,14015,159.0,141.0,18.0,0.0,0.0,0.0,159.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
8,2018,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,30160,142.0,138.0,4.0,0.0,0.0,0.0,142.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
9,2018,07,Chiapas,017,Cintalapa de Figueroa,07017,136.0,120.0,16.0,0.0,0.0,0.0,136.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
10,2018,18,Nayarit,015,Santiago Ixcuintla,18015,132.0,126.0,6.0,0.0,0.0,0.0,132.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
11,2018,16,Michoacán de Ocampo,071,Puruándiro,16071,131.0,127.0,4.0,0.0,0.0,0.0,131.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
12,2018,29,Tlaxcala,044,Zacatelco,29044,129.0,123.0,6.0,0.0,0.0,0.0,129.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
13,2018,11,Guanajuato,046,Yuriria,11046,128.0,126.0,2.0,0.0,0.0,0.0,128.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
14,2018,15,México,092,Teotihuacán,15092,126.0,116.0,10.0,0.0,0.0,0.0,126.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
15,2018,12,Guerrero,057,Técpan de Galeana,12057,114.0,105.0,9.0,0.0,0.0,0.0,114.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
16,2018,30,Veracruz de Ignacio de la Llave,123,Pánuco,30123,112.0,101.0,11.0,0.0,0.0,0.0,112.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
17,2018,11,Guanajuato,004,Apaseo el Alto,11004,111.0,106.0,5.0,0.0,0.0,0.0,111.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
18,2018,14,Jalisco,083,Tala,14083,109.0,97.0,12.0,0.0,0.0,0.0,109.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
19,2018,21,Puebla,045,Chalchicomula de Sesma,21045,105.0,98.0,7.0,0.0,0.0,0.0,105.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
20,2018,11,Guanajuato,030,San Felipe,11030,104.0,101.0,3.0,0.0,0.0,0.0,104.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
21,2018,30,Veracruz de Ignacio de la Llave,109,Misantla,30109,100.0,94.0,6.0,0.0,0.0,0.0,100.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
22,2018,22,Querétaro,007,Ezequiel Montes,22007,99.0,96.0,3.0,0.0,0.0,0.0,99.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
23,2018,21,Puebla,094,Libres,21094,99.0,97.0,2.0,0.0,0.0,0.0,99.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
24,2018,13,Hidalgo,074,Tlaxcoapan,13074,98.0,92.0,6.0,0.0,0.0,0.0,98.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
25,2018,15,México,087,Temoaya,15087,97.0,94.0,3.0,0.0,0.0,0.0,97.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
26,2018,15,México,067,Otzolotepec,15067,89.0,87.0,2.0,0.0,0.0,0.0,89.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
27,2018,22,Querétaro,004,Cadereyta de Montes,22004,88.0,77.0,11.0,0.0,0.0,0.0,88.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
28,2018,07,Chiapas,107,Villa Corzo,07107,81.0,80.0,1.0,0.0,0.0,0.0,81.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
29,2018,14,Jalisco,035,Encarnación de Díaz,14035,80.0,76.0,4.0,0.0,0.0,0.0,80.0,1.0,0,1,0.0,0.354120,0.354120,Low scaled B2B supply
30,2023,14,Jalisco,008,Arandas,14008,219.0,200.0,19.0,0.0,0.0,0.0,219.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
31,2023,32,Zacatecas,020,Jerez,32020,163.0,151.0,12.0,0.0,0.0,0.0,163.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
32,2023,29,Tlaxcala,013,Huamantla,29013,158.0,145.0,13.0,0.0,0.0,0.0,158.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
33,2023,15,México,074,San Felipe del Progreso,15074,134.0,131.0,3.0,0.0,0.0,0.0,134.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
34,2023,07,Chiapas,017,Cintalapa de Figueroa,07017,129.0,114.0,15.0,0.0,0.0,0.0,129.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
35,2023,12,Guerrero,046,Ometepec,12046,127.0,119.0,8.0,0.0,0.0,0.0,127.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
36,2023,15,México,115,Xonacatlán,15115,120.0,116.0,4.0,0.0,0.0,0.0,120.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
37,2023,15,México,005,Almoloya de Juárez,15005,117.0,113.0,4.0,0.0,0.0,0.0,117.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
38,2023,16,Michoacán de Ocampo,071,Puruándiro,16071,115.0,107.0,8.0,0.0,0.0,0.0,115.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
39,2023,11,Guanajuato,046,Yuriria,11046,111.0,107.0,4.0,0.0,0.0,0.0,111.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
40,2023,15,México,110,Valle de Bravo,15110,111.0,96.0,15.0,0.0,0.0,0.0,111.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
41,2023,27,Tabasco,003,Centla,27003,107.0,89.0,18.0,0.0,0.0,0.0,107.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
42,2023,30,Veracruz de Ignacio de la Llave,123,Pánuco,30123,102.0,83.0,19.0,0.0,0.0,0.0,102.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
43,2023,08,Chihuahua,011,Camargo,08011,101.0,89.0,12.0,0.0,0.0,0.0,101.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
44,2023,11,Guanajuato,030,San Felipe,11030,100.0,89.0,11.0,0.0,0.0,0.0,100.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
45,2023,21,Puebla,094,Libres,21094,100.0,96.0,4.0,0.0,0.0,0.0,100.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
46,2023,13,Hidalgo,074,Tlaxcoapan,13074,94.0,88.0,6.0,0.0,0.0,0.0,94.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
47,2023,13,Hidalgo,029,Huichapan,13029,89.0,79.0,10.0,0.0,0.0,0.0,89.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
48,2023,11,Guanajuato,001,Abasolo,11001,88.0,79.0,9.0,0.0,0.0,0.0,88.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
49,2023,30,Veracruz de Ignacio de la Llave,045,Cosamaloapan de Carpio,30045,87.0,84.0,3.0,0.0,0.0,0.0,87.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
50,2023,30,Veracruz de Ignacio de la Llave,109,Misantla,30109,87.0,82.0,5.0,0.0,0.0,0.0,87.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
51,2023,12,Guerrero,057,Técpan de Galeana,12057,86.0,72.0,14.0,0.0,0.0,0.0,86.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
52,2023,15,México,067,Otzolotepec,15067,85.0,84.0,1.0,0.0,0.0,0.0,85.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
53,2023,11,Guanajuato,026,Romita,11026,85.0,77.0,8.0,0.0,0.0,0.0,85.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
54,2023,10,Durango,008,Guadalupe Victoria,10008,83.0,75.0,8.0,0.0,0.0,0.0,83.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
55,2023,32,Zacatecas,048,Tlaltenango de Sánchez Román,32048,80.0,74.0,6.0,0.0,0.0,0.0,80.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
56,2023,15,México,011,Atenco,15011,79.0,77.0,2.0,0.0,0.0,0.0,79.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
57,2023,15,México,040,Ixtapan de la Sal,15040,78.0,71.0,7.0,0.0,0.0,0.0,78.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
58,2023,14,Jalisco,046,Jalostotitlán,14046,77.0,74.0,3.0,0.0,0.0,0.0,77.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply
59,2023,13,Hidalgo,081,Zacualtipán de Ángeles,13081,74.0,69.0,5.0,0.0,0.0,0.0,74.0,1.0,0,1,0.0,0.341575,0.341575,Low scaled B2B supply

VALIDACIÓN RÁPIDA
====================================================================================================
Filas diagnosticadas: 4530
Missing b2b_scaled_capacity_proxy: 0
Missing scaled_b2b_supply_score: 0
Años: [np.int64(2018), np.int64(2023)]

In [ ]:
# ============================================================
# 08. DIAGNÓSTICO DEL SCORE DEFINITIVO DE OPORTUNIDAD
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
#
# NO GUARDA ARCHIVOS.
#
# Objetivo:
# Construir en memoria:
# 1. industrial_demand_score
# 2. b2b_supply_score
# 3. scaled_b2b_supply_score
# 4. industrial_b2b_opportunity_score
# 5. opportunity_category
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

print("Input path:")
print(input_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Definir variables y pesos
# ------------------------------------------------------------

# Demanda industrial
demand_features = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

demand_weights = {
    "total_manufacturing_establishments": 0.25,
    "total_manufacturing_employment": 0.20,
    "total_manufacturing_value_added": 0.25,
    "total_manufacturing_income": 0.20,
    "total_manufacturing_investment": 0.10
}

# Oferta B2B general
# No usamos denue_b2b_support_establishments para evitar doble conteo.
b2b_supply_features = [
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes"
]

b2b_supply_weights = {
    "denue_logistics_storage_establishments": 0.35,
    "denue_professional_technical_establishments": 0.25,
    "denue_business_support_establishments": 0.20,
    "denue_b2b_support_scian_classes": 0.20
}

# Oferta B2B escalada
scaled_features = [
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "denue_b2b_support_establishments",
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments"
]

required_cols = (
    ["year", "entidad_id", "entidad_name", "municipio_id", "municipio_name", "geo_key"]
    + demand_features
    + b2b_supply_features
    + scaled_features
)

missing_cols = [col for col in required_cols if col not in df.columns]

if missing_cols:
    raise ValueError(f"Faltan columnas necesarias: {missing_cols}")

if not np.isclose(sum(demand_weights.values()), 1.0):
    raise ValueError("Los pesos de demanda no suman 1.")

if not np.isclose(sum(b2b_supply_weights.values()), 1.0):
    raise ValueError("Los pesos de oferta B2B no suman 1.")


# ------------------------------------------------------------
# 4. Convertir variables a numéricas y validar missing
# ------------------------------------------------------------

numeric_cols = list(set(demand_features + b2b_supply_features + scaled_features))

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_numeric = df[numeric_cols].isna().sum()

print("\nMissing en variables usadas:")
print(missing_numeric[missing_numeric > 0])

if missing_numeric.sum() > 0:
    raise ValueError(
        "Hay missing en variables necesarias. "
        "Revisa que estés usando 08_modeling_base_complete_cases.csv."
    )


# ------------------------------------------------------------
# 5. Industrial demand score
# ------------------------------------------------------------

for col in demand_features:
    percentile_col = f"{col}_demand_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["industrial_demand_score"] = 0.0

for col, weight in demand_weights.items():
    df["industrial_demand_score"] += (
        df[f"{col}_demand_percentile"] * weight
    )

df["industrial_demand_percentile"] = (
    df
    .groupby("year")["industrial_demand_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 6. B2B supply score general
# ------------------------------------------------------------

for col in b2b_supply_features:
    percentile_col = f"{col}_b2b_supply_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["b2b_supply_score"] = 0.0

for col, weight in b2b_supply_weights.items():
    df["b2b_supply_score"] += (
        df[f"{col}_b2b_supply_percentile"] * weight
    )

df["b2b_supply_percentile"] = (
    df
    .groupby("year")["b2b_supply_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 7. Scaled B2B supply score
# ------------------------------------------------------------

medium_expected_workers = 65.5
large_expected_workers = 150

df["b2b_scaled_capacity_proxy"] = (
    medium_expected_workers * df["denue_b2b_medium_establishments"]
    + large_expected_workers * df["denue_b2b_large_establishments"]
)

df["scaled_b2b_supply_score"] = (
    df
    .groupby("year")["b2b_scaled_capacity_proxy"]
    .rank(pct=True, method="average")
)

df["scaled_b2b_supply_percentile"] = df["scaled_b2b_supply_score"]

# Variables auxiliares de atomización
df["b2b_micro_small_establishments"] = (
    df["denue_b2b_micro_establishments"]
    + df["denue_b2b_small_establishments"]
)

df["b2b_micro_small_share"] = np.where(
    df["denue_b2b_support_establishments"] > 0,
    df["b2b_micro_small_establishments"] / df["denue_b2b_support_establishments"],
    np.nan
)

df["only_micro_small_b2b_supply"] = (
    (df["denue_b2b_support_establishments"] > 0) &
    (df["denue_b2b_medium_large_establishments"] == 0)
).astype(int)


# ------------------------------------------------------------
# 8. Score definitivo de oportunidad
# ------------------------------------------------------------

df["industrial_b2b_opportunity_score"] = (
    df["industrial_demand_percentile"]
    * (1 - df["scaled_b2b_supply_percentile"])
)

df["industrial_b2b_opportunity_percentile"] = (
    df
    .groupby("year")["industrial_b2b_opportunity_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 9. Categorías interpretativas
# ------------------------------------------------------------

def classify_opportunity(row):
    demand_p = row["industrial_demand_percentile"]
    scaled_p = row["scaled_b2b_supply_percentile"]

    if demand_p >= 0.90 and scaled_p < 0.50:
        return "Top priority opportunity"

    elif demand_p >= 0.75 and scaled_p < 0.50:
        return "Priority opportunity"

    elif demand_p >= 0.75 and scaled_p >= 0.75:
        return "Industrial ecosystem hub"

    elif demand_p >= 0.50 and scaled_p < 0.75:
        return "Developing industrial market"

    elif demand_p < 0.50 and scaled_p >= 0.75:
        return "Service hub, lower industrial demand"

    elif demand_p < 0.50 and scaled_p < 0.75:
        return "Lower initial priority"

    else:
        return "Intermediate / monitor"


df["industrial_b2b_opportunity_category"] = (
    df
    .apply(classify_opportunity, axis=1)
)


# ------------------------------------------------------------
# 10. Tablas de revisión
# ------------------------------------------------------------

review_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",

    # Scores principales
    "industrial_demand_score",
    "industrial_demand_percentile",
    "b2b_supply_score",
    "b2b_supply_percentile",
    "b2b_scaled_capacity_proxy",
    "scaled_b2b_supply_score",
    "scaled_b2b_supply_percentile",
    "industrial_b2b_opportunity_score",
    "industrial_b2b_opportunity_percentile",
    "industrial_b2b_opportunity_category",

    # Variables manufactureras
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",

    # Variables B2B
    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "b2b_micro_small_share",
    "only_micro_small_b2b_supply"
]

score_diagnostic = df[review_cols].copy()


# Ranking principal de oportunidades
priority_categories = [
    "Top priority opportunity",
    "Priority opportunity",
    "Developing industrial market"
]

opportunity_ranking = (
    score_diagnostic[
        score_diagnostic["industrial_b2b_opportunity_category"]
        .isin(priority_categories)
    ]
    .sort_values(
        [
            "year",
            "industrial_b2b_opportunity_category",
            "industrial_b2b_opportunity_score"
        ],
        ascending=[True, True, False]
    )
    .reset_index(drop=True)
)

# Top opportunity por score, sin filtrar categoría
top_opportunity_score = (
    score_diagnostic
    .sort_values(
        ["year", "industrial_b2b_opportunity_score"],
        ascending=[True, False]
    )
    .groupby("year")
    .head(40)
    .reset_index(drop=True)
)

# Hubs consolidados
ecosystem_hubs = (
    score_diagnostic[
        score_diagnostic["industrial_b2b_opportunity_category"]
        == "Industrial ecosystem hub"
    ]
    .sort_values(
        ["year", "industrial_demand_percentile", "scaled_b2b_supply_percentile"],
        ascending=[True, False, False]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. Resumen por categoría
# ------------------------------------------------------------

category_summary = (
    score_diagnostic
    .groupby(["year", "industrial_b2b_opportunity_category"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_municipalities=("geo_key", "nunique"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_scaled_b2b_supply_percentile=("scaled_b2b_supply_percentile", "mean"),
        avg_opportunity_score=("industrial_b2b_opportunity_score", "mean"),
        avg_manufacturing_establishments=("total_manufacturing_establishments", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean"),
        avg_micro_small_share=("b2b_micro_small_share", "mean")
    )
    .reset_index()
)

category_summary["share_municipality_years"] = (
    category_summary["n_municipality_years"]
    / category_summary.groupby("year")["n_municipality_years"].transform("sum")
)

category_order = {
    "Top priority opportunity": 1,
    "Priority opportunity": 2,
    "Developing industrial market": 3,
    "Industrial ecosystem hub": 4,
    "Service hub, lower industrial demand": 5,
    "Lower initial priority": 6,
    "Intermediate / monitor": 7
}

category_summary["category_order"] = (
    category_summary["industrial_b2b_opportunity_category"]
    .map(category_order)
)

category_summary = (
    category_summary
    .sort_values(["year", "category_order"])
    .drop(columns=["category_order"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 12. Mostrar resultados
# ------------------------------------------------------------

print("\nFÓRMULA DEL SCORE DEFINITIVO")
print("=" * 100)
print("industrial_b2b_opportunity_score = industrial_demand_percentile * (1 - scaled_b2b_supply_percentile)")
print(f"Medium expected workers used for scaled proxy: {medium_expected_workers}")
print(f"Large expected workers used for scaled proxy: {large_expected_workers}")

print("\nRESUMEN POR CATEGORÍA")
print("=" * 100)
display(category_summary)

print("\nRANKING PRINCIPAL DE OPORTUNIDADES")
print("=" * 100)
display(opportunity_ranking.head(50))

print("\nTOP POR SCORE DE OPORTUNIDAD, SIN FILTRAR CATEGORÍA")
print("=" * 100)
display(top_opportunity_score.head(50))

print("\nINDUSTRIAL ECOSYSTEM HUBS")
print("=" * 100)
display(ecosystem_hubs.head(40))

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas diagnosticadas:", len(score_diagnostic))
print("Missing industrial_b2b_opportunity_score:", score_diagnostic["industrial_b2b_opportunity_score"].isna().sum())
print("Missing category:", score_diagnostic["industrial_b2b_opportunity_category"].isna().sum())
print("Años:", sorted(score_diagnostic["year"].dropna().unique()))

Google Drive ya está disponible en: /content/drive/MyDrive
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Base cargada:
Filas: 4,530
Columnas: 54

Missing en variables usadas:
Series([], dtype: int64)

FÓRMULA DEL SCORE DEFINITIVO
====================================================================================================
industrial_b2b_opportunity_score = industrial_demand_percentile * (1 - scaled_b2b_supply_percentile)
Medium expected workers used for scaled proxy: 65.5
Large expected workers used for scaled proxy: 150

RESUMEN POR CATEGORÍA
====================================================================================================

,year,industrial_b2b_opportunity_category,n_municipality_years,n_municipalities,avg_industrial_demand_percentile,avg_b2b_supply_percentile,avg_scaled_b2b_supply_percentile,avg_opportunity_score,avg_manufacturing_establishments,avg_manufacturing_employment,avg_b2b_total,avg_b2b_medium_large,avg_micro_small_share,share_municipality_years
0,2018,Top priority opportunity,6,6,0.932146,0.815293,0.354120,0.602054,539.666667,5892.000000,128.666667,0.000000,1.000000,0.002673
1,2018,Priority opportunity,139,139,0.812261,0.659260,0.354120,0.524623,381.913669,1674.302158,52.316547,0.000000,1.000000,0.061915
2,2018,Developing industrial market,525,525,0.644991,0.582144,0.457164,0.341398,200.024762,711.274286,34.432381,0.260952,0.991627,0.233853
3,2018,Industrial ecosystem hub,355,355,0.904461,0.899497,0.911278,0.077799,1011.135211,16040.160563,584.887324,36.912676,0.948508,0.158129
4,2018,"Service hub, lower industrial demand",19,19,0.357942,0.574036,0.821240,0.062593,46.421053,108.473684,22.631579,1.789474,0.872954,0.008463
5,2018,Lower initial priority,1103,1103,0.248254,0.286549,0.370946,0.154818,36.453309,76.639166,6.628286,0.042611,0.994219,0.491314
6,2018,Intermediate / monitor,98,98,0.654836,0.760761,0.850816,0.097166,179.040816,651.489796,67.102041,2.816327,0.941790,0.043653
7,2023,Top priority opportunity,10,10,0.930547,0.678096,0.341575,0.612695,674.100000,7372.900000,74.700000,0.000000,1.000000,0.004376
8,2023,Priority opportunity,124,124,0.812677,0.653739,0.341575,0.535087,437.725806,1765.056452,42.911290,0.000000,1.000000,0.054267
9,2023,Developing industrial market,525,525,0.643333,0.583001,0.459612,0.340244,208.718095,756.152381,31.074286,0.304762,0.989438,0.229759
10,2023,Industrial ecosystem hub,378,378,0.900608,0.898029,0.908808,0.079520,1042.875661,16749.428571,511.589947,40.015873,0.937574,0.165427
11,2023,"Service hub, lower industrial demand",31,31,0.377716,0.534658,0.822143,0.066659,51.419355,135.870968,15.225806,1.741935,0.813279,0.013567
12,2023,Lower initial priority,1111,1111,0.246549,0.282859,0.359006,0.156315,41.867687,86.802880,5.952295,0.045005,0.991986,0.486214
13,2023,Intermediate / monitor,106,106,0.652054,0.743338,0.830763,0.110228,194.745283,631.613208,52.933962,2.566038,0.930765,0.046389

RANKING PRINCIPAL DE OPORTUNIDADES
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,industrial_demand_score,industrial_demand_percentile,b2b_supply_score,b2b_supply_percentile,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply
0,2018,12,Guerrero,034,Huitzuco de los Figueroa,12034,0.722361,0.749220,0.770880,0.784410,...,57.0,10.0,13.0,34.0,15.0,0.0,0.0,0.0,1.0,1
1,2018,21,Puebla,170,Tepeyahualco,21170,0.721381,0.748330,0.177049,0.159911,...,4.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,1.0,1
2,2018,13,Hidalgo,082,Zapotlán de Juárez,13082,0.721347,0.747884,0.557127,0.571492,...,29.0,2.0,4.0,23.0,6.0,0.0,0.0,0.0,1.0,1
3,2018,20,Oaxaca,546,Teotitlán del Valle,20546,0.721314,0.747439,0.310535,0.319154,...,8.0,0.0,2.0,6.0,3.0,0.0,0.0,0.0,1.0,1
4,2018,12,Guerrero,042,Mártir de Cuilapan,12042,0.720412,0.746548,0.541849,0.554120,...,16.0,4.0,2.0,10.0,6.0,0.0,0.0,0.0,1.0,1
5,2018,07,Chiapas,003,Acapetahua,07003,0.720390,0.746102,0.640991,0.656570,...,31.0,3.0,16.0,12.0,10.0,0.0,0.0,0.0,1.0,1
6,2018,20,Oaxaca,021,Cosolapa,20021,0.719588,0.745212,0.566169,0.583073,...,23.0,2.0,10.0,11.0,6.0,0.0,0.0,0.0,1.0,1
7,2018,14,Jalisco,123,Zapotlán del Rey,14123,0.719220,0.744766,0.620256,0.640535,...,21.0,10.0,5.0,6.0,7.0,0.0,0.0,0.0,1.0,1
8,2018,30,Veracruz de Ignacio de la Llave,047,Coscomatepec,30047,0.716292,0.742094,0.623497,0.644543,...,34.0,2.0,8.0,24.0,11.0,0.0,0.0,0.0,1.0,1
9,2018,21,Puebla,045,Chalchicomula de Sesma,21045,0.713408,0.740757,0.811370,0.821826,...,105.0,8.0,50.0,47.0,18.0,0.0,0.0,0.0,1.0,1
10,2018,15,México,015,Atlautla,15015,0.713073,0.740312,0.646381,0.663252,...,46.0,4.0,6.0,36.0,7.0,0.0,0.0,0.0,1.0,1
11,2018,20,Oaxaca,441,Santa María Xadani,20441,0.712895,0.739866,0.163953,0.132962,...,3.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,1
12,2018,08,Chihuahua,062,Saucillo,08062,0.712661,0.739421,0.718708,0.736080,...,35.0,10.0,14.0,11.0,12.0,0.0,0.0,0.0,1.0,1
13,2018,16,Michoacán de Ocampo,012,Buenavista,16012,0.712428,0.738976,0.747049,0.763474,...,49.0,7.0,16.0,26.0,14.0,0.0,0.0,0.0,1.0,1
14,2018,29,Tlaxcala,008,Cuapiaxtla,29008,0.712261,0.738530,0.395780,0.414031,...,15.0,0.0,4.0,11.0,5.0,0.0,0.0,0.0,1.0,1
15,2018,31,Yucatán,056,Oxkutzcab,31056,0.712149,0.738085,0.741949,0.756347,...,46.0,6.0,20.0,20.0,17.0,0.0,0.0,0.0,1.0,1
16,2018,21,Puebla,189,Tochtepec,21189,0.711693,0.737194,0.499165,0.513586,...,26.0,1.0,4.0,21.0,5.0,0.0,0.0,0.0,1.0,1
17,2018,12,Guerrero,057,Técpan de Galeana,12057,0.711581,0.736748,0.872483,0.881514,...,114.0,31.0,31.0,52.0,28.0,0.0,0.0,0.0,1.0,1
18,2018,32,Zacatecas,044,Tabasco,32044,0.710757,0.736303,0.670122,0.686414,...,26.0,6.0,9.0,11.0,11.0,0.0,0.0,0.0,1.0,1
19,2018,16,Michoacán de Ocampo,100,Tzintzuntzan,16100,0.710590,0.735857,0.323808,0.336080,...,10.0,0.0,2.0,8.0,3.0,0.0,0.0,0.0,1.0,1
20,2018,16,Michoacán de Ocampo,055,Múgica,16055,0.710523,0.735412,0.780857,0.791091,...,65.0,8.0,26.0,31.0,16.0,0.0,0.0,0.0,1.0,1
21,2018,21,Puebla,171,Tepeyahualco de Cuauhtémoc,21171,0.709287,0.733630,0.278508,0.282183,...,5.0,0.0,2.0,3.0,3.0,0.0,0.0,0.0,1.0,1
22,2018,15,México,012,Atizapán,15012,0.708898,0.732294,0.482238,0.494209,...,16.0,1.0,4.0,11.0,6.0,0.0,0.0,0.0,1.0,1
23,2018,16,Michoacán de Ocampo,105,Vista Hermosa,16105,0.708719,0.731849,0.733419,0.751002,...,38.0,17.0,7.0,14.0,13.0,0.0,0.0,0.0,1.0,1
24,2018,18,Nayarit,018,Tuxpan,18018,0.708619,0.731403,0.772996,0.786637,...,53.0,9.0,17.0,27.0,17.0,0.0,0.0,0.0,1.0,1
25,2018,14,Jalisco,024,Cocula,14024,0.708541,0.730958,0.686058,0.702450,...,41.0,3.0,21.0,17.0,15.0,0.0,0.0,0.0,1.0,1
26,2018,16,Michoacán de Ocampo,071,Puruándiro,16071,0.708207,0.729621,0.872706,0.881960,...,131.0,19.0,51.0,61.0,28.0,0.0,0.0,0.0,1.0,1
27,2018,29,Tlaxcala,053,San Juan Huactzinco,29053,0.707483,0.728731,0.341737,0.351893,...,9.0,0.0,3.0,6.0,4.0,0.0,0.0,0.0,1.0,1
28,2018,17,Morelos,003,Axochiapan,17003,0.707428,0.728285,0.806682,0.815590,...,80.0,12.0,21.0,47.0,17.0,0.0,0.0,0.0,1.0,1
29,2018,15,México,028,Chiautla,15028,0.707327,0.727617,0.590490,0.607127,...,39.0,1.0,12.0,26.0,10.0,0.0,0.0,0.0,1.0,1
30,2018,12,Guerrero,071,Xochistlahuaca,12071,0.707327,0.727617,0.371470,0.391537,...,14.0,0.0,2.0,12.0,5.0,0.0,0.0,0.0,1.0,1
31,2018,31,Yucatán,058,Peto,31058,0.707283,0.726949,0.696927,0.712249,...,34.0,7.0,18.0,9.0,12.0,0.0,0.0,0.0,1.0,1
32,2018,22,Querétaro,008,Huimilpan,22008,0.706069,0.725167,0.497884,0.512249,...,11.0,2.0,5.0,4.0,7.0,0.0,0.0,0.0,1.0,1
33,2018,08,Chihuahua,040,Madera,08040,0.704577,0.724276,0.681437,0.700223,...,31.0,6.0,9.0,16.0,10.0,0.0,0.0,0.0,1.0,1
34,2018,14,Jalisco,116,Villa Hidalgo,14116,0.703196,0.723831,0.768898,0.782183,...,51.0,10.0,25.0,16.0,17.0,0.0,0.0,0.0,1.0,1
35,2018,14,Jalisco,025,Colotlán,14025,0.702572,0.723385,0.762405,0.777283,...,61.0,6.0,32.0,23.0,18.0,0.0,0.0,0.0,1.0,1
36,2018,14,Jalisco,036,Etzatlán,14036,0.700612,0.722049,0.717695,0.735412,...,39.0,5.0,19.0,15.0,17.0,0.0,0.0,0.0,1.0,1
37,2018,20,Oaxaca,126,San Cristóbal Amatlán,20126,0.700512,0.721604,0.199944,0.188641,...,4.0,0.0,0.0,4.0,2.0,0.0,0.0,0.0,1.0,1
38,2018,31,Yucatán,032,Espita,31032,0.700301,0.721158,0.475913,0.489532,...,13.0,2.0,3.0,8.0,4.0,0.0,0.0,0.0,1.0,1
39,2018,28,Tamaulipas,012,González,28012,0.699477,0.719822,0.788641,0.798664,...,55.0,15.0,20.0,20.0,17.0,0.0,0.0,0.0,1.0,1
40,2018,31,Yucatán,093,Tixkokob,31093,0.696069,0.718040,0.537216,0.550111,...,18.0,2.0,5.0,11.0,6.0,0.0,0.0,0.0,1.0,1
41,2018,24,San Luis Potosí,025,Salinas,24025,0.695189,0.716704,0.713151,0.730067,...,42.0,5.0,14.0,23.0,13.0,0.0,0.0,0.0,1.0,1
42,2018,21,Puebla,094,Libres,21094,0.694599,0.716258,0.810412,0.818708,...,99.0,8.0,36.0,55.0,19.0,0.0,0.0,0.0,1.0,1
43,2018,14,Jalisco,033,Degollado,14033,0.694065,0.715813,0.730078,0.746993,...,46.0,6.0,24.0,16.0,14.0,0.0,0.0,0.0,1.0,1
44,2018,07,Chiapas,051,Mapastepec,07051,0.692695,0.714922,0.804777,0.813808,...,71.0,13.0,19.0,39.0,18.0,0.0,0.0,0.0,1.0,1
45,2018,21,Puebla,129,San José Miahuatlán,21129,0.690824,0.714031,0.478096,0.489978,...,15.0,1.0,4.0,10.0,6.0,0.0,0.0,0.0,1.0,1
46,2018,21,Puebla,205,Yehualtepec,21205,0.690245,0.713586,0.551626,0.566592,...,30.0,1.0,9.0,20.0,7.0,0.0,0.0,0.0,1.0,1
47,2018,14,Jalisco,102,Tonaya,14102,0.689889,0.712249,0.572617,0.590646,...,14.0,5.0,2.0,7.0,11.0,0.0,0.0,0.0,1.0,1
48,2018,08,Chihuahua,005,Ascensión,08005,0.689733,0.711804,0.730891,0.748330,...,36.0,17.0,10.0,9.0,14.0,0.0,0.0,0.0,1.0,1
49,2018,31,Yucatán,075,Teabo,31075,0.687739,0.709577,0.229120,0.223385,...,2.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,1

TOP POR SCORE DE OPORTUNIDAD, SIN FILTRAR CATEGORÍA
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,industrial_demand_score,industrial_demand_percentile,b2b_supply_score,b2b_supply_percentile,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply
0,2018,15,México,101,Tianguistenco,15101,0.953296,0.968374,0.806013,0.814699,...,167.0,5.0,57.0,105.0,21.0,0.0,0.0,0.0,1.0,1
1,2018,29,Tlaxcala,013,Huamantla,29013,0.938140,0.956793,0.879866,0.891314,...,174.0,17.0,52.0,105.0,29.0,0.0,0.0,0.0,1.0,1
2,2018,14,Jalisco,008,Arandas,14008,0.911759,0.936303,0.846247,0.854343,...,187.0,8.0,108.0,71.0,28.0,0.0,0.0,0.0,1.0,1
3,2018,11,Guanajuato,004,Apaseo el Alto,11004,0.893185,0.918486,0.853207,0.861024,...,111.0,16.0,42.0,53.0,24.0,0.0,0.0,0.0,1.0,1
4,2018,31,Yucatán,041,Kanasín,31041,0.880267,0.909131,0.751269,0.766592,...,57.0,12.0,5.0,40.0,17.0,0.0,0.0,0.0,1.0,1
5,2018,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,0.875657,0.903786,0.686448,0.703786,...,76.0,3.0,9.0,64.0,12.0,0.0,0.0,0.0,1.0,1
6,2018,13,Hidalgo,081,Zacualtipán de Ángeles,13081,0.869510,0.899332,0.752116,0.767929,...,71.0,5.0,21.0,45.0,15.0,0.0,0.0,0.0,1.0,1
7,2018,31,Yucatán,038,Hunucmá,31038,0.868976,0.897550,0.659878,0.678396,...,41.0,3.0,16.0,22.0,9.0,0.0,0.0,0.0,1.0,1
8,2018,14,Jalisco,083,Tala,14083,0.868029,0.896659,0.843630,0.852116,...,109.0,14.0,37.0,58.0,22.0,0.0,0.0,0.0,1.0,1
9,2018,04,Campeche,001,Calkiní,04001,0.864120,0.893987,0.787661,0.797773,...,73.0,10.0,14.0,49.0,17.0,0.0,0.0,0.0,1.0,1
10,2018,15,México,120,Zumpango,15120,0.858486,0.891314,0.891169,0.901559,...,319.0,16.0,128.0,175.0,26.0,0.0,0.0,0.0,1.0,1
11,2018,22,Querétaro,007,Ezequiel Montes,22007,0.857038,0.889532,0.827316,0.838307,...,99.0,12.0,27.0,60.0,21.0,0.0,0.0,0.0,1.0,1
12,2018,21,Puebla,177,Tlacotepec de Benito Juárez,21177,0.856013,0.889087,0.739811,0.754566,...,50.0,7.0,9.0,34.0,15.0,0.0,0.0,0.0,1.0,1
13,2018,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,30160,0.849276,0.882405,0.870657,0.878842,...,142.0,29.0,34.0,79.0,21.0,0.0,0.0,0.0,1.0,1
14,2018,21,Puebla,161,Tepanco de López,21161,0.841347,0.874388,0.602884,0.621826,...,26.0,6.0,2.0,18.0,7.0,0.0,0.0,0.0,1.0,1
15,2018,29,Tlaxcala,034,Tlaxco,29034,0.840278,0.872606,0.736570,0.753229,...,43.0,6.0,13.0,24.0,17.0,0.0,0.0,0.0,1.0,1
16,2018,09,Ciudad de México,009,Milpa Alta,09009,0.840278,0.872160,0.831670,0.841871,...,236.0,7.0,58.0,171.0,20.0,0.0,0.0,0.0,1.0,1
17,2018,29,Tlaxcala,015,Ixtacuixtla de Mariano Matamoros,29015,0.838129,0.870824,0.536192,0.547439,...,54.0,0.0,19.0,35.0,10.0,0.0,0.0,0.0,1.0,1
18,2018,14,Jalisco,015,Autlán de Navarro,14015,0.837506,0.869933,0.868263,0.874388,...,159.0,13.0,92.0,54.0,33.0,0.0,0.0,0.0,1.0,1
19,2018,21,Puebla,013,Altepexi,21013,0.837082,0.869042,0.543296,0.556347,...,34.0,1.0,7.0,26.0,6.0,0.0,0.0,0.0,1.0,1
20,2018,14,Jalisco,016,Ayotlán,14016,0.835713,0.867706,0.785891,0.795991,...,78.0,7.0,37.0,34.0,17.0,0.0,0.0,0.0,1.0,1
21,2018,31,Yucatán,079,Tekax,31079,0.834143,0.865479,0.686091,0.702895,...,61.0,2.0,23.0,36.0,15.0,0.0,0.0,0.0,1.0,1
22,2018,16,Michoacán de Ocampo,073,Quiroga,16073,0.830869,0.864143,0.716192,0.732739,...,55.0,4.0,14.0,37.0,14.0,0.0,0.0,0.0,1.0,1
23,2018,12,Guerrero,074,Zitlala,12074,0.828441,0.862806,0.346102,0.365256,...,12.0,0.0,3.0,9.0,3.0,0.0,0.0,0.0,1.0,1
24,2018,29,Tlaxcala,019,Tepetitla de Lardizábal,29019,0.828163,0.862361,0.475022,0.488196,...,38.0,0.0,6.0,32.0,7.0,0.0,0.0,0.0,1.0,1
25,2018,31,Yucatán,080,Tekit,31080,0.827439,0.861470,0.317394,0.328508,...,7.0,0.0,2.0,5.0,4.0,0.0,0.0,0.0,1.0,1
26,2018,29,Tlaxcala,042,Xicohtzinco,29042,0.821114,0.858797,0.608731,0.627617,...,26.0,3.0,5.0,18.0,9.0,0.0,0.0,0.0,1.0,1
27,2018,29,Tlaxcala,059,Santa Cruz Quilehtla,29059,0.820067,0.858352,0.421849,0.438753,...,12.0,1.0,2.0,9.0,4.0,0.0,0.0,0.0,1.0,1
28,2018,11,Guanajuato,018,Jaral del Progreso,11018,0.820011,0.857461,0.763073,0.777728,...,51.0,8.0,16.0,27.0,16.0,0.0,0.0,0.0,1.0,1
29,2018,16,Michoacán de Ocampo,058,Nuevo Parangaricutiro,16058,0.817227,0.855234,0.652361,0.668597,...,46.0,2.0,17.0,27.0,11.0,0.0,0.0,0.0,1.0,1
30,2018,16,Michoacán de Ocampo,056,Nahuatzen,16056,0.817138,0.854788,0.488864,0.504677,...,21.0,1.0,3.0,17.0,6.0,0.0,0.0,0.0,1.0,1
31,2018,14,Jalisco,125,San Ignacio Cerro Gordo,14125,0.816537,0.853898,0.643051,0.658797,...,26.0,4.0,12.0,10.0,10.0,0.0,0.0,0.0,1.0,1
32,2018,21,Puebla,149,Santiago Miahuatlán,21149,0.815056,0.852116,0.464655,0.480178,...,17.0,1.0,2.0,14.0,6.0,0.0,0.0,0.0,1.0,1
33,2018,15,México,019,Capulhuac,15019,0.812996,0.849443,0.726637,0.743875,...,78.0,3.0,21.0,54.0,17.0,0.0,0.0,0.0,1.0,1
34,2018,08,Chihuahua,045,Meoqui,08045,0.812862,0.848998,0.797082,0.806236,...,55.0,16.0,19.0,20.0,20.0,0.0,0.0,0.0,1.0,1
35,2018,14,Jalisco,035,Encarnación de Díaz,14035,0.811548,0.847661,0.810423,0.819599,...,80.0,9.0,40.0,31.0,22.0,0.0,0.0,0.0,1.0,1
36,2018,21,Puebla,125,San Gregorio Atzompa,21125,0.811437,0.847216,0.508040,0.519599,...,13.0,2.0,5.0,6.0,6.0,0.0,0.0,0.0,1.0,1
37,2018,11,Guanajuato,046,Yuriria,11046,0.809688,0.844989,0.868708,0.874833,...,128.0,18.0,58.0,52.0,26.0,0.0,0.0,0.0,1.0,1
38,2018,31,Yucatán,089,Ticul,31089,0.807795,0.842762,0.757149,0.773719,...,69.0,5.0,33.0,31.0,16.0,0.0,0.0,0.0,1.0,1
39,2018,13,Hidalgo,056,Santiago Tulantepec de Lugo Guerrero,13056,0.807138,0.842316,0.560278,0.576392,...,34.0,1.0,6.0,27.0,9.0,0.0,0.0,0.0,1.0,1
40,2023,29,Tlaxcala,013,Huamantla,29013,0.939311,0.958425,0.882801,0.892779,...,158.0,17.0,58.0,83.0,32.0,0.0,0.0,0.0,1.0,1
41,2023,24,San Luis Potosí,059,Villa de Pozos,24059,0.936258,0.957987,0.101127,0.028665,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
42,2023,31,Yucatán,041,Kanasín,31041,0.919387,0.945733,0.833063,0.844201,...,68.0,20.0,19.0,29.0,27.0,0.0,0.0,0.0,1.0,1
43,2023,14,Jalisco,008,Arandas,14008,0.919354,0.945295,0.873753,0.884902,...,219.0,12.0,151.0,56.0,31.0,0.0,0.0,0.0,1.0,1
44,2023,29,Tlaxcala,041,Papalotla de Xicohténcatl,29041,0.916554,0.941357,0.700842,0.720788,...,36.0,5.0,14.0,17.0,12.0,0.0,0.0,0.0,1.0,1
45,2023,29,Tlaxcala,028,Teolocholco,29028,0.884442,0.915974,0.616816,0.637199,...,43.0,1.0,14.0,28.0,13.0,0.0,0.0,0.0,1.0,1
46,2023,21,Puebla,010,Ajalpan,21010,0.882823,0.914661,0.733042,0.751422,...,63.0,4.0,21.0,38.0,14.0,0.0,0.0,0.0,1.0,1
47,2023,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,0.872954,0.909847,0.668425,0.683589,...,63.0,2.0,13.0,48.0,13.0,0.0,0.0,0.0,1.0,1
48,2023,29,Tlaxcala,015,Ixtacuixtla de Mariano Matamoros,29015,0.871455,0.908972,0.530547,0.546171,...,44.0,0.0,18.0,26.0,10.0,0.0,0.0,0.0,1.0,1
49,2023,30,Veracruz de Ignacio de la Llave,207,Tres Valles,30207,0.868578,0.907221,0.775799,0.791247,...,53.0,7.0,27.0,19.0,22.0,0.0,0.0,0.0,1.0,1

INDUSTRIAL ECOSYSTEM HUBS
====================================================================================================

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,industrial_demand_score,industrial_demand_percentile,b2b_supply_score,b2b_supply_percentile,...,denue_b2b_support_establishments,denue_logistics_storage_establishments,denue_professional_technical_establishments,denue_business_support_establishments,denue_b2b_support_scian_classes,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply
0,2018,15,México,106,Toluca,15106,0.997305,1.000000,0.990802,0.992428,...,2404.0,311.0,885.0,1208.0,92.0,75.0,71.0,146.0,0.939268,0
1,2018,24,San Luis Potosí,028,San Luis Potosí,24028,0.997127,0.999555,0.995278,0.996882,...,3054.0,486.0,1448.0,1120.0,99.0,125.0,89.0,214.0,0.929928,0
2,2018,02,Baja California,004,Tijuana,02004,0.996815,0.999109,0.998352,0.999555,...,4275.0,782.0,1905.0,1588.0,105.0,158.0,80.0,238.0,0.944327,0
3,2018,14,Jalisco,039,Guadalajara,14039,0.995345,0.998664,0.999733,1.000000,...,7008.0,817.0,3751.0,2440.0,110.0,294.0,161.0,455.0,0.935074,0
4,2018,22,Querétaro,014,Querétaro,22014,0.995122,0.998218,0.996080,0.997327,...,3543.0,427.0,1809.0,1307.0,103.0,157.0,102.0,259.0,0.926898,0
5,2018,01,Aguascalientes,001,Aguascalientes,01001,0.995056,0.997773,0.994098,0.995546,...,2938.0,352.0,1395.0,1191.0,99.0,99.0,41.0,140.0,0.952349,0
6,2018,14,Jalisco,120,Zapopan,14120,0.994076,0.997327,0.993898,0.995100,...,2728.0,334.0,1177.0,1217.0,101.0,127.0,63.0,190.0,0.930352,0
7,2018,19,Nuevo León,039,Monterrey,19039,0.993964,0.996882,0.997973,0.998664,...,4737.0,627.0,2543.0,1567.0,102.0,319.0,218.0,537.0,0.886637,0
8,2018,08,Chihuahua,037,Juárez,08037,0.993853,0.996437,0.992160,0.993764,...,2135.0,553.0,799.0,783.0,93.0,130.0,67.0,197.0,0.907728,0
9,2018,05,Coahuila de Zaragoza,030,Saltillo,05030,0.993831,0.995991,0.985089,0.987528,...,1608.0,240.0,712.0,656.0,86.0,70.0,46.0,116.0,0.927861,0
10,2018,11,Guanajuato,020,León,11020,0.992138,0.995546,0.996526,0.997773,...,4220.0,539.0,1837.0,1844.0,98.0,132.0,100.0,232.0,0.945024,0
11,2018,26,Sonora,030,Hermosillo,26030,0.991938,0.995100,0.991425,0.993318,...,2256.0,346.0,1283.0,627.0,97.0,105.0,67.0,172.0,0.923759,0
12,2018,15,México,033,Ecatepec de Morelos,15033,0.991292,0.994655,0.983408,0.985746,...,2562.0,181.0,897.0,1484.0,75.0,40.0,21.0,61.0,0.976190,0
13,2018,05,Coahuila de Zaragoza,035,Torreón,05035,0.990713,0.994209,0.989176,0.989310,...,1953.0,280.0,1012.0,661.0,92.0,89.0,79.0,168.0,0.913978,0
14,2018,08,Chihuahua,019,Chihuahua,08019,0.989109,0.993764,0.992383,0.994209,...,2153.0,377.0,1094.0,682.0,98.0,88.0,55.0,143.0,0.933581,0
15,2018,21,Puebla,114,Puebla,21114,0.989087,0.993318,0.998330,0.999109,...,5014.0,611.0,2303.0,2100.0,107.0,163.0,86.0,249.0,0.950339,0
16,2018,02,Baja California,002,Mexicali,02002,0.988374,0.992873,0.990423,0.991091,...,1904.0,375.0,905.0,624.0,95.0,88.0,50.0,138.0,0.927521,0
17,2018,19,Nuevo León,006,Apodaca,19006,0.987706,0.992428,0.971136,0.970601,...,770.0,317.0,175.0,278.0,74.0,68.0,56.0,124.0,0.838961,0
18,2018,11,Guanajuato,007,Celaya,11007,0.987127,0.991982,0.979421,0.982183,...,1412.0,177.0,667.0,568.0,79.0,37.0,32.0,69.0,0.951133,0
19,2018,11,Guanajuato,017,Irapuato,11017,0.987016,0.991537,0.980200,0.982628,...,1444.0,184.0,676.0,584.0,80.0,44.0,26.0,70.0,0.951524,0
20,2018,09,Ciudad de México,007,Iztapalapa,09007,0.986281,0.991091,0.991347,0.992873,...,2974.0,299.0,978.0,1697.0,88.0,71.0,38.0,109.0,0.963349,0
21,2018,15,México,104,Tlalnepantla de Baz,15104,0.984855,0.990646,0.984900,0.987082,...,1690.0,231.0,739.0,720.0,83.0,58.0,58.0,116.0,0.931361,0
22,2018,09,Ciudad de México,002,Azcapotzalco,09002,0.983842,0.990200,0.980512,0.983073,...,1081.0,258.0,386.0,437.0,83.0,79.0,77.0,156.0,0.855689,0
23,2018,19,Nuevo León,026,Guadalupe,19026,0.982929,0.989755,0.976849,0.977283,...,1012.0,233.0,356.0,423.0,78.0,46.0,31.0,77.0,0.923913,0
24,2018,19,Nuevo León,046,San Nicolás de los Garza,19046,0.981893,0.989310,0.974499,0.973719,...,864.0,209.0,342.0,313.0,81.0,59.0,45.0,104.0,0.879630,0
25,2018,15,México,057,Naucalpan de Juárez,15057,0.981247,0.988864,0.978530,0.980401,...,1563.0,118.0,690.0,755.0,81.0,57.0,56.0,113.0,0.927703,0
26,2018,15,México,121,Cuautitlán Izcalli,15121,0.980579,0.988419,0.973029,0.972829,...,930.0,163.0,339.0,428.0,73.0,49.0,32.0,81.0,0.912903,0
27,2018,14,Jalisco,098,San Pedro Tlaquepaque,14098,0.980356,0.987973,0.974588,0.974610,...,975.0,262.0,206.0,507.0,70.0,43.0,32.0,75.0,0.923077,0
28,2018,28,Tamaulipas,032,Reynosa,28032,0.980200,0.987528,0.982984,0.984855,...,1284.0,331.0,485.0,468.0,80.0,69.0,32.0,101.0,0.921340,0
29,2018,11,Guanajuato,037,Silao de la Victoria,11037,0.977171,0.987082,0.948207,0.952339,...,372.0,74.0,117.0,181.0,57.0,16.0,14.0,30.0,0.919355,0
30,2018,28,Tamaulipas,022,Matamoros,28022,0.977105,0.986637,0.978842,0.981737,...,1084.0,288.0,430.0,366.0,78.0,72.0,18.0,90.0,0.916974,0
31,2018,22,Querétaro,016,San Juan del Río,22016,0.976704,0.986192,0.966258,0.967929,...,729.0,117.0,321.0,291.0,64.0,17.0,6.0,23.0,0.968450,0
32,2018,09,Ciudad de México,015,Cuauhtémoc,09015,0.976570,0.985746,0.997038,0.998218,...,6122.0,459.0,4022.0,1641.0,99.0,362.0,218.0,580.0,0.905260,0
33,2018,31,Yucatán,050,Mérida,31050,0.976548,0.985301,0.995189,0.995991,...,3121.0,412.0,1575.0,1134.0,100.0,126.0,70.0,196.0,0.937200,0
34,2018,16,Michoacán de Ocampo,053,Morelia,16053,0.976214,0.984855,0.989532,0.989755,...,2612.0,252.0,1280.0,1080.0,88.0,68.0,41.0,109.0,0.958270,0
35,2018,14,Jalisco,097,Tlajomulco de Zúñiga,14097,0.976125,0.984410,0.957138,0.961693,...,590.0,151.0,110.0,329.0,56.0,29.0,17.0,46.0,0.922034,0
36,2018,15,México,109,Tultitlán,15109,0.975791,0.983964,0.961414,0.965256,...,725.0,110.0,175.0,440.0,55.0,25.0,21.0,46.0,0.936552,0
37,2018,19,Nuevo León,048,Santa Catarina,19048,0.975601,0.983519,0.947695,0.951893,...,343.0,121.0,90.0,132.0,62.0,21.0,18.0,39.0,0.886297,0
38,2018,15,México,051,Lerma,15051,0.975412,0.983073,0.927751,0.933185,...,278.0,49.0,57.0,172.0,45.0,15.0,10.0,25.0,0.910072,0
39,2018,05,Coahuila de Zaragoza,018,Monclova,05018,0.974543,0.982628,0.961637,0.965702,...,601.0,144.0,303.0,154.0,57.0,36.0,9.0,45.0,0.925125,0

VALIDACIÓN RÁPIDA
====================================================================================================
Filas diagnosticadas: 4530
Missing industrial_b2b_opportunity_score: 0
Missing category: 0
Años: [np.int64(2018), np.int64(2023)]

In [ ]:
# ============================================================
# RANKING LIMPIO DEL SCORE DEFINITIVO
# NO GUARDA ARCHIVOS
# Requiere que ya exista score_diagnostic en memoria
# ============================================================

ranking_cols = [
    "year",
    "entidad_name",
    "municipio_name",
    "geo_key",
    "industrial_b2b_opportunity_score",
    "industrial_b2b_opportunity_percentile",
    "industrial_b2b_opportunity_category",
    "industrial_demand_percentile",
    "scaled_b2b_supply_percentile",
    "b2b_supply_percentile",
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "denue_b2b_support_establishments",
    "denue_b2b_medium_large_establishments",
    "b2b_micro_small_share",
    "only_micro_small_b2b_supply"
]

ranking_cols = [col for col in ranking_cols if col in score_diagnostic.columns]

# Ranking puro por score, por año
opportunity_score_ranking = (
    score_diagnostic[ranking_cols]
    .sort_values(
        ["year", "industrial_b2b_opportunity_score"],
        ascending=[True, False]
    )
    .copy()
)

opportunity_score_ranking["rank_opportunity_score_within_year"] = (
    opportunity_score_ranking
    .groupby("year")
    .cumcount() + 1
)

# Mostrar top 50 por año
top_opportunity_score_ranking = (
    opportunity_score_ranking
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

print("RANKING PURO POR INDUSTRIAL_B2B_OPPORTUNITY_SCORE")
print("=" * 100)
display(top_opportunity_score_ranking)


# Ranking restringido a categorías interpretables de oportunidad
opportunity_categories = [
    "Top priority opportunity",
    "Priority opportunity",
    "Developing industrial market"
]

opportunity_only_ranking = (
    opportunity_score_ranking[
        opportunity_score_ranking["industrial_b2b_opportunity_category"]
        .isin(opportunity_categories)
    ]
    .copy()
)

opportunity_only_ranking["rank_opportunity_within_year"] = (
    opportunity_only_ranking
    .groupby("year")
    .cumcount() + 1
)

print("\nRANKING SOLO DE CATEGORÍAS DE OPORTUNIDAD")
print("=" * 100)
display(opportunity_only_ranking.groupby("year").head(50).reset_index(drop=True))


# Ranking por categoría, pero ordenado correctamente por score dentro de cada categoría
category_score_ranking = (
    opportunity_score_ranking
    .sort_values(
        [
            "year",
            "industrial_b2b_opportunity_category",
            "industrial_b2b_opportunity_score"
        ],
        ascending=[True, True, False]
    )
    .copy()
)

category_score_ranking["rank_within_category_year"] = (
    category_score_ranking
    .groupby(["year", "industrial_b2b_opportunity_category"])
    .cumcount() + 1
)

print("\nTOP 20 POR CATEGORÍA Y AÑO")
print("=" * 100)

for year in sorted(category_score_ranking["year"].dropna().unique()):
    print(f"\nAÑO {year}")
    for category in category_score_ranking["industrial_b2b_opportunity_category"].dropna().unique():
        temp = category_score_ranking[
            (category_score_ranking["year"] == year) &
            (category_score_ranking["industrial_b2b_opportunity_category"] == category)
        ].head(20)

        if len(temp) > 0:
            print(f"\n{category}")
            display(temp)

RANKING PURO POR INDUSTRIAL_B2B_OPPORTUNITY_SCORE
====================================================================================================

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year
0,2018,México,Tianguistenco,15101,0.625453,1.000000,Top priority opportunity,0.968374,0.354120,0.814699,671.0,10225.0,167.0,0.0,1.0,1,1
1,2018,Tlaxcala,Huamantla,29013,0.617973,0.999555,Top priority opportunity,0.956793,0.354120,0.891314,743.0,7179.0,174.0,0.0,1.0,1,2
2,2018,Jalisco,Arandas,14008,0.604739,0.999109,Top priority opportunity,0.936303,0.354120,0.854343,458.0,6485.0,187.0,0.0,1.0,1,3
3,2018,Guanajuato,Apaseo el Alto,11004,0.593231,0.998664,Top priority opportunity,0.918486,0.354120,0.861024,404.0,3985.0,111.0,0.0,1.0,1,4
4,2018,Yucatán,Kanasín,31041,0.587190,0.998218,Top priority opportunity,0.909131,0.354120,0.766592,318.0,3541.0,57.0,0.0,1.0,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023,Guanajuato,Yuriria,11046,0.554978,0.980306,Priority opportunity,0.842888,0.341575,0.850766,341.0,1268.0,111.0,0.0,1.0,1,46
96,2023,Veracruz de Ignacio de la Llave,Carlos A. Carrillo,30208,0.554402,0.979869,Priority opportunity,0.842013,0.341575,0.496718,116.0,2024.0,14.0,0.0,1.0,1,47
97,2023,Guerrero,Técpan de Galeana,12057,0.552097,0.979431,Priority opportunity,0.838512,0.341575,0.862582,514.0,1471.0,86.0,0.0,1.0,1,48
98,2023,Veracruz de Ignacio de la Llave,San Rafael,30211,0.551232,0.978993,Priority opportunity,0.837199,0.341575,0.747046,129.0,943.0,41.0,0.0,1.0,1,49
99,2023,Michoacán de Ocampo,Nuevo Parangaricutiro,16058,0.550656,0.978556,Priority opportunity,0.836324,0.341575,0.651641,741.0,1629.0,33.0,0.0,1.0,1,50

RANKING SOLO DE CATEGORÍAS DE OPORTUNIDAD
====================================================================================================

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_opportunity_within_year
0,2018,México,Tianguistenco,15101,0.625453,1.000000,Top priority opportunity,0.968374,0.354120,0.814699,671.0,10225.0,167.0,0.0,1.0,1,1,1
1,2018,Tlaxcala,Huamantla,29013,0.617973,0.999555,Top priority opportunity,0.956793,0.354120,0.891314,743.0,7179.0,174.0,0.0,1.0,1,2,2
2,2018,Jalisco,Arandas,14008,0.604739,0.999109,Top priority opportunity,0.936303,0.354120,0.854343,458.0,6485.0,187.0,0.0,1.0,1,3,3
3,2018,Guanajuato,Apaseo el Alto,11004,0.593231,0.998664,Top priority opportunity,0.918486,0.354120,0.861024,404.0,3985.0,111.0,0.0,1.0,1,4,4
4,2018,Yucatán,Kanasín,31041,0.587190,0.998218,Top priority opportunity,0.909131,0.354120,0.766592,318.0,3541.0,57.0,0.0,1.0,1,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023,Guanajuato,Yuriria,11046,0.554978,0.980306,Priority opportunity,0.842888,0.341575,0.850766,341.0,1268.0,111.0,0.0,1.0,1,46,46
96,2023,Veracruz de Ignacio de la Llave,Carlos A. Carrillo,30208,0.554402,0.979869,Priority opportunity,0.842013,0.341575,0.496718,116.0,2024.0,14.0,0.0,1.0,1,47,47
97,2023,Guerrero,Técpan de Galeana,12057,0.552097,0.979431,Priority opportunity,0.838512,0.341575,0.862582,514.0,1471.0,86.0,0.0,1.0,1,48,48
98,2023,Veracruz de Ignacio de la Llave,San Rafael,30211,0.551232,0.978993,Priority opportunity,0.837199,0.341575,0.747046,129.0,943.0,41.0,0.0,1.0,1,49,49
99,2023,Michoacán de Ocampo,Nuevo Parangaricutiro,16058,0.550656,0.978556,Priority opportunity,0.836324,0.341575,0.651641,741.0,1629.0,33.0,0.0,1.0,1,50,50

TOP 20 POR CATEGORÍA Y AÑO
====================================================================================================

AÑO 2018

Developing industrial market

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
681,2018,Guerrero,Huitzuco de los Figueroa,12034,0.483906,0.935412,Developing industrial market,0.749220,0.35412,0.784410,514.0,1051.0,57.0,0.0,1.0,1,146,1
570,2018,Puebla,Tepeyahualco,21170,0.483331,0.934967,Developing industrial market,0.748330,0.35412,0.159911,104.0,607.0,4.0,0.0,1.0,1,147,2
533,2018,Hidalgo,Zapotlán de Juárez,13082,0.483043,0.934521,Developing industrial market,0.747884,0.35412,0.571492,180.0,817.0,29.0,0.0,1.0,1,148,3
703,2018,Oaxaca,Teotitlán del Valle,20546,0.482756,0.934076,Developing industrial market,0.747439,0.35412,0.319154,740.0,1408.0,8.0,0.0,1.0,1,149,4
772,2018,Guerrero,Mártir de Cuilapan,12042,0.482180,0.933630,Developing industrial market,0.746548,0.35412,0.554120,682.0,1033.0,16.0,0.0,1.0,1,150,5
603,2018,Chiapas,Acapetahua,07003,0.481892,0.933185,Developing industrial market,0.746102,0.35412,0.656570,102.0,550.0,31.0,0.0,1.0,1,151,6
612,2018,Oaxaca,Cosolapa,20021,0.481317,0.932739,Developing industrial market,0.745212,0.35412,0.583073,116.0,637.0,23.0,0.0,1.0,1,152,7
485,2018,Jalisco,Zapotlán del Rey,14123,0.481029,0.932294,Developing industrial market,0.744766,0.35412,0.640535,55.0,3296.0,21.0,0.0,1.0,1,153,8
632,2018,Veracruz de Ignacio de la Llave,Coscomatepec,30047,0.479303,0.931849,Developing industrial market,0.742094,0.35412,0.644543,323.0,837.0,34.0,0.0,1.0,1,154,9
407,2018,Puebla,Chalchicomula de Sesma,21045,0.478440,0.931403,Developing industrial market,0.740757,0.35412,0.821826,335.0,1184.0,105.0,0.0,1.0,1,155,10
638,2018,México,Atlautla,15015,0.478152,0.930958,Developing industrial market,0.740312,0.35412,0.663252,208.0,623.0,46.0,0.0,1.0,1,156,11
630,2018,Oaxaca,Santa María Xadani,20441,0.477865,0.930512,Developing industrial market,0.739866,0.35412,0.132962,1203.0,1300.0,3.0,0.0,1.0,1,157,12
537,2018,Chihuahua,Saucillo,08062,0.477577,0.930067,Developing industrial market,0.739421,0.35412,0.736080,63.0,1008.0,35.0,0.0,1.0,1,158,13
601,2018,Michoacán de Ocampo,Buenavista,16012,0.477289,0.929621,Developing industrial market,0.738976,0.35412,0.763474,154.0,494.0,49.0,0.0,1.0,1,159,14
547,2018,Tlaxcala,Cuapiaxtla,29008,0.477002,0.929176,Developing industrial market,0.738530,0.35412,0.414031,89.0,611.0,15.0,0.0,1.0,1,160,15
705,2018,Yucatán,Oxkutzcab,31056,0.476714,0.928731,Developing industrial market,0.738085,0.35412,0.756347,598.0,926.0,46.0,0.0,1.0,1,161,16
627,2018,Puebla,Tochtepec,21189,0.476139,0.928285,Developing industrial market,0.737194,0.35412,0.513586,178.0,551.0,26.0,0.0,1.0,1,162,17
487,2018,Guerrero,Técpan de Galeana,12057,0.475851,0.927840,Developing industrial market,0.736748,0.35412,0.881514,457.0,1242.0,114.0,0.0,1.0,1,163,18
585,2018,Zacatecas,Tabasco,32044,0.475563,0.927394,Developing industrial market,0.736303,0.35412,0.686414,76.0,1149.0,26.0,0.0,1.0,1,164,19
740,2018,Michoacán de Ocampo,Tzintzuntzan,16100,0.475275,0.926949,Developing industrial market,0.735857,0.35412,0.336080,733.0,1271.0,10.0,0.0,1.0,1,165,20

Industrial ecosystem hub

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
214,2018,Michoacán de Ocampo,Sahuayo,16076,0.183472,0.535857,Industrial ecosystem hub,0.922494,0.801114,0.906904,1633.0,4955.0,207.0,2.0,0.990338,0,1043,1
225,2018,Guanajuato,Dolores Hidalgo Cuna de la Independencia Nacional,11014,0.182231,0.533185,Industrial ecosystem hub,0.916258,0.801114,0.898441,860.0,5399.0,219.0,2.0,0.990868,0,1049,2
209,2018,Guanajuato,Acámbaro,11002,0.181877,0.532294,Industrial ecosystem hub,0.914477,0.801114,0.930067,489.0,5296.0,261.0,2.0,0.992337,0,1051,3
213,2018,México,Valle de Chalco Solidaridad,15122,0.180902,0.529621,Industrial ecosystem hub,0.909577,0.801114,0.930958,1644.0,4529.0,601.0,2.0,0.996672,0,1057,4
251,2018,Chiapas,Venustiano Carranza,07106,0.180637,0.527840,Industrial ecosystem hub,0.908241,0.801114,0.829844,526.0,1942.0,76.0,2.0,0.973684,0,1061,5
279,2018,Guanajuato,Uriangato,11041,0.179131,0.524722,Industrial ecosystem hub,0.900668,0.801114,0.894878,1219.0,3575.0,176.0,2.0,0.988636,0,1068,6
204,2018,Querétaro,Pedro Escobedo,22012,0.178599,0.522940,Industrial ecosystem hub,0.897996,0.801114,0.830735,236.0,2380.0,92.0,2.0,0.978261,0,1072,7
311,2018,Tlaxcala,San Pablo del Monte,29025,0.177182,0.518931,Industrial ecosystem hub,0.890869,0.801114,0.832071,1023.0,3072.0,125.0,2.0,0.984000,0,1081,8
276,2018,México,Chicoloapan,15029,0.176739,0.518040,Industrial ecosystem hub,0.888641,0.801114,0.856570,559.0,2008.0,255.0,2.0,0.992157,0,1083,9
283,2018,San Luis Potosí,Rioverde,24024,0.175676,0.514922,Industrial ecosystem hub,0.883296,0.801114,0.919376,362.0,1871.0,253.0,2.0,0.992095,0,1090,10
246,2018,Aguascalientes,Calvillo,01003,0.175587,0.514477,Industrial ecosystem hub,0.882851,0.801114,0.808909,273.0,3366.0,86.0,2.0,0.976744,0,1091,11
287,2018,Guanajuato,Comonfort,11009,0.174170,0.510022,Industrial ecosystem hub,0.875724,0.801114,0.852561,328.0,2349.0,123.0,2.0,0.983740,0,1101,12
317,2018,Oaxaca,Santa Lucía del Camino,20390,0.173638,0.508241,Industrial ecosystem hub,0.873051,0.801114,0.837416,521.0,1976.0,189.0,2.0,0.989418,0,1105,13
273,2018,Chiapas,Chiapa de Corzo,07027,0.173284,0.507350,Industrial ecosystem hub,0.871269,0.801114,0.875278,385.0,1634.0,109.0,2.0,0.981651,0,1107,14
324,2018,Jalisco,Ameca,14006,0.172309,0.505122,Industrial ecosystem hub,0.866370,0.801114,0.891759,295.0,1439.0,126.0,2.0,0.984127,0,1112,15
384,2018,Puebla,Xicotepec,21197,0.170626,0.502004,Industrial ecosystem hub,0.857906,0.801114,0.911359,639.0,1587.0,201.0,2.0,0.990050,0,1119,16
342,2018,Hidalgo,Apan,13008,0.167968,0.497105,Industrial ecosystem hub,0.844543,0.801114,0.855234,252.0,1585.0,104.0,2.0,0.980769,0,1130,17
184,2018,Guanajuato,Pénjamo,11023,0.167259,0.494878,Industrial ecosystem hub,0.840980,0.801114,0.924276,399.0,5428.0,225.0,2.0,0.991111,0,1135,18
336,2018,Veracruz de Ignacio de la Llave,Ursulo Galván,30191,0.164868,0.489087,Industrial ecosystem hub,0.828953,0.801114,0.654343,92.0,1546.0,27.0,2.0,0.925926,0,1148,19
429,2018,Chiapas,Arriaga,07009,0.164425,0.487751,Industrial ecosystem hub,0.826726,0.801114,0.873942,238.0,1148.0,111.0,2.0,0.981982,0,1151,20

Intermediate / monitor

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
351,2018,Puebla,San José Chiapa,21128,0.147415,0.447216,Intermediate / monitor,0.741203,0.801114,0.334076,39.0,6547.0,8.0,2.0,0.750000,0,1242,1
453,2018,Veracruz de Ignacio de la Llave,Huatusco,30071,0.146706,0.444543,Intermediate / monitor,0.737639,0.801114,0.883296,288.0,833.0,134.0,2.0,0.985075,0,1248,2
572,2018,México,Tejupilco,15082,0.144403,0.437862,Intermediate / monitor,0.726058,0.801114,0.856125,268.0,762.0,128.0,2.0,0.984375,0,1263,3
682,2018,Puebla,Acatlán,21003,0.142631,0.431626,Intermediate / monitor,0.717149,0.801114,0.858352,287.0,628.0,124.0,2.0,0.983871,0,1277,4
651,2018,Tabasco,Emiliano Zapata,27007,0.140948,0.427171,Intermediate / monitor,0.708686,0.801114,0.848552,158.0,413.0,86.0,2.0,0.976744,0,1287,5
878,2018,Oaxaca,San Juan Cotzocón,20190,0.140328,0.424944,Intermediate / monitor,0.705568,0.801114,0.748775,847.0,979.0,38.0,2.0,0.947368,0,1292,6
744,2018,Veracruz de Ignacio de la Llave,Catemaco,30032,0.132089,0.401782,Intermediate / monitor,0.664143,0.801114,0.855679,209.0,503.0,94.0,2.0,0.978723,0,1344,7
646,2018,Puebla,Zacapoaxtla,21207,0.126732,0.387528,Intermediate / monitor,0.719376,0.823831,0.831626,277.0,734.0,103.0,1.0,0.990291,0,1376,8
700,2018,Michoacán de Ocampo,Zinapécuaro,16110,0.126596,0.387082,Intermediate / monitor,0.636526,0.801114,0.827171,211.0,644.0,75.0,2.0,0.973333,0,1377,9
569,2018,San Luis Potosí,Mexquitic de Carmona,24021,0.126026,0.385746,Intermediate / monitor,0.715367,0.823831,0.360134,19.0,2564.0,6.0,1.0,0.833333,0,1380,10
622,2018,Durango,Nombre de Dios,10016,0.124456,0.382183,Intermediate / monitor,0.706459,0.823831,0.652116,43.0,1824.0,19.0,1.0,0.947368,0,1388,11
596,2018,Nayarit,Ixtlán del Río,18006,0.119379,0.368374,Intermediate / monitor,0.749666,0.840757,0.833408,206.0,671.0,70.0,3.0,0.957143,0,1419,12
549,2018,Chiapas,Motozintla,07057,0.119237,0.367929,Intermediate / monitor,0.748775,0.840757,0.863697,262.0,585.0,101.0,3.0,0.970297,0,1420,13
985,2018,Veracruz de Ignacio de la Llave,Oluta,30116,0.119066,0.367038,Intermediate / monitor,0.598664,0.801114,0.667261,146.0,340.0,25.0,2.0,0.920000,0,1422,14
770,2018,Quintana Roo,Felipe Carrillo Puerto,23002,0.118180,0.364811,Intermediate / monitor,0.594209,0.801114,0.844098,166.0,441.0,83.0,2.0,0.975904,0,1427,15
933,2018,Chiapas,Bochil,07013,0.117914,0.363920,Intermediate / monitor,0.592873,0.801114,0.767483,109.0,244.0,47.0,2.0,0.957447,0,1429,16
769,2018,Zacatecas,Tlaltenango de Sánchez Román,32048,0.117472,0.363029,Intermediate / monitor,0.666815,0.823831,0.862806,198.0,478.0,101.0,1.0,0.990099,0,1431,17
929,2018,Morelos,Atlatlahucan,17002,0.117117,0.361693,Intermediate / monitor,0.588864,0.801114,0.733185,88.0,202.0,35.0,2.0,0.942857,0,1434,18
639,2018,Oaxaca,Heroica Ciudad de Tlaxiaco,20397,0.117038,0.360356,Intermediate / monitor,0.734967,0.840757,0.898886,288.0,719.0,152.0,3.0,0.980263,0,1437,19
731,2018,San Luis Potosí,Tamazunchale,24037,0.115511,0.354566,Intermediate / monitor,0.655679,0.823831,0.869488,193.0,478.0,116.0,1.0,0.991379,0,1450,20

Lower initial priority

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
998,2018,Hidalgo,Nopala de Villagrán,13044,0.322796,0.762584,Lower initial priority,0.499777,0.35412,0.257906,20.0,182.0,5.0,0.0,1.0,1,534,1
1124,2018,México,Amatepec,15008,0.322508,0.762138,Lower initial priority,0.499332,0.35412,0.543207,82.0,192.0,21.0,0.0,1.0,1,535,2
1225,2018,Guerrero,Tetipac,12060,0.322221,0.761693,Lower initial priority,0.498886,0.35412,0.188641,100.0,168.0,4.0,0.0,1.0,1,536,3
897,2018,Nayarit,Santa María del Oro,18014,0.321933,0.761247,Lower initial priority,0.498441,0.35412,0.581292,34.0,128.0,14.0,0.0,1.0,1,537,4
1103,2018,Puebla,Chiautzingo,21048,0.321645,0.760802,Lower initial priority,0.497996,0.35412,0.487305,122.0,269.0,26.0,0.0,1.0,1,538,5
1076,2018,Nuevo León,Lampazos de Naranjo,19032,0.321070,0.760356,Lower initial priority,0.497105,0.35412,0.521604,12.0,132.0,10.0,0.0,1.0,1,539,6
1030,2018,México,Papalotla,15069,0.320782,0.759911,Lower initial priority,0.496659,0.35412,0.383296,38.0,180.0,10.0,0.0,1.0,1,540,7
1317,2018,Oaxaca,San Vicente Coatlán,20534,0.320494,0.759465,Lower initial priority,0.496214,0.35412,0.150780,215.0,317.0,2.0,0.0,1.0,1,541,8
1154,2018,Zacatecas,Villa de Cos,32051,0.320207,0.759020,Lower initial priority,0.495768,0.35412,0.543207,82.0,187.0,21.0,0.0,1.0,1,542,9
1088,2018,San Luis Potosí,Villa de Arista,24056,0.319631,0.758575,Lower initial priority,0.494878,0.35412,0.508463,61.0,153.0,13.0,0.0,1.0,1,543,10
1200,2018,San Luis Potosí,Zaragoza,24055,0.319344,0.758129,Lower initial priority,0.494432,0.35412,0.541648,40.0,235.0,11.0,0.0,1.0,1,544,11
1120,2018,Puebla,Nicolás Bravo,21103,0.319056,0.757684,Lower initial priority,0.493987,0.35412,0.276615,28.0,226.0,5.0,0.0,1.0,1,545,12
1189,2018,Morelos,Zacualpan de Amilpas,17032,0.318768,0.757238,Lower initial priority,0.493541,0.35412,0.496882,99.0,214.0,16.0,0.0,1.0,1,546,13
1131,2018,Jalisco,Huejuquilla el Alto,14042,0.318481,0.756793,Lower initial priority,0.493096,0.35412,0.621381,85.0,222.0,18.0,0.0,1.0,1,547,14
1096,2018,Sonora,Ures,26066,0.318193,0.756347,Lower initial priority,0.492650,0.35412,0.497550,61.0,130.0,10.0,0.0,1.0,1,548,15
1157,2018,Veracruz de Ignacio de la Llave,Ixhuatlancillo,30081,0.317905,0.755902,Lower initial priority,0.492205,0.35412,0.504232,124.0,233.0,15.0,0.0,1.0,1,549,16
1191,2018,Hidalgo,San Salvador,13054,0.317617,0.755457,Lower initial priority,0.491759,0.35412,0.522049,80.0,185.0,26.0,0.0,1.0,1,550,17
1129,2018,Puebla,Zapotitlán,21209,0.317330,0.755011,Lower initial priority,0.491314,0.35412,0.321826,73.0,213.0,7.0,0.0,1.0,1,551,18
1116,2018,Zacatecas,Pánuco,32037,0.317042,0.754566,Lower initial priority,0.490869,0.35412,0.308241,56.0,151.0,8.0,0.0,1.0,1,552,19
1315,2018,Yucatán,Tixcacalcupul,31092,0.316754,0.754120,Lower initial priority,0.490423,0.35412,0.132962,215.0,282.0,3.0,0.0,1.0,1,553,20

Priority opportunity

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
261,2018,Hidalgo,Zacualtipán de Ángeles,13081,0.580860,0.997327,Priority opportunity,0.899332,0.35412,0.767929,338.0,3456.0,71.0,0.0,1.0,1,7,1
238,2018,Yucatán,Hunucmá,31038,0.579709,0.996882,Priority opportunity,0.897550,0.35412,0.678396,257.0,1756.0,41.0,0.0,1.0,1,8,2
234,2018,Jalisco,Tala,14083,0.579134,0.996437,Priority opportunity,0.896659,0.35412,0.852116,249.0,3568.0,109.0,0.0,1.0,1,9,3
295,2018,Campeche,Calkiní,04001,0.577408,0.995991,Priority opportunity,0.893987,0.35412,0.797773,1147.0,3999.0,73.0,0.0,1.0,1,10,4
305,2018,México,Zumpango,15120,0.575682,0.995546,Priority opportunity,0.891314,0.35412,0.901559,826.0,2518.0,319.0,0.0,1.0,1,11,5
252,2018,Querétaro,Ezequiel Montes,22007,0.574531,0.995100,Priority opportunity,0.889532,0.35412,0.838307,301.0,2650.0,99.0,0.0,1.0,1,12,6
366,2018,Puebla,Tlacotepec de Benito Juárez,21177,0.574243,0.994655,Priority opportunity,0.889087,0.35412,0.754566,1537.0,2575.0,50.0,0.0,1.0,1,13,7
302,2018,Veracruz de Ignacio de la Llave,Álamo Temapache,30160,0.569928,0.994209,Priority opportunity,0.882405,0.35412,0.878842,307.0,1360.0,142.0,0.0,1.0,1,14,8
308,2018,Puebla,Tepanco de López,21161,0.564749,0.993764,Priority opportunity,0.874388,0.35412,0.621826,141.0,4776.0,26.0,0.0,1.0,1,15,9
271,2018,Tlaxcala,Tlaxco,29034,0.563598,0.993318,Priority opportunity,0.872606,0.35412,0.753229,288.0,2566.0,43.0,0.0,1.0,1,16,10
313,2018,Ciudad de México,Milpa Alta,09009,0.563311,0.992873,Priority opportunity,0.872160,0.35412,0.841871,577.0,1848.0,236.0,0.0,1.0,1,17,11
285,2018,Tlaxcala,Ixtacuixtla de Mariano Matamoros,29015,0.562448,0.992428,Priority opportunity,0.870824,0.35412,0.547439,331.0,1982.0,54.0,0.0,1.0,1,18,12
326,2018,Jalisco,Autlán de Navarro,14015,0.561872,0.991982,Priority opportunity,0.869933,0.35412,0.874388,317.0,2011.0,159.0,0.0,1.0,1,19,13
368,2018,Puebla,Altepexi,21013,0.561297,0.991537,Priority opportunity,0.869042,0.35412,0.556347,888.0,3126.0,34.0,0.0,1.0,1,20,14
281,2018,Jalisco,Ayotlán,14016,0.560434,0.991091,Priority opportunity,0.867706,0.35412,0.795991,242.0,2787.0,78.0,0.0,1.0,1,21,15
427,2018,Yucatán,Tekax,31079,0.558995,0.990646,Priority opportunity,0.865479,0.35412,0.702895,1138.0,2703.0,61.0,0.0,1.0,1,22,16
448,2018,Michoacán de Ocampo,Quiroga,16073,0.558132,0.990200,Priority opportunity,0.864143,0.35412,0.732739,1765.0,3675.0,55.0,0.0,1.0,1,23,17
463,2018,Guerrero,Zitlala,12074,0.557269,0.989755,Priority opportunity,0.862806,0.35412,0.365256,1972.0,3958.0,12.0,0.0,1.0,1,24,18
286,2018,Tlaxcala,Tepetitla de Lardizábal,29019,0.556981,0.989310,Priority opportunity,0.862361,0.35412,0.488196,180.0,1571.0,38.0,0.0,1.0,1,25,19
416,2018,Yucatán,Tekit,31080,0.556406,0.988864,Priority opportunity,0.861470,0.35412,0.328508,1052.0,2605.0,7.0,0.0,1.0,1,26,20

Service hub, lower industrial demand

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
1159,2018,Michoacán de Ocampo,Álvaro Obregón,16003,0.096032,0.291759,"Service hub, lower industrial demand",0.482851,0.801114,0.768374,74.0,160.0,43.0,2.0,0.953488,0,1591,1
1130,2018,Chiapas,Acala,07002,0.094792,0.288196,"Service hub, lower industrial demand",0.476615,0.801114,0.721604,105.0,207.0,32.0,2.0,0.937500,0,1599,2
1259,2018,Veracruz de Ignacio de la Llave,Atzacan,30022,0.086553,0.259243,"Service hub, lower industrial demand",0.435189,0.801114,0.483296,61.0,132.0,18.0,2.0,0.888889,0,1664,3
1242,2018,Sonora,San Ignacio Río Muerto,26072,0.082082,0.244543,"Service hub, lower industrial demand",0.465924,0.823831,0.452116,69.0,153.0,8.0,1.0,0.875000,0,1697,4
1109,2018,Quintana Roo,Lázaro Cárdenas,23007,0.079257,0.233853,"Service hub, lower industrial demand",0.449889,0.823831,0.610690,67.0,180.0,18.0,1.0,0.944444,0,1721,5
1219,2018,Nuevo León,General Bravo,19020,0.078707,0.231180,"Service hub, lower industrial demand",0.446771,0.823831,0.510690,27.0,95.0,11.0,1.0,0.909091,0,1727,6
1262,2018,Chiapas,Mezcalapa,07124,0.077074,0.226281,"Service hub, lower industrial demand",0.387528,0.801114,0.586192,49.0,112.0,22.0,2.0,0.909091,0,1738,7
1434,2018,Hidalgo,Tlanchinol,13073,0.068584,0.198218,"Service hub, lower industrial demand",0.389310,0.823831,0.601782,68.0,115.0,18.0,1.0,0.944444,0,1801,8
1322,2018,Chiapas,Tecpatán,07092,0.067159,0.192873,"Service hub, lower industrial demand",0.453452,0.851893,0.673051,67.0,116.0,34.0,2.0,0.941176,0,1813,9
1071,2018,Michoacán de Ocampo,Tancítaro,16083,0.062577,0.180846,"Service hub, lower industrial demand",0.488641,0.871938,0.714477,65.0,189.0,32.0,2.0,0.937500,0,1840,10
1639,2018,Colima,Minatitlán,06008,0.058824,0.165702,"Service hub, lower industrial demand",0.295768,0.801114,0.632517,21.0,57.0,17.0,2.0,0.882353,0,1874,11
1332,2018,San Luis Potosí,Aquismón,24003,0.058448,0.164365,"Service hub, lower industrial demand",0.367038,0.840757,0.663697,39.0,125.0,77.0,3.0,0.961039,0,1877,12
1134,2018,Quintana Roo,Isla Mujeres,23003,0.052114,0.144321,"Service hub, lower industrial demand",0.457016,0.885969,0.766147,45.0,155.0,48.0,3.0,0.937500,0,1922,13
1562,2018,Zacatecas,Chalchihuites,32009,0.051321,0.140757,"Service hub, lower industrial demand",0.291314,0.823831,0.588419,22.0,64.0,16.0,1.0,0.937500,0,1930,14
1667,2018,Chiapas,Huitiupán,07039,0.050054,0.136748,"Service hub, lower industrial demand",0.251670,0.801114,0.407350,37.0,63.0,6.0,2.0,0.666667,0,1939,15
1681,2018,Sonora,Rosario,26051,0.046141,0.124276,"Service hub, lower industrial demand",0.261915,0.823831,0.410690,23.0,47.0,5.0,1.0,0.800000,0,1967,16
1782,2018,Zacatecas,Vetagrande,32050,0.042524,0.113586,"Service hub, lower industrial demand",0.213808,0.801114,0.385301,26.0,50.0,7.0,2.0,0.714286,0,1991,17
1827,2018,Jalisco,San Martín de Bolaños,14076,0.032601,0.085969,"Service hub, lower industrial demand",0.163920,0.801114,0.366147,12.0,34.0,5.0,2.0,0.600000,0,2053,18
2167,2018,Chihuahua,Guadalupe,08028,0.004430,0.011581,"Service hub, lower industrial demand",0.022272,0.801114,0.564143,5.0,7.0,13.0,2.0,0.846154,0,2220,19

Top priority opportunity

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
63,2018,México,Tianguistenco,15101,0.625453,1.000000,Top priority opportunity,0.968374,0.35412,0.814699,671.0,10225.0,167.0,0.0,1.0,1,1,1
109,2018,Tlaxcala,Huamantla,29013,0.617973,0.999555,Top priority opportunity,0.956793,0.35412,0.891314,743.0,7179.0,174.0,0.0,1.0,1,2,2
173,2018,Jalisco,Arandas,14008,0.604739,0.999109,Top priority opportunity,0.936303,0.35412,0.854343,458.0,6485.0,187.0,0.0,1.0,1,3,3
178,2018,Guanajuato,Apaseo el Alto,11004,0.593231,0.998664,Top priority opportunity,0.918486,0.35412,0.861024,404.0,3985.0,111.0,0.0,1.0,1,4,4
194,2018,Yucatán,Kanasín,31041,0.587190,0.998218,Top priority opportunity,0.909131,0.35412,0.766592,318.0,3541.0,57.0,0.0,1.0,1,5,5
250,2018,Tlaxcala,Contla de Juan Cuamatzi,29018,0.583737,0.997773,Top priority opportunity,0.903786,0.35412,0.703786,644.0,3937.0,76.0,0.0,1.0,1,6,6

AÑO 2023

Developing industrial market

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
2929,2023,Oaxaca,Teotitlán del Valle,20546,0.493314,0.941357,Developing industrial market,0.749234,0.341575,0.356674,899.0,1764.0,8.0,0.0,1.0,1,135,1
2947,2023,Puebla,Nealtican,21102,0.492738,0.940919,Developing industrial market,0.748359,0.341575,0.452079,311.0,748.0,17.0,0.0,1.0,1,136,2
2786,2023,Yucatán,Baca,31004,0.492450,0.940481,Developing industrial market,0.747921,0.341575,0.473961,35.0,3699.0,9.0,0.0,1.0,1,137,3
2903,2023,Jalisco,Zacoalco de Torres,14119,0.492162,0.940044,Developing industrial market,0.747484,0.341575,0.764551,204.0,638.0,41.0,0.0,1.0,1,138,4
2845,2023,Tlaxcala,Atltzayanca,29004,0.491585,0.939606,Developing industrial market,0.746608,0.341575,0.540481,159.0,851.0,13.0,0.0,1.0,1,139,5
2893,2023,México,Xonacatlán,15115,0.488992,0.939168,Developing industrial market,0.742670,0.341575,0.828446,318.0,891.0,120.0,0.0,1.0,1,140,6
2831,2023,Jalisco,Jamay,14047,0.487551,0.938731,Developing industrial market,0.740481,0.341575,0.670022,140.0,590.0,29.0,0.0,1.0,1,141,7
3064,2023,Michoacán de Ocampo,Tingambato,16090,0.487263,0.938293,Developing industrial market,0.740044,0.341575,0.617943,616.0,873.0,35.0,0.0,1.0,1,142,8
2933,2023,Puebla,Tochtepec,21189,0.486398,0.937856,Developing industrial market,0.738731,0.341575,0.658206,221.0,528.0,27.0,0.0,1.0,1,143,9
2749,2023,Sonora,Santa Ana,26058,0.485822,0.937418,Developing industrial market,0.737856,0.341575,0.741357,64.0,1572.0,33.0,0.0,1.0,1,144,10
2588,2023,Guanajuato,Doctor Mora,11013,0.485534,0.936980,Developing industrial market,0.737418,0.341575,0.662144,65.0,3362.0,26.0,0.0,1.0,1,145,11
2853,2023,Chiapas,Acapetahua,07003,0.484670,0.936543,Developing industrial market,0.736105,0.341575,0.652516,107.0,640.0,31.0,0.0,1.0,1,146,12
2928,2023,Oaxaca,Santa María Xadani,20441,0.484093,0.936105,Developing industrial market,0.735230,0.341575,0.423851,1298.0,1455.0,6.0,0.0,1.0,1,147,13
2834,2023,Jalisco,Amatitán,14005,0.483805,0.935667,Developing industrial market,0.734792,0.341575,0.621444,56.0,579.0,19.0,0.0,1.0,1,148,14
2967,2023,Guerrero,Olinalá,12045,0.483229,0.935230,Developing industrial market,0.733917,0.341575,0.638074,557.0,1424.0,24.0,0.0,1.0,1,149,15
2888,2023,Michoacán de Ocampo,Buenavista,16012,0.482653,0.934792,Developing industrial market,0.733042,0.341575,0.755799,155.0,550.0,42.0,0.0,1.0,1,150,16
2978,2023,Yucatán,Oxkutzcab,31056,0.482364,0.934354,Developing industrial market,0.732604,0.341575,0.737856,469.0,819.0,45.0,0.0,1.0,1,151,17
2711,2023,Puebla,Quecholac,21115,0.482076,0.933917,Developing industrial market,0.732166,0.341575,0.801313,352.0,1305.0,71.0,0.0,1.0,1,152,18
2832,2023,Guanajuato,Cuerámaro,11012,0.481500,0.933479,Developing industrial market,0.731291,0.341575,0.754923,175.0,882.0,50.0,0.0,1.0,1,153,19
2591,2023,Durango,Tlahualilo,10036,0.480924,0.933042,Developing industrial market,0.730416,0.341575,0.590810,58.0,2957.0,16.0,0.0,1.0,1,154,20

Industrial ecosystem hub

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
2483,2023,Veracruz de Ignacio de la Llave,Perote,30128,0.192400,0.564551,Industrial ecosystem hub,0.921663,0.791247,0.896718,852.0,2598.0,154.0,2.0,0.987013,0,996,1
2389,2023,Tlaxcala,Tetla de la Solidaridad,29031,0.192308,0.564114,Industrial ecosystem hub,0.921225,0.791247,0.725602,193.0,11268.0,33.0,2.0,0.939394,0,997,2
2477,2023,Chiapas,Villaflores,07108,0.191943,0.563239,Industrial ecosystem hub,0.919475,0.791247,0.911160,831.0,2491.0,176.0,2.0,0.988636,0,999,3
2481,2023,Guanajuato,Dolores Hidalgo Cuna de la Independencia Nacional,11014,0.190664,0.560613,Industrial ecosystem hub,0.913348,0.791247,0.910284,1013.0,5939.0,240.0,2.0,0.991667,0,1005,4
2453,2023,Guanajuato,Comonfort,11009,0.189842,0.558862,Industrial ecosystem hub,0.909409,0.791247,0.848578,281.0,3412.0,105.0,2.0,0.980952,0,1009,5
2511,2023,Guanajuato,Apaseo el Alto,11004,0.187466,0.552735,Industrial ecosystem hub,0.898031,0.791247,0.861269,354.0,2655.0,114.0,2.0,0.982456,0,1023,6
2533,2023,San Luis Potosí,Rioverde,24024,0.186735,0.550985,Industrial ecosystem hub,0.894530,0.791247,0.917724,480.0,1992.0,234.0,2.0,0.991453,0,1027,7
2540,2023,Puebla,Acajete,21001,0.186461,0.550109,Industrial ecosystem hub,0.893217,0.791247,0.835011,575.0,2343.0,85.0,2.0,0.976471,0,1029,8
2516,2023,Querétaro,Ezequiel Montes,22007,0.186279,0.549234,Industrial ecosystem hub,0.892341,0.791247,0.800438,305.0,2410.0,76.0,2.0,0.973684,0,1031,9
2478,2023,Coahuila de Zaragoza,San Pedro,05033,0.186096,0.548796,Industrial ecosystem hub,0.891466,0.791247,0.852079,254.0,6975.0,87.0,2.0,0.977011,0,1032,10
2546,2023,Chiapas,Huixtla,07040,0.185182,0.546171,Industrial ecosystem hub,0.887090,0.791247,0.903720,297.0,1645.0,157.0,2.0,0.987261,0,1038,11
2574,2023,Puebla,Tepeaca,21164,0.183538,0.542232,Industrial ecosystem hub,0.879212,0.791247,0.891904,991.0,2714.0,178.0,2.0,0.988764,0,1047,12
2530,2023,Puebla,San Miguel Xoxtla,21136,0.181437,0.537856,Industrial ecosystem hub,0.869147,0.791247,0.668271,123.0,1671.0,24.0,2.0,0.916667,0,1057,13
2475,2023,Michoacán de Ocampo,Hidalgo,16034,0.179427,0.533479,Industrial ecosystem hub,0.859519,0.791247,0.927352,2401.0,6873.0,290.0,2.0,0.993103,0,1067,14
2705,2023,Guanajuato,San Luis de la Paz,11033,0.176412,0.524726,Industrial ecosystem hub,0.845077,0.791247,0.913786,446.0,1473.0,190.0,2.0,0.989474,0,1087,15
2732,2023,Oaxaca,Heroica Ciudad de Huajuapan de León,20039,0.174859,0.521225,Industrial ecosystem hub,0.837637,0.791247,0.946608,593.0,1434.0,376.0,2.0,0.994681,0,1095,16
2700,2023,Puebla,Chignautla,21054,0.173123,0.516849,Industrial ecosystem hub,0.829322,0.791247,0.715098,400.0,2059.0,32.0,2.0,0.937500,0,1105,17
2764,2023,Hidalgo,Ixmiquilpan,13030,0.170839,0.512910,Industrial ecosystem hub,0.818381,0.791247,0.903282,629.0,1392.0,233.0,2.0,0.991416,0,1114,18
2837,2023,Chiapas,Teopisca,07094,0.166637,0.505908,Industrial ecosystem hub,0.798249,0.791247,0.735230,588.0,1223.0,40.0,2.0,0.950000,0,1130,19
2718,2023,Hidalgo,San Agustín Tlaxiaca,13052,0.165815,0.504158,Industrial ecosystem hub,0.794311,0.791247,0.694530,165.0,1327.0,39.0,2.0,0.948718,0,1134,20

Intermediate / monitor

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
2880,2023,Oaxaca,Heroica Ciudad de Tlaxiaco,20397,0.156496,0.477024,Intermediate / monitor,0.749672,0.791247,0.911597,324.0,745.0,160.0,2.0,0.987500,0,1196,1
2920,2023,Veracruz de Ignacio de la Llave,Xico,30092,0.155491,0.472210,Intermediate / monitor,0.744858,0.791247,0.748796,364.0,946.0,43.0,2.0,0.953488,0,1207,2
2960,2023,Guerrero,Tixtla de Guerrero,12061,0.154852,0.470022,Intermediate / monitor,0.741794,0.791247,0.788621,855.0,1356.0,61.0,2.0,0.967213,0,1212,3
2763,2023,Coahuila de Zaragoza,Allende,05003,0.153847,0.467396,Intermediate / monitor,0.736980,0.791247,0.742670,68.0,1913.0,33.0,2.0,0.939394,0,1218,4
2762,2023,San Luis Potosí,Mexquitic de Carmona,24021,0.153299,0.466083,Intermediate / monitor,0.734354,0.791247,0.386871,20.0,3530.0,6.0,2.0,0.666667,0,1221,5
2950,2023,Morelos,Axochiapan,17003,0.151837,0.460394,Intermediate / monitor,0.727352,0.791247,0.797374,292.0,704.0,67.0,2.0,0.970149,0,1234,6
2770,2023,Michoacán de Ocampo,Los Reyes,16075,0.151380,0.459081,Intermediate / monitor,0.725164,0.791247,0.887527,501.0,1075.0,165.0,2.0,0.987879,0,1237,7
2712,2023,Sonora,Huatabampo,26033,0.150375,0.456018,Intermediate / monitor,0.720350,0.791247,0.844639,297.0,1352.0,77.0,2.0,0.974026,0,1244,8
2894,2023,Tabasco,Teapa,27016,0.149461,0.453392,Intermediate / monitor,0.715974,0.791247,0.822319,154.0,595.0,69.0,2.0,0.971014,0,1250,9
2674,2023,Jalisco,San Julián,14074,0.148457,0.450328,Intermediate / monitor,0.711160,0.791247,0.726477,156.0,795.0,33.0,2.0,0.939394,0,1257,10
3032,2023,Guerrero,San Marcos,12053,0.147086,0.446389,Intermediate / monitor,0.704595,0.791247,0.749672,243.0,543.0,47.0,2.0,0.957447,0,1266,11
3133,2023,Oaxaca,San Juan Cotzocón,20190,0.146812,0.445514,Intermediate / monitor,0.703282,0.791247,0.729978,809.0,1007.0,31.0,2.0,0.935484,0,1268,12
3013,2023,Guerrero,Arcelia,12007,0.146538,0.444201,Intermediate / monitor,0.701969,0.791247,0.815317,227.0,577.0,62.0,2.0,0.967742,0,1271,13
3027,2023,Tabasco,Emiliano Zapata,27007,0.144711,0.438074,Intermediate / monitor,0.693217,0.791247,0.859519,244.0,491.0,89.0,2.0,0.977528,0,1285,14
2848,2023,México,Tejupilco,15082,0.141605,0.430635,Intermediate / monitor,0.678337,0.791247,0.874398,302.0,797.0,134.0,2.0,0.985075,0,1302,15
3068,2023,Chiapas,Motozintla,07057,0.141513,0.430197,Intermediate / monitor,0.677899,0.791247,0.867396,259.0,515.0,110.0,2.0,0.981818,0,1303,16
3072,2023,Michoacán de Ocampo,Ario,16009,0.136671,0.416630,Intermediate / monitor,0.654705,0.791247,0.781182,169.0,427.0,52.0,2.0,0.961538,0,1334,17
3077,2023,Oaxaca,Matías Romero Avendaño,20057,0.136580,0.415755,Intermediate / monitor,0.654267,0.791247,0.858643,245.0,488.0,93.0,2.0,0.978495,0,1336,18
2800,2023,Chihuahua,Aldama,08002,0.134376,0.410066,Intermediate / monitor,0.746171,0.819912,0.651204,77.0,779.0,20.0,1.0,0.950000,0,1349,19
3047,2023,Colima,Comala,06003,0.134113,0.409628,Intermediate / monitor,0.642451,0.791247,0.628884,144.0,446.0,20.0,2.0,0.900000,0,1350,20

Lower initial priority

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
3436,2023,Puebla,Huaquechula,21069,0.329068,0.781619,Lower initial priority,0.499781,0.341575,0.702407,125.0,251.0,28.0,0.0,1.0,1,500,1
3393,2023,San Luis Potosí,Xilitla,24054,0.328780,0.781182,Lower initial priority,0.499344,0.341575,0.659081,74.0,197.0,29.0,0.0,1.0,1,501,2
3416,2023,Hidalgo,Huautla,13025,0.328492,0.780744,Lower initial priority,0.498906,0.341575,0.542888,88.0,172.0,14.0,0.0,1.0,1,502,3
3449,2023,Veracruz de Ignacio de la Llave,Chocamán,30062,0.328204,0.780306,Lower initial priority,0.498468,0.341575,0.579431,96.0,212.0,17.0,0.0,1.0,1,503,4
3479,2023,Oaxaca,Santo Tomás Jalieza,20530,0.327916,0.779869,Lower initial priority,0.498031,0.341575,0.229103,187.0,381.0,2.0,0.0,1.0,1,504,5
3607,2023,Oaxaca,Santo Tomás Mazaltepec,20531,0.327627,0.779431,Lower initial priority,0.497593,0.341575,0.123414,185.0,240.0,2.0,0.0,1.0,1,505,6
3361,2023,Michoacán de Ocampo,Madero,16049,0.327339,0.778993,Lower initial priority,0.497155,0.341575,0.585558,83.0,187.0,20.0,0.0,1.0,1,506,7
3446,2023,Oaxaca,San Francisco Ixhuatán,20143,0.327051,0.778556,Lower initial priority,0.496718,0.341575,0.563239,146.0,227.0,17.0,0.0,1.0,1,507,8
3410,2023,Oaxaca,Santa Catarina Mechoacán,20367,0.326475,0.778118,Lower initial priority,0.495842,0.341575,0.445952,234.0,331.0,8.0,0.0,1.0,1,508,9
3471,2023,Veracruz de Ignacio de la Llave,Soteapan,30149,0.326187,0.777681,Lower initial priority,0.495405,0.341575,0.379212,117.0,262.0,17.0,0.0,1.0,1,509,10
3409,2023,Tlaxcala,Sanctórum de Lázaro Cárdenas,29020,0.325899,0.777243,Lower initial priority,0.494967,0.341575,0.413129,88.0,242.0,7.0,0.0,1.0,1,510,11
3447,2023,Oaxaca,San Andrés Huaxpaltepec,20090,0.325610,0.776805,Lower initial priority,0.494530,0.341575,0.533479,85.0,170.0,13.0,0.0,1.0,1,511,12
3429,2023,Puebla,Huehuetlán el Chico,21073,0.325322,0.776368,Lower initial priority,0.494092,0.341575,0.390372,82.0,198.0,6.0,0.0,1.0,1,512,13
3375,2023,Jalisco,Huejuquilla el Alto,14042,0.325034,0.775930,Lower initial priority,0.493654,0.341575,0.631072,57.0,169.0,18.0,0.0,1.0,1,513,14
3402,2023,Puebla,Zapotitlán,21209,0.324746,0.775492,Lower initial priority,0.493217,0.341575,0.346389,86.0,236.0,7.0,0.0,1.0,1,514,15
3505,2023,Oaxaca,Santo Domingo Tomaltepec,20519,0.324458,0.775055,Lower initial priority,0.492779,0.341575,0.210722,97.0,239.0,3.0,0.0,1.0,1,515,16
3525,2023,Michoacán de Ocampo,Juárez,16046,0.324170,0.774617,Lower initial priority,0.492341,0.341575,0.325821,75.0,171.0,7.0,0.0,1.0,1,516,17
3407,2023,Veracruz de Ignacio de la Llave,Coacoatzintla,30036,0.323881,0.774179,Lower initial priority,0.491904,0.341575,0.361269,74.0,181.0,5.0,0.0,1.0,1,517,18
3433,2023,Puebla,Vicente Guerrero,21195,0.323593,0.773742,Lower initial priority,0.491466,0.341575,0.300219,73.0,223.0,5.0,0.0,1.0,1,518,19
3287,2023,Guerrero,Tepecoacuilco de Trujano,12059,0.323305,0.773304,Lower initial priority,0.491028,0.341575,0.540044,109.0,285.0,19.0,0.0,1.0,1,519,20

Priority opportunity

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
2515,2023,Hidalgo,Zacualtipán de Ángeles,13081,0.592150,0.995624,Priority opportunity,0.899344,0.341575,0.803939,363.0,3258.0,74.0,0.0,1.0,1,11,1
2494,2023,Guanajuato,San Felipe,11030,0.589268,0.995186,Priority opportunity,0.894967,0.341575,0.866958,347.0,4315.0,100.0,0.0,1.0,1,12,2
2500,2023,Tlaxcala,Tlaxco,29034,0.587251,0.994748,Priority opportunity,0.891904,0.341575,0.779869,343.0,3007.0,46.0,0.0,1.0,1,13,3
2497,2023,Aguascalientes,Rincón de Romos,01007,0.585522,0.994311,Priority opportunity,0.889278,0.341575,0.695405,226.0,2767.0,57.0,0.0,1.0,1,14,4
2524,2023,Guanajuato,Abasolo,11001,0.581488,0.993873,Priority opportunity,0.883151,0.341575,0.863020,286.0,2269.0,88.0,0.0,1.0,1,15,5
2635,2023,Yucatán,Tekit,31080,0.580336,0.993435,Priority opportunity,0.881400,0.341575,0.426477,1156.0,2782.0,7.0,0.0,1.0,1,16,6
2551,2023,Tlaxcala,Tepetitla de Lardizábal,29019,0.579471,0.992998,Priority opportunity,0.880088,0.341575,0.545295,295.0,1708.0,29.0,0.0,1.0,1,17,7
2670,2023,Yucatán,Tekax,31079,0.579183,0.992560,Priority opportunity,0.879650,0.341575,0.770241,1171.0,3166.0,55.0,0.0,1.0,1,18,8
2731,2023,Michoacán de Ocampo,Nahuatzen,16056,0.578030,0.992123,Priority opportunity,0.877899,0.341575,0.503282,1748.0,2873.0,39.0,0.0,1.0,1,19,9
2531,2023,Tlaxcala,La Magdalena Tlaltelulco,29048,0.577166,0.991685,Priority opportunity,0.876586,0.341575,0.590372,242.0,1990.0,25.0,0.0,1.0,1,20,10
2634,2023,Michoacán de Ocampo,Chilchota,16025,0.576878,0.991247,Priority opportunity,0.876149,0.341575,0.496280,2114.0,3680.0,30.0,0.0,1.0,1,21,11
2565,2023,Zacatecas,Jerez,32020,0.576302,0.990810,Priority opportunity,0.875274,0.341575,0.887090,536.0,2820.0,163.0,0.0,1.0,1,22,12
2558,2023,México,Almoloya de Juárez,15005,0.575725,0.990372,Priority opportunity,0.874398,0.341575,0.812691,427.0,1666.0,117.0,0.0,1.0,1,23,13
2662,2023,Michoacán de Ocampo,Paracho,16065,0.575149,0.989934,Priority opportunity,0.873523,0.341575,0.805252,1155.0,2262.0,58.0,0.0,1.0,1,24,14
2719,2023,Guerrero,Ometepec,12046,0.574573,0.989497,Priority opportunity,0.872648,0.341575,0.860394,2227.0,3237.0,127.0,0.0,1.0,1,25,15
2589,2023,Tlaxcala,Santa Cruz Quilehtla,29059,0.571115,0.989059,Priority opportunity,0.867396,0.341575,0.396061,224.0,2746.0,8.0,0.0,1.0,1,26,16
2761,2023,Michoacán de Ocampo,Quiroga,16073,0.570250,0.988621,Priority opportunity,0.866083,0.341575,0.701532,1692.0,3203.0,34.0,0.0,1.0,1,27,17
2512,2023,Jalisco,Ixtlahuacán de los Membrillos,14044,0.569962,0.988184,Priority opportunity,0.865646,0.341575,0.733479,90.0,4567.0,30.0,0.0,1.0,1,28,18
2605,2023,Jalisco,San Ignacio Cerro Gordo,14125,0.569098,0.987746,Priority opportunity,0.864333,0.341575,0.647702,307.0,1447.0,25.0,0.0,1.0,1,29,19
2598,2023,Yucatán,Halachó,31033,0.568233,0.987309,Priority opportunity,0.863020,0.341575,0.343107,461.0,2590.0,8.0,0.0,1.0,1,30,20

Service hub, lower industrial demand

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
3456,2023,Guerrero,Tecoanapa,12056,0.102138,0.308534,"Service hub, lower industrial demand",0.489278,0.791247,0.470897,90.0,190.0,13.0,2.0,0.846154,0,1581,1
3369,2023,Chiapas,Juárez,07048,0.099123,0.298031,"Service hub, lower industrial demand",0.474836,0.791247,0.641138,83.0,200.0,19.0,2.0,0.894737,0,1605,2
3400,2023,Campeche,Candelaria,04011,0.097113,0.291028,"Service hub, lower industrial demand",0.465208,0.791247,0.755361,73.0,191.0,35.0,2.0,0.942857,0,1621,3
3242,2023,Veracruz de Ignacio de la Llave,Angel R. Cabada,30015,0.089374,0.265208,"Service hub, lower industrial demand",0.496280,0.819912,0.736543,96.0,241.0,32.0,1.0,0.968750,0,1680,4
3568,2023,México,Villa de Allende,15111,0.088800,0.262582,"Service hub, lower industrial demand",0.425383,0.791247,0.587746,58.0,129.0,18.0,2.0,0.888889,0,1686,5
3530,2023,Chiapas,Socoltenango,07083,0.087338,0.258206,"Service hub, lower industrial demand",0.418381,0.791247,0.568490,62.0,140.0,14.0,2.0,0.857143,0,1696,6
3426,2023,Tamaulipas,Xicoténcatl,28043,0.084015,0.246389,"Service hub, lower industrial demand",0.466521,0.819912,0.709409,74.0,155.0,27.0,1.0,0.962963,0,1723,7
3674,2023,Guerrero,La Unión de Isidoro Montes de Oca,12068,0.083501,0.244201,"Service hub, lower industrial demand",0.400000,0.791247,0.503720,48.0,103.0,8.0,2.0,0.750000,0,1728,8
3627,2023,Nuevo León,General Bravo,19020,0.081857,0.238074,"Service hub, lower industrial demand",0.392123,0.791247,0.538293,24.0,80.0,12.0,2.0,0.833333,0,1742,9
3513,2023,Veracruz de Ignacio de la Llave,Atzacan,30022,0.080389,0.232385,"Service hub, lower industrial demand",0.446389,0.819912,0.522976,73.0,162.0,14.0,1.0,0.928571,0,1755,10
3521,2023,Veracruz de Ignacio de la Llave,Actopan,30004,0.080074,0.231510,"Service hub, lower industrial demand",0.444639,0.819912,0.491247,80.0,194.0,12.0,1.0,0.916667,0,1757,11
3514,2023,Zacatecas,Luis Moya,32025,0.079128,0.227571,"Service hub, lower industrial demand",0.439387,0.819912,0.546608,55.0,152.0,11.0,1.0,0.909091,0,1766,12
3455,2023,Michoacán de Ocampo,Tanhuato,16086,0.077315,0.223195,"Service hub, lower industrial demand",0.429322,0.819912,0.655580,48.0,180.0,24.0,1.0,0.958333,0,1776,13
3592,2023,Chiapas,Ángel Albino Corzo,07008,0.071716,0.203501,"Service hub, lower industrial demand",0.343545,0.791247,0.784683,30.0,103.0,53.0,2.0,0.962264,0,1821,14
3634,2023,Morelos,Amacuzac,17001,0.070695,0.200000,"Service hub, lower industrial demand",0.392560,0.819912,0.570241,45.0,116.0,14.0,1.0,0.928571,0,1829,15
3483,2023,Sonora,San Ignacio Río Muerto,26072,0.069206,0.194311,"Service hub, lower industrial demand",0.449891,0.846171,0.464989,70.0,174.0,7.0,2.0,0.714286,0,1842,16
3388,2023,Nuevo León,Lampazos de Naranjo,19032,0.067300,0.187746,"Service hub, lower industrial demand",0.483589,0.860832,0.466521,24.0,133.0,7.0,3.0,0.571429,0,1857,17
3663,2023,Zacatecas,Cuauhtémoc,32008,0.066518,0.185120,"Service hub, lower industrial demand",0.369365,0.819912,0.492779,41.0,113.0,11.0,1.0,0.909091,0,1863,18
3652,2023,Michoacán de Ocampo,Contepec,16017,0.061474,0.170678,"Service hub, lower industrial demand",0.341357,0.819912,0.605689,32.0,132.0,20.0,1.0,0.950000,0,1896,19
3371,2023,Quintana Roo,José María Morelos,23006,0.061193,0.169803,"Service hub, lower industrial demand",0.466083,0.868709,0.666083,107.0,258.0,22.0,2.0,0.909091,0,1898,20

Top priority opportunity

,year,entidad_name,municipio_name,geo_key,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_category,industrial_demand_percentile,scaled_b2b_supply_percentile,b2b_supply_percentile,total_manufacturing_establishments,total_manufacturing_employment,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,rank_opportunity_score_within_year,rank_within_category_year
2356,2023,Tlaxcala,Huamantla,29013,0.631050,1.000000,Top priority opportunity,0.958425,0.341575,0.892779,856.0,8708.0,158.0,0.0,1.0,1,1,1
2326,2023,San Luis Potosí,Villa de Pozos,24059,0.630762,0.999562,Top priority opportunity,0.957987,0.341575,0.028665,460.0,15911.0,0.0,0.0,NaN,0,2,2
2376,2023,Yucatán,Kanasín,31041,0.622694,0.999125,Top priority opportunity,0.945733,0.341575,0.844201,563.0,8973.0,68.0,0.0,1.0,1,3,3
2403,2023,Jalisco,Arandas,14008,0.622406,0.998687,Top priority opportunity,0.945295,0.341575,0.884902,502.0,7271.0,219.0,0.0,1.0,1,4,4
2393,2023,Tlaxcala,Papalotla de Xicohténcatl,29041,0.619812,0.998249,Top priority opportunity,0.941357,0.341575,0.720788,461.0,9879.0,36.0,0.0,1.0,1,5,5
2434,2023,Tlaxcala,Teolocholco,29028,0.603100,0.997812,Top priority opportunity,0.915974,0.341575,0.637199,252.0,6529.0,43.0,0.0,1.0,1,6,6
2523,2023,Puebla,Ajalpan,21010,0.602235,0.997374,Top priority opportunity,0.914661,0.341575,0.751422,2288.0,7759.0,63.0,0.0,1.0,1,7,7
2508,2023,Tlaxcala,Contla de Juan Cuamatzi,29018,0.599065,0.996937,Top priority opportunity,0.909847,0.341575,0.683589,713.0,3501.0,63.0,0.0,1.0,1,8,8
2469,2023,Tlaxcala,Ixtacuixtla de Mariano Matamoros,29015,0.598489,0.996499,Top priority opportunity,0.908972,0.341575,0.546171,371.0,3145.0,44.0,0.0,1.0,1,9,9
2505,2023,Veracruz de Ignacio de la Llave,Tres Valles,30207,0.597337,0.996061,Top priority opportunity,0.907221,0.341575,0.791247,275.0,2053.0,53.0,0.0,1.0,1,10,10

In [ ]:
# ============================================================
# 09. SCORE DEFINITIVO V2: AJUSTE DE CEROS EN OFERTA B2B ESCALADA
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
# NO GUARDA ARCHIVOS.
#
# Objetivo:
# Comparar:
# - V1: percentil tradicional con rank(pct=True, method="average")
# - V2: ceros explícitos en scaled B2B supply:
#       si b2b_scaled_capacity_proxy == 0 -> scaled_b2b_supply_percentile_v2 = 0
#       si b2b_scaled_capacity_proxy > 0  -> percentil anual entre positivos
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

print("Input path:")
print(input_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Definir variables y pesos
# ------------------------------------------------------------

demand_features = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

demand_weights = {
    "total_manufacturing_establishments": 0.25,
    "total_manufacturing_employment": 0.20,
    "total_manufacturing_value_added": 0.25,
    "total_manufacturing_income": 0.20,
    "total_manufacturing_investment": 0.10
}

b2b_supply_features = [
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes"
]

b2b_supply_weights = {
    "denue_logistics_storage_establishments": 0.35,
    "denue_professional_technical_establishments": 0.25,
    "denue_business_support_establishments": 0.20,
    "denue_b2b_support_scian_classes": 0.20
}

scaled_features = [
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "denue_b2b_support_establishments",
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments"
]

required_cols = (
    ["year", "entidad_id", "entidad_name", "municipio_id", "municipio_name", "geo_key"]
    + demand_features
    + b2b_supply_features
    + scaled_features
)

missing_cols = [col for col in required_cols if col not in df.columns]

if missing_cols:
    raise ValueError(f"Faltan columnas necesarias: {missing_cols}")

if not np.isclose(sum(demand_weights.values()), 1.0):
    raise ValueError("Los pesos de demanda no suman 1.")

if not np.isclose(sum(b2b_supply_weights.values()), 1.0):
    raise ValueError("Los pesos de oferta B2B no suman 1.")


# ------------------------------------------------------------
# 4. Convertir variables a numéricas
# ------------------------------------------------------------

numeric_cols = list(set(demand_features + b2b_supply_features + scaled_features))

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_numeric = df[numeric_cols].isna().sum()

if missing_numeric.sum() > 0:
    print("Missing detectados:")
    print(missing_numeric[missing_numeric > 0])
    raise ValueError(
        "Hay missing en variables necesarias. "
        "Revisa que estés usando 08_modeling_base_complete_cases.csv."
    )


# ------------------------------------------------------------
# 5. Industrial demand score
# ------------------------------------------------------------

for col in demand_features:
    percentile_col = f"{col}_demand_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["industrial_demand_score"] = 0.0

for col, weight in demand_weights.items():
    df["industrial_demand_score"] += (
        df[f"{col}_demand_percentile"] * weight
    )

df["industrial_demand_percentile"] = (
    df
    .groupby("year")["industrial_demand_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 6. B2B supply score general
# ------------------------------------------------------------

for col in b2b_supply_features:
    percentile_col = f"{col}_b2b_supply_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["b2b_supply_score"] = 0.0

for col, weight in b2b_supply_weights.items():
    df["b2b_supply_score"] += (
        df[f"{col}_b2b_supply_percentile"] * weight
    )

df["b2b_supply_percentile"] = (
    df
    .groupby("year")["b2b_supply_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 7. Oferta B2B escalada: proxy de capacidad
# ------------------------------------------------------------

medium_expected_workers = 65.5
large_expected_workers = 150

df["b2b_scaled_capacity_proxy"] = (
    medium_expected_workers * df["denue_b2b_medium_establishments"]
    + large_expected_workers * df["denue_b2b_large_establishments"]
)

df["has_scaled_b2b_supply"] = (
    df["b2b_scaled_capacity_proxy"] > 0
).astype(int)


# ------------------------------------------------------------
# 8. Scaled B2B supply V1: método anterior
# ------------------------------------------------------------

df["scaled_b2b_supply_percentile_v1"] = (
    df
    .groupby("year")["b2b_scaled_capacity_proxy"]
    .rank(pct=True, method="average")
)

df["industrial_b2b_opportunity_score_v1"] = (
    df["industrial_demand_percentile"]
    * (1 - df["scaled_b2b_supply_percentile_v1"])
)

df["industrial_b2b_opportunity_percentile_v1"] = (
    df
    .groupby("year")["industrial_b2b_opportunity_score_v1"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 9. Scaled B2B supply V2: ceros explícitos
# ------------------------------------------------------------

df["scaled_b2b_supply_percentile_v2"] = np.nan

for year_value, idx in df.groupby("year").groups.items():
    year_mask = df.index.isin(idx)
    positive_mask = year_mask & (df["b2b_scaled_capacity_proxy"] > 0)
    zero_mask = year_mask & (df["b2b_scaled_capacity_proxy"] == 0)

    # Ceros explícitos: ausencia de oferta escalada
    df.loc[zero_mask, "scaled_b2b_supply_percentile_v2"] = 0.0

    # Positivos: percentil anual solo entre municipios con oferta escalada positiva
    df.loc[positive_mask, "scaled_b2b_supply_percentile_v2"] = (
        df.loc[positive_mask, "b2b_scaled_capacity_proxy"]
        .rank(pct=True, method="average")
    )

df["industrial_b2b_opportunity_score_v2"] = (
    df["industrial_demand_percentile"]
    * (1 - df["scaled_b2b_supply_percentile_v2"])
)

df["industrial_b2b_opportunity_percentile_v2"] = (
    df
    .groupby("year")["industrial_b2b_opportunity_score_v2"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 10. Variables auxiliares de atomización
# ------------------------------------------------------------

df["b2b_micro_small_establishments"] = (
    df["denue_b2b_micro_establishments"]
    + df["denue_b2b_small_establishments"]
)

df["b2b_micro_small_share"] = np.where(
    df["denue_b2b_support_establishments"] > 0,
    df["b2b_micro_small_establishments"] / df["denue_b2b_support_establishments"],
    np.nan
)

df["only_micro_small_b2b_supply"] = (
    (df["denue_b2b_support_establishments"] > 0) &
    (df["denue_b2b_medium_large_establishments"] == 0)
).astype(int)


# ------------------------------------------------------------
# 11. Categorías con V2
# ------------------------------------------------------------

def classify_opportunity_v2(row):
    demand_p = row["industrial_demand_percentile"]
    scaled_p = row["scaled_b2b_supply_percentile_v2"]

    if demand_p >= 0.90 and scaled_p < 0.50:
        return "Top priority opportunity"

    elif demand_p >= 0.75 and scaled_p < 0.50:
        return "Priority opportunity"

    elif demand_p >= 0.75 and scaled_p >= 0.75:
        return "Industrial ecosystem hub"

    elif demand_p >= 0.50 and scaled_p < 0.75:
        return "Developing industrial market"

    elif demand_p < 0.50 and scaled_p >= 0.75:
        return "Service hub, lower industrial demand"

    elif demand_p < 0.50 and scaled_p < 0.75:
        return "Lower initial priority"

    else:
        return "Intermediate / monitor"


df["industrial_b2b_opportunity_category_v2"] = (
    df.apply(classify_opportunity_v2, axis=1)
)


# ------------------------------------------------------------
# 12. Subtipos de oportunidad con V2
# ------------------------------------------------------------

def classify_opportunity_subtype_v2(row):
    category = row["industrial_b2b_opportunity_category_v2"]
    b2b_general_p = row["b2b_supply_percentile"]
    b2b_total = row["denue_b2b_support_establishments"]
    medium_large = row["denue_b2b_medium_large_establishments"]

    opportunity_categories = [
        "Top priority opportunity",
        "Priority opportunity",
        "Developing industrial market"
    ]

    if category not in opportunity_categories:
        return "Not opportunity subtype"

    if medium_large == 0 and b2b_total > 0 and b2b_general_p >= 0.75:
        return "Atomized B2B opportunity"

    elif medium_large == 0 and b2b_total > 0 and b2b_general_p < 0.75:
        return "Limited scaled B2B opportunity"

    elif medium_large == 0 and b2b_total == 0:
        return "Broad B2B gap"

    elif medium_large > 0 and row["scaled_b2b_supply_percentile_v2"] < 0.50:
        return "Low scaled B2B opportunity"

    else:
        return "Mixed opportunity case"


df["industrial_b2b_opportunity_subtype_v2"] = (
    df.apply(classify_opportunity_subtype_v2, axis=1)
)


# ------------------------------------------------------------
# 13. Tabla diagnóstica compacta
# ------------------------------------------------------------

review_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",

    "industrial_demand_percentile",
    "b2b_supply_percentile",

    "b2b_scaled_capacity_proxy",
    "scaled_b2b_supply_percentile_v1",
    "scaled_b2b_supply_percentile_v2",

    "industrial_b2b_opportunity_score_v1",
    "industrial_b2b_opportunity_percentile_v1",
    "industrial_b2b_opportunity_score_v2",
    "industrial_b2b_opportunity_percentile_v2",

    "industrial_b2b_opportunity_category_v2",
    "industrial_b2b_opportunity_subtype_v2",

    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",

    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "b2b_micro_small_share",
    "only_micro_small_b2b_supply"
]

score_diagnostic_v2 = df[review_cols].copy()


# ------------------------------------------------------------
# 14. Rankings comparativos
# ------------------------------------------------------------

# Ranking V1
ranking_v1 = (
    score_diagnostic_v2
    .sort_values(
        ["year", "industrial_b2b_opportunity_score_v1"],
        ascending=[True, False]
    )
    .copy()
)

ranking_v1["rank_v1"] = (
    ranking_v1
    .groupby("year")
    .cumcount() + 1
)

# Ranking V2
ranking_v2 = (
    score_diagnostic_v2
    .sort_values(
        ["year", "industrial_b2b_opportunity_score_v2"],
        ascending=[True, False]
    )
    .copy()
)

ranking_v2["rank_v2"] = (
    ranking_v2
    .groupby("year")
    .cumcount() + 1
)

# Comparación de rankings
rank_compare = (
    ranking_v2[
        [
            "year",
            "geo_key",
            "entidad_name",
            "municipio_name",
            "rank_v2",
            "industrial_b2b_opportunity_score_v2",
            "industrial_b2b_opportunity_category_v2",
            "industrial_b2b_opportunity_subtype_v2",
            "industrial_demand_percentile",
            "scaled_b2b_supply_percentile_v2",
            "b2b_supply_percentile",
            "denue_b2b_support_establishments",
            "denue_b2b_medium_large_establishments",
            "b2b_micro_small_share"
        ]
    ]
    .merge(
        ranking_v1[["year", "geo_key", "rank_v1", "industrial_b2b_opportunity_score_v1"]],
        on=["year", "geo_key"],
        how="left"
    )
)

rank_compare["rank_change_v2_minus_v1"] = (
    rank_compare["rank_v2"] - rank_compare["rank_v1"]
)


# ------------------------------------------------------------
# 15. Resúmenes
# ------------------------------------------------------------

zero_summary = (
    df
    .groupby("year")
    .agg(
        n_municipality_years=("geo_key", "size"),
        n_zero_scaled_capacity=("has_scaled_b2b_supply", lambda x: (x == 0).sum()),
        n_positive_scaled_capacity=("has_scaled_b2b_supply", "sum"),
        avg_scaled_percentile_v1_for_zeros=(
            "scaled_b2b_supply_percentile_v1",
            lambda x: x[df.loc[x.index, "has_scaled_b2b_supply"] == 0].mean()
        ),
        avg_scaled_percentile_v2_for_zeros=(
            "scaled_b2b_supply_percentile_v2",
            lambda x: x[df.loc[x.index, "has_scaled_b2b_supply"] == 0].mean()
        )
    )
    .reset_index()
)

zero_summary["share_zero_scaled_capacity"] = (
    zero_summary["n_zero_scaled_capacity"] /
    zero_summary["n_municipality_years"]
)

category_summary_v2 = (
    score_diagnostic_v2
    .groupby(["year", "industrial_b2b_opportunity_category_v2"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        avg_opportunity_score_v2=("industrial_b2b_opportunity_score_v2", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_scaled_b2b_supply_percentile_v2=("scaled_b2b_supply_percentile_v2", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_manufacturing_establishments=("total_manufacturing_establishments", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean"),
        avg_micro_small_share=("b2b_micro_small_share", "mean")
    )
    .reset_index()
)

subtype_summary_v2 = (
    score_diagnostic_v2
    .groupby(["year", "industrial_b2b_opportunity_subtype_v2"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        avg_opportunity_score_v2=("industrial_b2b_opportunity_score_v2", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_scaled_b2b_supply_percentile_v2=("scaled_b2b_supply_percentile_v2", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 16. Tablas de revisión
# ------------------------------------------------------------

top_v2 = (
    rank_compare
    .sort_values(["year", "rank_v2"])
    .groupby("year")
    .head(40)
    .reset_index(drop=True)
)

top_opportunity_categories_v2 = (
    rank_compare[
        rank_compare["industrial_b2b_opportunity_category_v2"].isin(
            [
                "Top priority opportunity",
                "Priority opportunity",
                "Developing industrial market"
            ]
        )
    ]
    .sort_values(["year", "rank_v2"])
    .groupby("year")
    .head(50)
    .reset_index(drop=True)
)

atomized_opportunities_v2 = (
    rank_compare[
        rank_compare["industrial_b2b_opportunity_subtype_v2"]
        == "Atomized B2B opportunity"
    ]
    .sort_values(["year", "rank_v2"])
    .groupby("year")
    .head(30)
    .reset_index(drop=True)
)

broad_gap_opportunities_v2 = (
    rank_compare[
        rank_compare["industrial_b2b_opportunity_subtype_v2"]
        == "Broad B2B gap"
    ]
    .sort_values(["year", "rank_v2"])
    .groupby("year")
    .head(30)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 17. Mostrar resultados
# ------------------------------------------------------------

print("\nAJUSTE METODOLÓGICO V2")
print("=" * 100)
print("V1: percentil tradicional con empates promedio.")
print("V2: b2b_scaled_capacity_proxy == 0 recibe scaled_b2b_supply_percentile_v2 = 0.")
print("Para valores positivos, el percentil se calcula dentro de los municipios con proxy positiva.")
print(f"Medium expected workers: {medium_expected_workers}")
print(f"Large expected workers: {large_expected_workers}")

print("\nRESUMEN DE CEROS EN OFERTA B2B ESCALADA")
print("=" * 100)
display(zero_summary)

print("\nRESUMEN POR CATEGORÍA V2")
print("=" * 100)
display(category_summary_v2)

print("\nRESUMEN POR SUBTIPO V2")
print("=" * 100)
display(subtype_summary_v2)

print("\nTOP RANKING V2 POR INDUSTRIAL_B2B_OPPORTUNITY_SCORE")
print("=" * 100)
display(top_v2)

print("\nTOP SOLO CATEGORÍAS DE OPORTUNIDAD V2")
print("=" * 100)
display(top_opportunity_categories_v2)

print("\nATOMIZED B2B OPPORTUNITIES V2")
print("=" * 100)
display(atomized_opportunities_v2)

print("\nBROAD B2B GAP OPPORTUNITIES V2")
print("=" * 100)
display(broad_gap_opportunities_v2)

print("\nVALIDACIÓN RÁPIDA")
print("=" * 100)
print("Filas diagnosticadas:", len(score_diagnostic_v2))
print("Missing scaled_b2b_supply_percentile_v2:", score_diagnostic_v2["scaled_b2b_supply_percentile_v2"].isna().sum())
print("Missing industrial_b2b_opportunity_score_v2:", score_diagnostic_v2["industrial_b2b_opportunity_score_v2"].isna().sum())
print("Años:", sorted(score_diagnostic_v2["year"].dropna().unique()))

Google Drive ya está disponible en: /content/drive/MyDrive
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Base cargada:
Filas: 4,530
Columnas: 54

AJUSTE METODOLÓGICO V2
====================================================================================================
V1: percentil tradicional con empates promedio.
V2: b2b_scaled_capacity_proxy == 0 recibe scaled_b2b_supply_percentile_v2 = 0.
Para valores positivos, el percentil se calcula dentro de los municipios con proxy positiva.
Medium expected workers: 65.5
Large expected workers: 150

RESUMEN DE CEROS EN OFERTA B2B ESCALADA
====================================================================================================

,year,n_municipality_years,n_zero_scaled_capacity,n_positive_scaled_capacity,avg_scaled_percentile_v1_for_zeros,avg_scaled_percentile_v2_for_zeros,share_zero_scaled_capacity
0,2018,2245,1589,656,0.354120,0.0,0.707795
1,2023,2285,1560,725,0.341575,0.0,0.682713

RESUMEN POR CATEGORÍA V2
====================================================================================================

,year,industrial_b2b_opportunity_category_v2,n_municipality_years,avg_opportunity_score_v2,avg_industrial_demand_percentile,avg_scaled_b2b_supply_percentile_v2,avg_b2b_supply_percentile,avg_manufacturing_establishments,avg_manufacturing_employment,avg_b2b_total,avg_b2b_medium_large,avg_micro_small_share
0,2018,Developing industrial market,672,0.516700,0.668647,0.193617,0.637374,243.049107,1363.879464,59.858631,1.337798,0.979746
1,2018,Industrial ecosystem hub,162,0.114277,0.944598,0.877113,0.953878,1565.012346,30009.592593,1086.413580,76.469136,0.927062
2,2018,Intermediate / monitor,2,0.165936,0.710579,0.766387,0.910913,295.500000,1458.000000,177.500000,11.000000,0.938024
3,2018,Lower initial priority,1122,0.245738,0.250111,0.012481,0.291417,36.622103,77.178253,6.899287,0.072193,0.991980
4,2018,Priority opportunity,258,0.710744,0.821189,0.132530,0.723372,377.321705,1761.395349,72.275194,0.658915,0.989785
5,2018,Top priority opportunity,29,0.713418,0.921780,0.226477,0.852915,794.310345,5660.862069,176.068966,1.310345,0.990035
6,2023,Developing industrial market,701,0.508602,0.670168,0.208940,0.645911,270.223966,1298.005706,55.748930,1.427960,0.975845
7,2023,Industrial ecosystem hub,184,0.117460,0.942461,0.873508,0.945881,1534.614130,30323.554348,897.070652,78.103261,0.910977
8,2023,Intermediate / monitor,1,0.149911,0.744420,0.798621,0.920350,216.000000,710.000000,175.000000,14.000000,0.920000
9,2023,Lower initial priority,1142,0.243359,0.250109,0.018300,0.289694,42.126970,88.134851,6.204028,0.091068,0.986549
10,2023,Priority opportunity,226,0.716260,0.818256,0.123247,0.706490,424.579646,1904.225664,60.163717,0.610619,0.987600
11,2023,Top priority opportunity,31,0.734919,0.919482,0.201824,0.798595,563.838710,5397.096774,111.645161,1.096774,0.987796

RESUMEN POR SUBTIPO V2
====================================================================================================

,year,industrial_b2b_opportunity_subtype_v2,n_municipality_years,avg_opportunity_score_v2,avg_industrial_demand_percentile,avg_scaled_b2b_supply_percentile_v2,avg_b2b_supply_percentile,avg_b2b_total,avg_b2b_medium_large
0,2018,Atomized B2B opportunity,96,0.753937,0.753937,0.000000,0.802566,80.760417,0.000000
1,2018,Broad B2B gap,8,0.549499,0.549499,0.000000,0.022717,0.000000,0.000000
2,2018,Limited scaled B2B opportunity,429,0.653562,0.653562,0.000000,0.525629,22.023310,0.000000
3,2018,Low scaled B2B opportunity,272,0.543410,0.748070,0.270120,0.755855,80.433824,1.411765
4,2018,Mixed opportunity case,154,0.300803,0.826635,0.632459,0.853018,161.681818,4.694805
5,2018,Not opportunity subtype,1286,0.229054,0.338313,0.122573,0.375832,143.153188,9.713064
6,2023,Atomized B2B opportunity,84,0.761954,0.761954,0.000000,0.801881,71.857143,0.000000
7,2023,Broad B2B gap,7,0.700594,0.700594,0.000000,0.028665,0.000000,0.000000
8,2023,Limited scaled B2B opportunity,408,0.651834,0.651834,0.000000,0.520696,19.247549,0.000000
9,2023,Low scaled B2B opportunity,288,0.535779,0.724807,0.256590,0.738836,63.965278,1.361111
10,2023,Mixed opportunity case,171,0.304248,0.816473,0.623856,0.844558,139.339181,4.567251
11,2023,Not opportunity subtype,1327,0.225832,0.346482,0.137470,0.381155,129.857573,10.918613

TOP RANKING V2 POR INDUSTRIAL_B2B_OPPORTUNITY_SCORE
====================================================================================================

,year,geo_key,entidad_name,municipio_name,rank_v2,industrial_b2b_opportunity_score_v2,industrial_b2b_opportunity_category_v2,industrial_b2b_opportunity_subtype_v2,industrial_demand_percentile,scaled_b2b_supply_percentile_v2,b2b_supply_percentile,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,rank_v1,industrial_b2b_opportunity_score_v1,rank_change_v2_minus_v1
0,2018,15101,México,Tianguistenco,1,0.968374,Top priority opportunity,Atomized B2B opportunity,0.968374,0.0,0.814699,167.0,0.0,1.0,1,0.625453,0
1,2018,29013,Tlaxcala,Huamantla,2,0.956793,Top priority opportunity,Atomized B2B opportunity,0.956793,0.0,0.891314,174.0,0.0,1.0,2,0.617973,0
2,2018,14008,Jalisco,Arandas,3,0.936303,Top priority opportunity,Atomized B2B opportunity,0.936303,0.0,0.854343,187.0,0.0,1.0,3,0.604739,0
3,2018,11004,Guanajuato,Apaseo el Alto,4,0.918486,Top priority opportunity,Atomized B2B opportunity,0.918486,0.0,0.861024,111.0,0.0,1.0,4,0.593231,0
4,2018,31041,Yucatán,Kanasín,5,0.909131,Top priority opportunity,Atomized B2B opportunity,0.909131,0.0,0.766592,57.0,0.0,1.0,5,0.587190,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2023,16105,Michoacán de Ocampo,Vista Hermosa,36,0.852516,Priority opportunity,Limited scaled B2B opportunity,0.852516,0.0,0.673523,22.0,0.0,1.0,36,0.561318,0
76,2023,21117,Puebla,Rafael Lara Grajales,37,0.852079,Priority opportunity,Limited scaled B2B opportunity,0.852079,0.0,0.719912,44.0,0.0,1.0,37,0.561030,0
77,2023,13029,Hidalgo,Huichapan,38,0.850328,Priority opportunity,Atomized B2B opportunity,0.850328,0.0,0.855142,89.0,0.0,1.0,38,0.559877,0
78,2023,16079,Michoacán de Ocampo,Salvador Escalante,39,0.849015,Priority opportunity,Limited scaled B2B opportunity,0.849015,0.0,0.644639,45.0,0.0,1.0,39,0.559012,0
79,2023,14046,Jalisco,Jalostotitlán,40,0.848578,Priority opportunity,Atomized B2B opportunity,0.848578,0.0,0.782495,77.0,0.0,1.0,40,0.558724,0

TOP SOLO CATEGORÍAS DE OPORTUNIDAD V2
====================================================================================================

,year,geo_key,entidad_name,municipio_name,rank_v2,industrial_b2b_opportunity_score_v2,industrial_b2b_opportunity_category_v2,industrial_b2b_opportunity_subtype_v2,industrial_demand_percentile,scaled_b2b_supply_percentile_v2,b2b_supply_percentile,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,rank_v1,industrial_b2b_opportunity_score_v1,rank_change_v2_minus_v1
0,2018,15101,México,Tianguistenco,1,0.968374,Top priority opportunity,Atomized B2B opportunity,0.968374,0.0,0.814699,167.0,0.0,1.0,1,0.625453,0
1,2018,29013,Tlaxcala,Huamantla,2,0.956793,Top priority opportunity,Atomized B2B opportunity,0.956793,0.0,0.891314,174.0,0.0,1.0,2,0.617973,0
2,2018,14008,Jalisco,Arandas,3,0.936303,Top priority opportunity,Atomized B2B opportunity,0.936303,0.0,0.854343,187.0,0.0,1.0,3,0.604739,0
3,2018,11004,Guanajuato,Apaseo el Alto,4,0.918486,Top priority opportunity,Atomized B2B opportunity,0.918486,0.0,0.861024,111.0,0.0,1.0,4,0.593231,0
4,2018,31041,Yucatán,Kanasín,5,0.909131,Top priority opportunity,Atomized B2B opportunity,0.909131,0.0,0.766592,57.0,0.0,1.0,5,0.587190,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023,11046,Guanajuato,Yuriria,46,0.842888,Priority opportunity,Atomized B2B opportunity,0.842888,0.0,0.850766,111.0,0.0,1.0,46,0.554978,0
96,2023,30208,Veracruz de Ignacio de la Llave,Carlos A. Carrillo,47,0.842013,Priority opportunity,Limited scaled B2B opportunity,0.842013,0.0,0.496718,14.0,0.0,1.0,47,0.554402,0
97,2023,12057,Guerrero,Técpan de Galeana,48,0.838512,Priority opportunity,Atomized B2B opportunity,0.838512,0.0,0.862582,86.0,0.0,1.0,48,0.552097,0
98,2023,30211,Veracruz de Ignacio de la Llave,San Rafael,49,0.837199,Priority opportunity,Limited scaled B2B opportunity,0.837199,0.0,0.747046,41.0,0.0,1.0,49,0.551232,0
99,2023,16058,Michoacán de Ocampo,Nuevo Parangaricutiro,50,0.836324,Priority opportunity,Limited scaled B2B opportunity,0.836324,0.0,0.651641,33.0,0.0,1.0,50,0.550656,0

ATOMIZED B2B OPPORTUNITIES V2
====================================================================================================

,year,geo_key,entidad_name,municipio_name,rank_v2,industrial_b2b_opportunity_score_v2,industrial_b2b_opportunity_category_v2,industrial_b2b_opportunity_subtype_v2,industrial_demand_percentile,scaled_b2b_supply_percentile_v2,b2b_supply_percentile,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,rank_v1,industrial_b2b_opportunity_score_v1,rank_change_v2_minus_v1
0,2018,15101,México,Tianguistenco,1,0.968374,Top priority opportunity,Atomized B2B opportunity,0.968374,0.0,0.814699,167.0,0.0,1.0,1,0.625453,0
1,2018,29013,Tlaxcala,Huamantla,2,0.956793,Top priority opportunity,Atomized B2B opportunity,0.956793,0.0,0.891314,174.0,0.0,1.0,2,0.617973,0
2,2018,14008,Jalisco,Arandas,3,0.936303,Top priority opportunity,Atomized B2B opportunity,0.936303,0.0,0.854343,187.0,0.0,1.0,3,0.604739,0
3,2018,11004,Guanajuato,Apaseo el Alto,4,0.918486,Top priority opportunity,Atomized B2B opportunity,0.918486,0.0,0.861024,111.0,0.0,1.0,4,0.593231,0
4,2018,31041,Yucatán,Kanasín,5,0.909131,Top priority opportunity,Atomized B2B opportunity,0.909131,0.0,0.766592,57.0,0.0,1.0,5,0.587190,0
5,2018,13081,Hidalgo,Zacualtipán de Ángeles,7,0.899332,Priority opportunity,Atomized B2B opportunity,0.899332,0.0,0.767929,71.0,0.0,1.0,7,0.580860,0
6,2018,14083,Jalisco,Tala,9,0.896659,Priority opportunity,Atomized B2B opportunity,0.896659,0.0,0.852116,109.0,0.0,1.0,9,0.579134,0
7,2018,04001,Campeche,Calkiní,10,0.893987,Priority opportunity,Atomized B2B opportunity,0.893987,0.0,0.797773,73.0,0.0,1.0,10,0.577408,0
8,2018,15120,México,Zumpango,11,0.891314,Priority opportunity,Atomized B2B opportunity,0.891314,0.0,0.901559,319.0,0.0,1.0,11,0.575682,0
9,2018,22007,Querétaro,Ezequiel Montes,12,0.889532,Priority opportunity,Atomized B2B opportunity,0.889532,0.0,0.838307,99.0,0.0,1.0,12,0.574531,0
10,2018,21177,Puebla,Tlacotepec de Benito Juárez,13,0.889087,Priority opportunity,Atomized B2B opportunity,0.889087,0.0,0.754566,50.0,0.0,1.0,13,0.574243,0
11,2018,30160,Veracruz de Ignacio de la Llave,Álamo Temapache,14,0.882405,Priority opportunity,Atomized B2B opportunity,0.882405,0.0,0.878842,142.0,0.0,1.0,14,0.569928,0
12,2018,29034,Tlaxcala,Tlaxco,16,0.872606,Priority opportunity,Atomized B2B opportunity,0.872606,0.0,0.753229,43.0,0.0,1.0,16,0.563598,0
13,2018,09009,Ciudad de México,Milpa Alta,17,0.872160,Priority opportunity,Atomized B2B opportunity,0.872160,0.0,0.841871,236.0,0.0,1.0,17,0.563311,0
14,2018,14015,Jalisco,Autlán de Navarro,19,0.869933,Priority opportunity,Atomized B2B opportunity,0.869933,0.0,0.874388,159.0,0.0,1.0,19,0.561872,0
15,2018,14016,Jalisco,Ayotlán,21,0.867706,Priority opportunity,Atomized B2B opportunity,0.867706,0.0,0.795991,78.0,0.0,1.0,21,0.560434,0
16,2018,11018,Guanajuato,Jaral del Progreso,29,0.857461,Priority opportunity,Atomized B2B opportunity,0.857461,0.0,0.777728,51.0,0.0,1.0,29,0.553817,0
17,2018,08045,Chihuahua,Meoqui,35,0.848998,Priority opportunity,Atomized B2B opportunity,0.848998,0.0,0.806236,55.0,0.0,1.0,35,0.548350,0
18,2018,14035,Jalisco,Encarnación de Díaz,36,0.847661,Priority opportunity,Atomized B2B opportunity,0.847661,0.0,0.819599,80.0,0.0,1.0,36,0.547487,0
19,2018,11046,Guanajuato,Yuriria,38,0.844989,Priority opportunity,Atomized B2B opportunity,0.844989,0.0,0.874833,128.0,0.0,1.0,38,0.545761,0
20,2018,31089,Yucatán,Ticul,39,0.842762,Priority opportunity,Atomized B2B opportunity,0.842762,0.0,0.773719,69.0,0.0,1.0,39,0.544323,0
21,2018,18015,Nayarit,Santiago Ixcuintla,47,0.834298,Priority opportunity,Atomized B2B opportunity,0.834298,0.0,0.888641,132.0,0.0,1.0,47,0.538856,0
22,2018,05009,Coahuila de Zaragoza,Francisco I. Madero,48,0.831626,Priority opportunity,Atomized B2B opportunity,0.831626,0.0,0.795546,61.0,0.0,1.0,48,0.537130,0
23,2018,30123,Veracruz de Ignacio de la Llave,Pánuco,49,0.831180,Priority opportunity,Atomized B2B opportunity,0.831180,0.0,0.869042,112.0,0.0,1.0,49,0.536843,0
24,2018,32036,Zacatecas,Ojocaliente,52,0.827617,Priority opportunity,Atomized B2B opportunity,0.827617,0.0,0.755902,53.0,0.0,1.0,52,0.534541,0
25,2018,10023,Durango,Pueblo Nuevo,54,0.825835,Priority opportunity,Atomized B2B opportunity,0.825835,0.0,0.762584,54.0,0.0,1.0,54,0.533390,0
26,2018,15088,México,Tenancingo,56,0.823608,Priority opportunity,Atomized B2B opportunity,0.823608,0.0,0.872606,169.0,0.0,1.0,56,0.531952,0
27,2018,24008,San Luis Potosí,Cerritos,58,0.822717,Priority opportunity,Atomized B2B opportunity,0.822717,0.0,0.806682,60.0,0.0,1.0,58,0.531376,0
28,2018,31052,Yucatán,Motul,59,0.821826,Priority opportunity,Atomized B2B opportunity,0.821826,0.0,0.785301,55.0,0.0,1.0,59,0.530801,0
29,2018,11008,Guanajuato,Manuel Doblado,61,0.820045,Priority opportunity,Atomized B2B opportunity,0.820045,0.0,0.763029,41.0,0.0,1.0,61,0.529650,0
30,2023,29013,Tlaxcala,Huamantla,1,0.958425,Top priority opportunity,Atomized B2B opportunity,0.958425,0.0,0.892779,158.0,0.0,1.0,1,0.631050,0
31,2023,31041,Yucatán,Kanasín,3,0.945733,Top priority opportunity,Atomized B2B opportunity,0.945733,0.0,0.844201,68.0,0.0,1.0,3,0.622694,0
32,2023,14008,Jalisco,Arandas,4,0.945295,Top priority opportunity,Atomized B2B opportunity,0.945295,0.0,0.884902,219.0,0.0,1.0,4,0.622406,0
33,2023,21010,Puebla,Ajalpan,7,0.914661,Top priority opportunity,Atomized B2B opportunity,0.914661,0.0,0.751422,63.0,0.0,1.0,7,0.602235,0
34,2023,30207,Veracruz de Ignacio de la Llave,Tres Valles,10,0.907221,Top priority opportunity,Atomized B2B opportunity,0.907221,0.0,0.791247,53.0,0.0,1.0,10,0.597337,0
35,2023,13081,Hidalgo,Zacualtipán de Ángeles,11,0.899344,Priority opportunity,Atomized B2B opportunity,0.899344,0.0,0.803939,74.0,0.0,1.0,11,0.592150,0
36,2023,11030,Guanajuato,San Felipe,12,0.894967,Priority opportunity,Atomized B2B opportunity,0.894967,0.0,0.866958,100.0,0.0,1.0,12,0.589268,0
37,2023,29034,Tlaxcala,Tlaxco,13,0.891904,Priority opportunity,Atomized B2B opportunity,0.891904,0.0,0.779869,46.0,0.0,1.0,13,0.587251,0
38,2023,11001,Guanajuato,Abasolo,15,0.883151,Priority opportunity,Atomized B2B opportunity,0.883151,0.0,0.863020,88.0,0.0,1.0,15,0.581488,0
39,2023,31079,Yucatán,Tekax,18,0.879650,Priority opportunity,Atomized B2B opportunity,0.879650,0.0,0.770241,55.0,0.0,1.0,18,0.579183,0
40,2023,32020,Zacatecas,Jerez,22,0.875274,Priority opportunity,Atomized B2B opportunity,0.875274,0.0,0.887090,163.0,0.0,1.0,22,0.576302,0
41,2023,15005,México,Almoloya de Juárez,23,0.874398,Priority opportunity,Atomized B2B opportunity,0.874398,0.0,0.812691,117.0,0.0,1.0,23,0.575725,0
42,2023,16065,Michoacán de Ocampo,Paracho,24,0.873523,Priority opportunity,Atomized B2B opportunity,0.873523,0.0,0.805252,58.0,0.0,1.0,24,0.575149,0
43,2023,12046,Guerrero,Ometepec,25,0.872648,Priority opportunity,Atomized B2B opportunity,0.872648,0.0,0.860394,127.0,0.0,1.0,25,0.574573,0
44,2023,13074,Hidalgo,Tlaxcoapan,33,0.854705,Priority opportunity,Atomized B2B opportunity,0.854705,0.0,0.829322,94.0,0.0,1.0,33,0.562758,0
45,2023,08011,Chihuahua,Camargo,34,0.853829,Priority opportunity,Atomized B2B opportunity,0.853829,0.0,0.864770,101.0,0.0,1.0,34,0.562182,0
46,2023,10023,Durango,Pueblo Nuevo,35,0.853392,Priority opportunity,Atomized B2B opportunity,0.853392,0.0,0.759300,45.0,0.0,1.0,35,0.561894,0
47,2023,13029,Hidalgo,Huichapan,38,0.850328,Priority opportunity,Atomized B2B opportunity,0.850328,0.0,0.855142,89.0,0.0,1.0,38,0.559877,0
48,2023,14046,Jalisco,Jalostotitlán,40,0.848578,Priority opportunity,Atomized B2B opportunity,0.848578,0.0,0.782495,77.0,0.0,1.0,40,0.558724,0
49,2023,30045,Veracruz de Ignacio de la Llave,Cosamaloapan de Carpio,41,0.848140,Priority opportunity,Atomized B2B opportunity,0.848140,0.0,0.817068,87.0,0.0,1.0,41,0.558436,0
50,2023,07009,Chiapas,Arriaga,42,0.847265,Priority opportunity,Atomized B2B opportunity,0.847265,0.0,0.843326,73.0,0.0,1.0,42,0.557860,0
51,2023,11046,Guanajuato,Yuriria,46,0.842888,Priority opportunity,Atomized B2B opportunity,0.842888,0.0,0.850766,111.0,0.0,1.0,46,0.554978,0
52,2023,12057,Guerrero,Técpan de Galeana,48,0.838512,Priority opportunity,Atomized B2B opportunity,0.838512,0.0,0.862582,86.0,0.0,1.0,48,0.552097,0
53,2023,30053,Veracruz de Ignacio de la Llave,Cuitláhuac,54,0.829759,Priority opportunity,Atomized B2B opportunity,0.829759,0.0,0.784245,43.0,0.0,1.0,54,0.546334,0
54,2023,21199,Puebla,Xiutetelco,58,0.824945,Priority opportunity,Atomized B2B opportunity,0.824945,0.0,0.754486,45.0,0.0,1.0,58,0.543164,0
55,2023,30123,Veracruz de Ignacio de la Llave,Pánuco,60,0.823195,Priority opportunity,Atomized B2B opportunity,0.823195,0.0,0.864333,102.0,0.0,1.0,60,0.542012,0
56,2023,31052,Yucatán,Motul,61,0.821882,Priority opportunity,Atomized B2B opportunity,0.821882,0.0,0.750109,53.0,0.0,1.0,61,0.541147,0
57,2023,10008,Durango,Guadalupe Victoria,62,0.820131,Priority opportunity,Atomized B2B opportunity,0.820131,0.0,0.847265,83.0,0.0,1.0,62,0.539995,0
58,2023,07017,Chiapas,Cintalapa de Figueroa,66,0.814880,Priority opportunity,Atomized B2B opportunity,0.814880,0.0,0.897593,129.0,0.0,1.0,66,0.536537,0
59,2023,07012,Chiapas,Berriozábal,67,0.813567,Priority opportunity,Atomized B2B opportunity,0.813567,0.0,0.798687,50.0,0.0,1.0,67,0.535672,0

BROAD B2B GAP OPPORTUNITIES V2
====================================================================================================

,year,geo_key,entidad_name,municipio_name,rank_v2,industrial_b2b_opportunity_score_v2,industrial_b2b_opportunity_category_v2,industrial_b2b_opportunity_subtype_v2,industrial_demand_percentile,scaled_b2b_supply_percentile_v2,b2b_supply_percentile,denue_b2b_support_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,rank_v1,industrial_b2b_opportunity_score_v1,rank_change_v2_minus_v1
0,2018,31016,Yucatán,Chacsinkín,481,0.584855,Developing industrial market,Broad B2B gap,0.584855,0.0,0.022717,0.0,0.0,NaN,380,0.377746,101
1,2018,20497,Oaxaca,Santiago Yaitepec,499,0.575501,Developing industrial market,Broad B2B gap,0.575501,0.0,0.022717,0.0,0.0,NaN,395,0.371705,104
2,2018,17035,Morelos,Xoxocotla,530,0.563920,Developing industrial market,Broad B2B gap,0.563920,0.0,0.022717,0.0,0.0,NaN,417,0.364224,113
3,2018,19016,Nuevo León,Doctor González,539,0.559911,Developing industrial market,Broad B2B gap,0.559911,0.0,0.022717,0.0,0.0,NaN,424,0.361635,115
4,2018,20328,Oaxaca,San Pedro Taviche,549,0.556347,Developing industrial market,Broad B2B gap,0.556347,0.0,0.022717,0.0,0.0,NaN,431,0.359334,118
5,2018,20313,Oaxaca,San Pedro Jocotipac,634,0.522049,Developing industrial market,Broad B2B gap,0.522049,0.0,0.022717,0.0,0.0,NaN,493,0.337181,141
6,2018,21193,Puebla,Tzicatlacoyan,637,0.519822,Developing industrial market,Broad B2B gap,0.519822,0.0,0.022717,0.0,0.0,NaN,496,0.335742,141
7,2018,20564,Oaxaca,Yutanduchi de Guerrero,654,0.513586,Developing industrial market,Broad B2B gap,0.513586,0.0,0.022717,0.0,0.0,NaN,509,0.331715,145
8,2023,24059,San Luis Potosí,Villa de Pozos,2,0.957987,Top priority opportunity,Broad B2B gap,0.957987,0.0,0.028665,0.0,0.0,NaN,2,0.630762,0
9,2023,25019,Sinaloa,Eldorado,135,0.762801,Priority opportunity,Broad B2B gap,0.762801,0.0,0.028665,0.0,0.0,NaN,122,0.502247,13
10,2023,25020,Sinaloa,Juan José Ríos,279,0.672648,Developing industrial market,Broad B2B gap,0.672648,0.0,0.028665,0.0,0.0,NaN,232,0.442888,47
11,2023,20243,Oaxaca,San Martín Tilcajete,288,0.666083,Developing industrial market,Broad B2B gap,0.666083,0.0,0.028665,0.0,0.0,NaN,241,0.438565,47
12,2023,20497,Oaxaca,Santiago Yaitepec,319,0.648140,Developing industrial market,Broad B2B gap,0.648140,0.0,0.028665,0.0,0.0,NaN,265,0.426751,54
13,2023,19016,Nuevo León,Doctor González,419,0.600000,Developing industrial market,Broad B2B gap,0.600000,0.0,0.028665,0.0,0.0,NaN,334,0.395055,85
14,2023,20328,Oaxaca,San Pedro Taviche,427,0.596499,Developing industrial market,Broad B2B gap,0.596499,0.0,0.028665,0.0,0.0,NaN,339,0.392749,88

VALIDACIÓN RÁPIDA
====================================================================================================
Filas diagnosticadas: 4530
Missing scaled_b2b_supply_percentile_v2: 0
Missing industrial_b2b_opportunity_score_v2: 0
Años: [np.int64(2018), np.int64(2023)]

In [ ]:
# ============================================================
# 10. CONSOLIDAR BASE FINAL DE SCORES DE OPORTUNIDAD
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
#
# Output folder:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/
#
# Archivos:
# 01_municipality_industrial_b2b_opportunity_scores.csv
# 01_municipality_industrial_b2b_opportunity_scores.parquet
# 02_top_opportunity_ranking.csv
# 03_opportunity_category_summary.csv
# 04_opportunity_subtype_summary.csv
# 05_scoring_methodology_notes.txt
#
# Score definitivo:
# industrial_b2b_opportunity_score =
# industrial_demand_percentile * (1 - scaled_b2b_supply_percentile)
#
# Ajuste V2:
# Si b2b_scaled_capacity_proxy == 0,
# entonces scaled_b2b_supply_percentile = 0.
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

modeling_path = (
    project_path / "data" / "processed" / "modeling_base"
)

final_scores_path = modeling_path / "final_scores"
final_scores_path.mkdir(parents=True, exist_ok=True)

input_path = modeling_path / "08_modeling_base_complete_cases.csv"

output_csv_path = (
    final_scores_path / "01_municipality_industrial_b2b_opportunity_scores.csv"
)

output_parquet_path = (
    final_scores_path / "01_municipality_industrial_b2b_opportunity_scores.parquet"
)

top_ranking_path = (
    final_scores_path / "02_top_opportunity_ranking.csv"
)

category_summary_path = (
    final_scores_path / "03_opportunity_category_summary.csv"
)

subtype_summary_path = (
    final_scores_path / "04_opportunity_subtype_summary.csv"
)

methodology_notes_path = (
    final_scores_path / "05_scoring_methodology_notes.txt"
)

print("Input path:")
print(input_path)

print("\nOutput folder:")
print(final_scores_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré el input en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base complete-case
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")


# ------------------------------------------------------------
# 3. Definir variables y pesos
# ------------------------------------------------------------

demand_features = [
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment"
]

demand_weights = {
    "total_manufacturing_establishments": 0.25,
    "total_manufacturing_employment": 0.20,
    "total_manufacturing_value_added": 0.25,
    "total_manufacturing_income": 0.20,
    "total_manufacturing_investment": 0.10
}

b2b_supply_features = [
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes"
]

b2b_supply_weights = {
    "denue_logistics_storage_establishments": 0.35,
    "denue_professional_technical_establishments": 0.25,
    "denue_business_support_establishments": 0.20,
    "denue_b2b_support_scian_classes": 0.20
}

scaled_features = [
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",
    "denue_b2b_support_establishments"
]

required_cols = (
    [
        "year",
        "entidad_id",
        "entidad_name",
        "municipio_id",
        "municipio_name",
        "geo_key"
    ]
    + demand_features
    + b2b_supply_features
    + scaled_features
)

missing_cols = [col for col in required_cols if col not in df.columns]

if missing_cols:
    raise ValueError(f"Faltan columnas necesarias: {missing_cols}")

if not np.isclose(sum(demand_weights.values()), 1.0):
    raise ValueError("Los pesos de demanda no suman 1.")

if not np.isclose(sum(b2b_supply_weights.values()), 1.0):
    raise ValueError("Los pesos de oferta B2B no suman 1.")


# ------------------------------------------------------------
# 4. Convertir variables a numéricas
# ------------------------------------------------------------

numeric_cols = list(set(demand_features + b2b_supply_features + scaled_features))

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

missing_numeric = df[numeric_cols].isna().sum()

print("\nMissing en variables usadas:")
print(missing_numeric[missing_numeric > 0])

if missing_numeric.sum() > 0:
    raise ValueError(
        "Hay missing en variables necesarias. "
        "Revisa que estés usando 08_modeling_base_complete_cases.csv."
    )


# ------------------------------------------------------------
# 5. Industrial demand score
# ------------------------------------------------------------

for col in demand_features:
    percentile_col = f"{col}_demand_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["industrial_demand_score"] = 0.0

for col, weight in demand_weights.items():
    df["industrial_demand_score"] += (
        df[f"{col}_demand_percentile"] * weight
    )

df["industrial_demand_percentile"] = (
    df
    .groupby("year")["industrial_demand_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 6. B2B supply score general
# ------------------------------------------------------------

for col in b2b_supply_features:
    percentile_col = f"{col}_b2b_supply_percentile"

    df[percentile_col] = (
        df
        .groupby("year")[col]
        .rank(pct=True, method="average")
    )

df["b2b_supply_score"] = 0.0

for col, weight in b2b_supply_weights.items():
    df["b2b_supply_score"] += (
        df[f"{col}_b2b_supply_percentile"] * weight
    )

df["b2b_supply_percentile"] = (
    df
    .groupby("year")["b2b_supply_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 7. Scaled B2B supply score V2
# ------------------------------------------------------------

medium_expected_workers = 65.5
large_expected_workers = 150

df["b2b_scaled_capacity_proxy"] = (
    medium_expected_workers * df["denue_b2b_medium_establishments"]
    + large_expected_workers * df["denue_b2b_large_establishments"]
)

df["has_scaled_b2b_supply"] = (
    df["b2b_scaled_capacity_proxy"] > 0
).astype(int)

df["scaled_b2b_supply_percentile"] = np.nan

for year_value, idx in df.groupby("year").groups.items():

    year_mask = df.index.isin(idx)
    positive_mask = year_mask & (df["b2b_scaled_capacity_proxy"] > 0)
    zero_mask = year_mask & (df["b2b_scaled_capacity_proxy"] == 0)

    df.loc[zero_mask, "scaled_b2b_supply_percentile"] = 0.0

    df.loc[positive_mask, "scaled_b2b_supply_percentile"] = (
        df.loc[positive_mask, "b2b_scaled_capacity_proxy"]
        .rank(pct=True, method="average")
    )

df["scaled_b2b_supply_score"] = df["scaled_b2b_supply_percentile"]


# ------------------------------------------------------------
# 8. Variables auxiliares de atomización
# ------------------------------------------------------------

df["b2b_micro_small_establishments"] = (
    df["denue_b2b_micro_establishments"]
    + df["denue_b2b_small_establishments"]
)

df["b2b_micro_small_share"] = np.where(
    df["denue_b2b_support_establishments"] > 0,
    df["b2b_micro_small_establishments"] / df["denue_b2b_support_establishments"],
    np.nan
)

df["only_micro_small_b2b_supply"] = (
    (df["denue_b2b_support_establishments"] > 0) &
    (df["denue_b2b_medium_large_establishments"] == 0)
).astype(int)


# ------------------------------------------------------------
# 9. Score definitivo de oportunidad
# ------------------------------------------------------------

df["industrial_b2b_opportunity_score"] = (
    df["industrial_demand_percentile"]
    * (1 - df["scaled_b2b_supply_percentile"])
)

df["industrial_b2b_opportunity_percentile"] = (
    df
    .groupby("year")["industrial_b2b_opportunity_score"]
    .rank(pct=True, method="average")
)


# ------------------------------------------------------------
# 10. Categorías interpretativas
# ------------------------------------------------------------

def classify_opportunity(row):
    demand_p = row["industrial_demand_percentile"]
    scaled_p = row["scaled_b2b_supply_percentile"]

    if demand_p >= 0.90 and scaled_p < 0.50:
        return "Top priority opportunity"

    elif demand_p >= 0.75 and scaled_p < 0.50:
        return "Priority opportunity"

    elif demand_p >= 0.75 and scaled_p >= 0.75:
        return "Industrial ecosystem hub"

    elif demand_p >= 0.50 and scaled_p < 0.75:
        return "Developing industrial market"

    elif demand_p < 0.50 and scaled_p >= 0.75:
        return "Service hub, lower industrial demand"

    elif demand_p < 0.50 and scaled_p < 0.75:
        return "Lower initial priority"

    else:
        return "Intermediate / monitor"


df["industrial_b2b_opportunity_category"] = (
    df.apply(classify_opportunity, axis=1)
)


# ------------------------------------------------------------
# 11. Subtipos de oportunidad
# ------------------------------------------------------------

def classify_opportunity_subtype(row):
    category = row["industrial_b2b_opportunity_category"]
    b2b_general_p = row["b2b_supply_percentile"]
    b2b_total = row["denue_b2b_support_establishments"]
    medium_large = row["denue_b2b_medium_large_establishments"]
    scaled_p = row["scaled_b2b_supply_percentile"]

    opportunity_categories = [
        "Top priority opportunity",
        "Priority opportunity",
        "Developing industrial market"
    ]

    if category not in opportunity_categories:
        return "Not opportunity subtype"

    if medium_large == 0 and b2b_total > 0 and b2b_general_p >= 0.75:
        return "Atomized B2B opportunity"

    elif medium_large == 0 and b2b_total > 0 and b2b_general_p < 0.75:
        return "Limited scaled B2B opportunity"

    elif medium_large == 0 and b2b_total == 0:
        return "Broad B2B gap"

    elif medium_large > 0 and scaled_p < 0.50:
        return "Low scaled B2B opportunity"

    else:
        return "Mixed opportunity case"


df["industrial_b2b_opportunity_subtype"] = (
    df.apply(classify_opportunity_subtype, axis=1)
)


# ------------------------------------------------------------
# 12. Ranking por año
# ------------------------------------------------------------

df = (
    df
    .sort_values(
        ["year", "industrial_b2b_opportunity_score"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

df["industrial_b2b_opportunity_rank"] = (
    df
    .groupby("year")
    .cumcount() + 1
)


# ------------------------------------------------------------
# 13. Seleccionar columnas finales
# ------------------------------------------------------------

final_cols = [
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",

    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",

    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",

    "b2b_micro_small_establishments",
    "b2b_micro_small_share",
    "only_micro_small_b2b_supply",
    "has_scaled_b2b_supply",
    "b2b_scaled_capacity_proxy",

    "industrial_demand_score",
    "industrial_demand_percentile",
    "b2b_supply_score",
    "b2b_supply_percentile",
    "scaled_b2b_supply_score",
    "scaled_b2b_supply_percentile",
    "industrial_b2b_opportunity_score",
    "industrial_b2b_opportunity_percentile",
    "industrial_b2b_opportunity_rank",

    "industrial_b2b_opportunity_category",
    "industrial_b2b_opportunity_subtype"
]

final_cols = [col for col in final_cols if col in df.columns]

final_scores = df[final_cols].copy()


# ------------------------------------------------------------
# 14. Resúmenes finales
# ------------------------------------------------------------

category_summary = (
    final_scores
    .groupby(["year", "industrial_b2b_opportunity_category"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        avg_opportunity_score=("industrial_b2b_opportunity_score", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_scaled_b2b_supply_percentile=("scaled_b2b_supply_percentile", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_manufacturing_establishments=("total_manufacturing_establishments", "mean"),
        avg_manufacturing_employment=("total_manufacturing_employment", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean"),
        avg_micro_small_share=("b2b_micro_small_share", "mean")
    )
    .reset_index()
)

category_summary["share_municipality_years"] = (
    category_summary["n_municipality_years"]
    / category_summary.groupby("year")["n_municipality_years"].transform("sum")
)

subtype_summary = (
    final_scores
    .groupby(["year", "industrial_b2b_opportunity_subtype"], dropna=False)
    .agg(
        n_municipality_years=("geo_key", "size"),
        avg_opportunity_score=("industrial_b2b_opportunity_score", "mean"),
        avg_industrial_demand_percentile=("industrial_demand_percentile", "mean"),
        avg_scaled_b2b_supply_percentile=("scaled_b2b_supply_percentile", "mean"),
        avg_b2b_supply_percentile=("b2b_supply_percentile", "mean"),
        avg_b2b_total=("denue_b2b_support_establishments", "mean"),
        avg_b2b_medium_large=("denue_b2b_medium_large_establishments", "mean")
    )
    .reset_index()
)

top_opportunity_ranking = (
    final_scores
    .sort_values(
        ["year", "industrial_b2b_opportunity_rank"],
        ascending=[True, True]
    )
    .groupby("year")
    .head(100)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 15. Guardar archivos finales
# ------------------------------------------------------------

final_scores.to_csv(
    output_csv_path,
    index=False,
    encoding="utf-8-sig"
)

try:
    final_scores.to_parquet(
        output_parquet_path,
        index=False
    )
except Exception as e:
    print("\nNo se pudo guardar parquet. El CSV sí fue guardado.")
    print(e)

top_opportunity_ranking.to_csv(
    top_ranking_path,
    index=False,
    encoding="utf-8-sig"
)

category_summary.to_csv(
    category_summary_path,
    index=False,
    encoding="utf-8-sig"
)

subtype_summary.to_csv(
    subtype_summary_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 16. Guardar nota metodológica
# ------------------------------------------------------------

methodology_notes = f"""
Nearshoring Project / Market Opportunity Analytics
Final scoring methodology notes

Input:
{input_path}

Output:
{output_csv_path}

Industrial demand score:
- Constructed from annual percentile ranks of:
  1. total_manufacturing_establishments, weight 0.25
  2. total_manufacturing_employment, weight 0.20
  3. total_manufacturing_value_added, weight 0.25
  4. total_manufacturing_income, weight 0.20
  5. total_manufacturing_investment, weight 0.10

B2B supply score:
- Constructed from annual percentile ranks of:
  1. denue_logistics_storage_establishments, weight 0.35
  2. denue_professional_technical_establishments, weight 0.25
  3. denue_business_support_establishments, weight 0.20
  4. denue_b2b_support_scian_classes, weight 0.20
- denue_b2b_support_establishments is not included in the score to avoid double-counting its components.

Scaled B2B supply score:
- b2b_scaled_capacity_proxy =
  {medium_expected_workers} * denue_b2b_medium_establishments
  + {large_expected_workers} * denue_b2b_large_establishments
- If b2b_scaled_capacity_proxy == 0, scaled_b2b_supply_percentile = 0.
- If b2b_scaled_capacity_proxy > 0, scaled_b2b_supply_percentile is calculated as the annual percentile rank among municipalities with positive scaled B2B capacity.

Final opportunity score:
industrial_b2b_opportunity_score =
industrial_demand_percentile * (1 - scaled_b2b_supply_percentile)

Interpretation:
- Higher scores indicate municipalities with stronger industrial demand and weaker scaled B2B supply.
- Categories and subtypes are interpretive labels used to distinguish:
  1. Atomized B2B opportunity
  2. Limited scaled B2B opportunity
  3. Broad B2B gap
  4. Industrial ecosystem hub
  5. Lower initial priority

Important scope note:
- This is a territorial prioritization model, not a causal prediction of nearshoring.
"""

with open(methodology_notes_path, "w", encoding="utf-8") as f:
    f.write(methodology_notes)


# ------------------------------------------------------------
# 17. Validación rápida
# ------------------------------------------------------------

print("\nPROCESO TERMINADO")
print("=" * 100)

print("\nBase final:")
print(f"Filas: {final_scores.shape[0]:,}")
print(f"Columnas: {final_scores.shape[1]:,}")

print("\nMissing principales:")
print(
    final_scores[
        [
            "industrial_demand_percentile",
            "b2b_supply_percentile",
            "scaled_b2b_supply_percentile",
            "industrial_b2b_opportunity_score",
            "industrial_b2b_opportunity_category",
            "industrial_b2b_opportunity_subtype"
        ]
    ]
    .isna()
    .sum()
)

print("\nAños:")
print(sorted(final_scores["year"].dropna().unique()))

print("\nTop 20 ranking final:")
display(top_opportunity_ranking.head(20))

print("\nResumen por categoría:")
display(category_summary)

print("\nResumen por subtipo:")
display(subtype_summary)

print("\nArchivos guardados:")
print(output_csv_path)
print(output_parquet_path)
print(top_ranking_path)
print(category_summary_path)
print(subtype_summary_path)
print(methodology_notes_path)

Google Drive ya está disponible en: /content/drive/MyDrive
Input path:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/08_modeling_base_complete_cases.csv

Output folder:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores

Base cargada:
Filas: 4,530
Columnas: 54

Missing en variables usadas:
Series([], dtype: int64)

PROCESO TERMINADO
====================================================================================================

Base final:
Filas: 4,530
Columnas: 37

Missing principales:
industrial_demand_percentile           0
b2b_supply_percentile                  0
scaled_b2b_supply_percentile           0
industrial_b2b_opportunity_score       0
industrial_b2b_opportunity_category    0
industrial_b2b_opportunity_subtype     0
dtype: int64

Años:
[np.int64(2018), np.int64(2023)]

Top 20 ranking final:

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,total_manufacturing_establishments,total_manufacturing_employment,total_manufacturing_value_added,total_manufacturing_income,...,industrial_demand_percentile,b2b_supply_score,b2b_supply_percentile,scaled_b2b_supply_score,scaled_b2b_supply_percentile,industrial_b2b_opportunity_score,industrial_b2b_opportunity_percentile,industrial_b2b_opportunity_rank,industrial_b2b_opportunity_category,industrial_b2b_opportunity_subtype
0,2018,15,México,101,Tianguistenco,15101,671.0,10225.0,23738.590,43770.764,...,0.968374,0.806013,0.814699,0.0,0.0,0.968374,1.000000,1,Top priority opportunity,Atomized B2B opportunity
1,2018,29,Tlaxcala,013,Huamantla,29013,743.0,7179.0,4539.760,14402.339,...,0.956793,0.879866,0.891314,0.0,0.0,0.956793,0.999555,2,Top priority opportunity,Atomized B2B opportunity
2,2018,14,Jalisco,008,Arandas,14008,458.0,6485.0,2100.558,7795.481,...,0.936303,0.846247,0.854343,0.0,0.0,0.936303,0.999109,3,Top priority opportunity,Atomized B2B opportunity
3,2018,11,Guanajuato,004,Apaseo el Alto,11004,404.0,3985.0,1912.168,6117.481,...,0.918486,0.853207,0.861024,0.0,0.0,0.918486,0.998664,4,Top priority opportunity,Atomized B2B opportunity
4,2018,31,Yucatán,041,Kanasín,31041,318.0,3541.0,1274.774,4645.405,...,0.909131,0.751269,0.766592,0.0,0.0,0.909131,0.998218,5,Top priority opportunity,Atomized B2B opportunity
5,2018,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,644.0,3937.0,386.251,1370.414,...,0.903786,0.686448,0.703786,0.0,0.0,0.903786,0.997773,6,Top priority opportunity,Limited scaled B2B opportunity
6,2018,13,Hidalgo,081,Zacualtipán de Ángeles,13081,338.0,3456.0,651.961,2668.787,...,0.899332,0.752116,0.767929,0.0,0.0,0.899332,0.997327,7,Priority opportunity,Atomized B2B opportunity
7,2018,31,Yucatán,038,Hunucmá,31038,257.0,1756.0,1692.994,4333.701,...,0.897550,0.659878,0.678396,0.0,0.0,0.897550,0.996882,8,Priority opportunity,Limited scaled B2B opportunity
8,2018,14,Jalisco,083,Tala,14083,249.0,3568.0,881.091,3958.324,...,0.896659,0.843630,0.852116,0.0,0.0,0.896659,0.996437,9,Priority opportunity,Atomized B2B opportunity
9,2018,04,Campeche,001,Calkiní,04001,1147.0,3999.0,337.851,476.206,...,0.893987,0.787661,0.797773,0.0,0.0,0.893987,0.995991,10,Priority opportunity,Atomized B2B opportunity
10,2018,15,México,120,Zumpango,15120,826.0,2518.0,188.473,1103.867,...,0.891314,0.891169,0.901559,0.0,0.0,0.891314,0.995546,11,Priority opportunity,Atomized B2B opportunity
11,2018,22,Querétaro,007,Ezequiel Montes,22007,301.0,2650.0,578.080,2046.716,...,0.889532,0.827316,0.838307,0.0,0.0,0.889532,0.995100,12,Priority opportunity,Atomized B2B opportunity
12,2018,21,Puebla,177,Tlacotepec de Benito Juárez,21177,1537.0,2575.0,205.778,706.202,...,0.889087,0.739811,0.754566,0.0,0.0,0.889087,0.994655,13,Priority opportunity,Atomized B2B opportunity
13,2018,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,30160,307.0,1360.0,722.614,1973.976,...,0.882405,0.870657,0.878842,0.0,0.0,0.882405,0.994209,14,Priority opportunity,Atomized B2B opportunity
14,2018,21,Puebla,161,Tepanco de López,21161,141.0,4776.0,1292.920,2775.358,...,0.874388,0.602884,0.621826,0.0,0.0,0.874388,0.993764,15,Priority opportunity,Limited scaled B2B opportunity
15,2018,29,Tlaxcala,034,Tlaxco,29034,288.0,2566.0,288.232,1659.828,...,0.872606,0.736570,0.753229,0.0,0.0,0.872606,0.993318,16,Priority opportunity,Atomized B2B opportunity
16,2018,09,Ciudad de México,009,Milpa Alta,09009,577.0,1848.0,273.133,736.410,...,0.872160,0.831670,0.841871,0.0,0.0,0.872160,0.992873,17,Priority opportunity,Atomized B2B opportunity
17,2018,29,Tlaxcala,015,Ixtacuixtla de Mariano Matamoros,29015,331.0,1982.0,405.920,1191.688,...,0.870824,0.536192,0.547439,0.0,0.0,0.870824,0.992428,18,Priority opportunity,Limited scaled B2B opportunity
18,2018,14,Jalisco,015,Autlán de Navarro,14015,317.0,2011.0,226.754,1242.085,...,0.869933,0.868263,0.874388,0.0,0.0,0.869933,0.991982,19,Priority opportunity,Atomized B2B opportunity
19,2018,21,Puebla,013,Altepexi,21013,888.0,3126.0,186.437,293.833,...,0.869042,0.543296,0.556347,0.0,0.0,0.869042,0.991537,20,Priority opportunity,Limited scaled B2B opportunity

Resumen por categoría:

,year,industrial_b2b_opportunity_category,n_municipality_years,avg_opportunity_score,avg_industrial_demand_percentile,avg_scaled_b2b_supply_percentile,avg_b2b_supply_percentile,avg_manufacturing_establishments,avg_manufacturing_employment,avg_b2b_total,avg_b2b_medium_large,avg_micro_small_share,share_municipality_years
0,2018,Developing industrial market,672,0.516700,0.668647,0.193617,0.637374,243.049107,1363.879464,59.858631,1.337798,0.979746,0.299332
1,2018,Industrial ecosystem hub,162,0.114277,0.944598,0.877113,0.953878,1565.012346,30009.592593,1086.413580,76.469136,0.927062,0.072160
2,2018,Intermediate / monitor,2,0.165936,0.710579,0.766387,0.910913,295.500000,1458.000000,177.500000,11.000000,0.938024,0.000891
3,2018,Lower initial priority,1122,0.245738,0.250111,0.012481,0.291417,36.622103,77.178253,6.899287,0.072193,0.991980,0.499777
4,2018,Priority opportunity,258,0.710744,0.821189,0.132530,0.723372,377.321705,1761.395349,72.275194,0.658915,0.989785,0.114922
5,2018,Top priority opportunity,29,0.713418,0.921780,0.226477,0.852915,794.310345,5660.862069,176.068966,1.310345,0.990035,0.012918
6,2023,Developing industrial market,701,0.508602,0.670168,0.208940,0.645911,270.223966,1298.005706,55.748930,1.427960,0.975845,0.306783
7,2023,Industrial ecosystem hub,184,0.117460,0.942461,0.873508,0.945881,1534.614130,30323.554348,897.070652,78.103261,0.910977,0.080525
8,2023,Intermediate / monitor,1,0.149911,0.744420,0.798621,0.920350,216.000000,710.000000,175.000000,14.000000,0.920000,0.000438
9,2023,Lower initial priority,1142,0.243359,0.250109,0.018300,0.289694,42.126970,88.134851,6.204028,0.091068,0.986549,0.499781
10,2023,Priority opportunity,226,0.716260,0.818256,0.123247,0.706490,424.579646,1904.225664,60.163717,0.610619,0.987600,0.098906
11,2023,Top priority opportunity,31,0.734919,0.919482,0.201824,0.798595,563.838710,5397.096774,111.645161,1.096774,0.987796,0.013567

Resumen por subtipo:

,year,industrial_b2b_opportunity_subtype,n_municipality_years,avg_opportunity_score,avg_industrial_demand_percentile,avg_scaled_b2b_supply_percentile,avg_b2b_supply_percentile,avg_b2b_total,avg_b2b_medium_large
0,2018,Atomized B2B opportunity,96,0.753937,0.753937,0.000000,0.802566,80.760417,0.000000
1,2018,Broad B2B gap,8,0.549499,0.549499,0.000000,0.022717,0.000000,0.000000
2,2018,Limited scaled B2B opportunity,429,0.653562,0.653562,0.000000,0.525629,22.023310,0.000000
3,2018,Low scaled B2B opportunity,272,0.543410,0.748070,0.270120,0.755855,80.433824,1.411765
4,2018,Mixed opportunity case,154,0.300803,0.826635,0.632459,0.853018,161.681818,4.694805
5,2018,Not opportunity subtype,1286,0.229054,0.338313,0.122573,0.375832,143.153188,9.713064
6,2023,Atomized B2B opportunity,84,0.761954,0.761954,0.000000,0.801881,71.857143,0.000000
7,2023,Broad B2B gap,7,0.700594,0.700594,0.000000,0.028665,0.000000,0.000000
8,2023,Limited scaled B2B opportunity,408,0.651834,0.651834,0.000000,0.520696,19.247549,0.000000
9,2023,Low scaled B2B opportunity,288,0.535779,0.724807,0.256590,0.738836,63.965278,1.361111
10,2023,Mixed opportunity case,171,0.304248,0.816473,0.623856,0.844558,139.339181,4.567251
11,2023,Not opportunity subtype,1327,0.225832,0.346482,0.137470,0.381155,129.857573,10.918613

Archivos guardados:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/01_municipality_industrial_b2b_opportunity_scores.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/01_municipality_industrial_b2b_opportunity_scores.parquet
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/02_top_opportunity_ranking.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/03_opportunity_category_summary.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/04_opportunity_subtype_summary.csv
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/05_scoring_methodology_notes.txt

In [1]:
# ============================================================
# GENERAR MUESTRA CSV DE LA FINAL OPPORTUNITY SCORE BASE
# Nearshoring Project / Market Opportunity Analytics
#
# Funciona aunque hayas cerrado sesión.
#
# Objetivo:
# Crear una muestra pequeña en .csv para compartir en otro chat.
#
# Input:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/
#   01_municipality_industrial_b2b_opportunity_scores.csv
#
# Output:
# /content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/context_exports/
#   final_opportunity_score_base_sample_for_context.csv
# ============================================================


# ------------------------------------------------------------
# 0. Imports y montaje robusto de Google Drive
# ------------------------------------------------------------

from pathlib import Path
import pandas as pd
import numpy as np


def get_drive_root():
    possible_roots = [
        Path("/content/drive/MyDrive"),
        Path("/content/gdrive/MyDrive")
    ]

    for root in possible_roots:
        if root.exists():
            print(f"Google Drive ya está disponible en: {root}")
            return root

    try:
        from google.colab import drive
        print("Montando Google Drive en /content/drive...")
        drive.mount("/content/drive")

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("Primer intento de montaje falló:")
        print(e)

    try:
        from google.colab import drive
        print("Intentando force_remount=True...")
        drive.mount("/content/drive", force_remount=True)

        root = Path("/content/drive/MyDrive")
        if root.exists():
            print(f"Google Drive montado correctamente en: {root}")
            return root

    except Exception as e:
        print("El force_remount también falló:")
        print(e)

    raise RuntimeError(
        "No se pudo montar Google Drive. "
        "Reinicia el runtime y vuelve a autorizar Drive."
    )


drive_root = get_drive_root()


# ------------------------------------------------------------
# 1. Rutas
# ------------------------------------------------------------

project_path = drive_root / "Nearshoring_Project"

final_scores_path = (
    project_path / "data" / "processed" / "modeling_base" / "final_scores"
)

input_path = final_scores_path / "01_municipality_industrial_b2b_opportunity_scores.csv"

output_path = final_scores_path / "context_exports"
output_path.mkdir(parents=True, exist_ok=True)

sample_csv_path = output_path / "final_opportunity_score_base_sample_for_context.csv"

print("Input:")
print(input_path)

print("\nOutput:")
print(sample_csv_path)

if not input_path.exists():
    raise FileNotFoundError(f"No encontré la base final en: {input_path}")


# ------------------------------------------------------------
# 2. Cargar base final
# ------------------------------------------------------------

df = pd.read_csv(
    input_path,
    dtype={
        "year": str,
        "entidad_id": str,
        "municipio_id": str,
        "geo_key": str
    },
    low_memory=False
)

df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

df["entidad_id"] = (
    df["entidad_id"]
    .astype(str)
    .str.strip()
    .str.zfill(2)
)

df["municipio_id"] = (
    df["municipio_id"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

df["geo_key"] = df["entidad_id"] + df["municipio_id"]

print("\nBase cargada:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")
print("Años:", sorted(df["year"].dropna().unique()))


# ------------------------------------------------------------
# 3. Columnas que sí conviene mostrar en la muestra
# ------------------------------------------------------------

sample_cols = [
    # IDs
    "year",
    "entidad_id",
    "entidad_name",
    "municipio_id",
    "municipio_name",
    "geo_key",

    # Ranking y clasificación
    "industrial_b2b_opportunity_rank",
    "industrial_b2b_opportunity_category",
    "industrial_b2b_opportunity_subtype",

    # Scores principales
    "industrial_b2b_opportunity_score",
    "industrial_b2b_opportunity_percentile",
    "industrial_demand_percentile",
    "b2b_supply_percentile",
    "scaled_b2b_supply_percentile",

    # Variables manufactureras clave
    "total_manufacturing_establishments",
    "total_manufacturing_employment",
    "total_manufacturing_value_added",
    "total_manufacturing_income",
    "total_manufacturing_investment",

    # Variables B2B clave
    "denue_b2b_support_establishments",
    "denue_logistics_storage_establishments",
    "denue_professional_technical_establishments",
    "denue_business_support_establishments",
    "denue_b2b_support_scian_classes",

    # Tamaño B2B
    "denue_b2b_micro_establishments",
    "denue_b2b_small_establishments",
    "denue_b2b_medium_establishments",
    "denue_b2b_large_establishments",
    "denue_b2b_medium_large_establishments",

    # Auxiliares
    "b2b_micro_small_share",
    "only_micro_small_b2b_supply",
    "has_scaled_b2b_supply",
    "b2b_scaled_capacity_proxy"
]

sample_cols = [col for col in sample_cols if col in df.columns]


# ------------------------------------------------------------
# 4. Validar columnas esenciales
# ------------------------------------------------------------

required_cols = [
    "year",
    "industrial_b2b_opportunity_rank",
    "industrial_b2b_opportunity_score",
    "industrial_b2b_opportunity_category",
    "industrial_b2b_opportunity_subtype"
]

missing_required = [col for col in required_cols if col not in df.columns]

if missing_required:
    raise ValueError(f"Faltan columnas esenciales: {missing_required}")


# ------------------------------------------------------------
# 5. Construir muestra útil para contexto
# ------------------------------------------------------------

# A) Top 15 por año
top_sample = (
    df[sample_cols]
    .sort_values(
        ["year", "industrial_b2b_opportunity_rank"],
        ascending=[True, True]
    )
    .groupby("year")
    .head(15)
    .copy()
)

top_sample["sample_source"] = "top_15_by_year"


# B) Hasta 2 ejemplos por categoría y año
category_sample = (
    df[sample_cols]
    .sort_values(
        ["year", "industrial_b2b_opportunity_category", "industrial_b2b_opportunity_score"],
        ascending=[True, True, False]
    )
    .groupby(["year", "industrial_b2b_opportunity_category"], dropna=False)
    .head(2)
    .copy()
)

category_sample["sample_source"] = "examples_by_category"


# C) Hasta 2 ejemplos por subtipo y año
subtype_sample = (
    df[sample_cols]
    .sort_values(
        ["year", "industrial_b2b_opportunity_subtype", "industrial_b2b_opportunity_score"],
        ascending=[True, True, False]
    )
    .groupby(["year", "industrial_b2b_opportunity_subtype"], dropna=False)
    .head(2)
    .copy()
)

subtype_sample["sample_source"] = "examples_by_subtype"


# D) Muestra aleatoria pequeña por año para contexto general
random_sample = (
    df[sample_cols]
    .groupby("year", group_keys=False)
    .apply(lambda x: x.sample(n=min(10, len(x)), random_state=123))
    .copy()
)

random_sample["sample_source"] = "random_sample_by_year"


# Unir y quitar duplicados
sample_df = pd.concat(
    [
        top_sample,
        category_sample,
        subtype_sample,
        random_sample
    ],
    ignore_index=True
)

sample_df = (
    sample_df
    .drop_duplicates(subset=["year", "geo_key"], keep="first")
    .sort_values(
        ["year", "industrial_b2b_opportunity_rank"],
        ascending=[True, True]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 6. Redondear columnas numéricas para que sea legible
# ------------------------------------------------------------

score_like_cols = [
    col for col in sample_df.columns
    if (
        "score" in col
        or "percentile" in col
        or "share" in col
        or "proxy" in col
    )
]

for col in score_like_cols:
    sample_df[col] = pd.to_numeric(sample_df[col], errors="ignore")
    if pd.api.types.is_numeric_dtype(sample_df[col]):
        sample_df[col] = sample_df[col].round(4)


# ------------------------------------------------------------
# 7. Guardar muestra CSV
# ------------------------------------------------------------

sample_df.to_csv(
    sample_csv_path,
    index=False,
    encoding="utf-8-sig"
)


# ------------------------------------------------------------
# 8. Mostrar resultado
# ------------------------------------------------------------

print("\nMUESTRA GENERADA")
print("=" * 100)
print(f"Filas de muestra: {sample_df.shape[0]:,}")
print(f"Columnas de muestra: {sample_df.shape[1]:,}")

print("\nArchivo guardado en:")
print(sample_csv_path)

print("\nVista rápida:")
display(sample_df.head(30))

Montando Google Drive en /content/drive...
Mounted at /content/drive
Google Drive montado correctamente en: /content/drive/MyDrive
Input:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/01_municipality_industrial_b2b_opportunity_scores.csv

Output:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/context_exports/final_opportunity_score_base_sample_for_context.csv

Base cargada:
Filas: 4,530
Columnas: 37
Años: [np.int64(2018), np.int64(2023)]

/tmp/ipykernel_5038/4200677502.py:270: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=min(10, len(x)), random_state=123))
/tmp/ipykernel_5038/4200677502.py:314: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  sample_df[col] = pd.to_numeric(sample_df[col], errors="ignore")

MUESTRA GENERADA
====================================================================================================
Filas de muestra: 76
Columnas de muestra: 34

Archivo guardado en:
/content/drive/MyDrive/Nearshoring_Project/data/processed/modeling_base/final_scores/context_exports/final_opportunity_score_base_sample_for_context.csv

Vista rápida:

,year,entidad_id,entidad_name,municipio_id,municipio_name,geo_key,industrial_b2b_opportunity_rank,industrial_b2b_opportunity_category,industrial_b2b_opportunity_subtype,industrial_b2b_opportunity_score,...,denue_b2b_micro_establishments,denue_b2b_small_establishments,denue_b2b_medium_establishments,denue_b2b_large_establishments,denue_b2b_medium_large_establishments,b2b_micro_small_share,only_micro_small_b2b_supply,has_scaled_b2b_supply,b2b_scaled_capacity_proxy,sample_source
0,2018,15,México,101,Tianguistenco,15101,1,Top priority opportunity,Atomized B2B opportunity,0.9684,...,159.0,8.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
1,2018,29,Tlaxcala,013,Huamantla,29013,2,Top priority opportunity,Atomized B2B opportunity,0.9568,...,163.0,11.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
2,2018,14,Jalisco,008,Arandas,14008,3,Top priority opportunity,Atomized B2B opportunity,0.9363,...,176.0,11.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
3,2018,11,Guanajuato,004,Apaseo el Alto,11004,4,Top priority opportunity,Atomized B2B opportunity,0.9185,...,106.0,5.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
4,2018,31,Yucatán,041,Kanasín,31041,5,Top priority opportunity,Atomized B2B opportunity,0.9091,...,49.0,8.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
5,2018,29,Tlaxcala,018,Contla de Juan Cuamatzi,29018,6,Top priority opportunity,Limited scaled B2B opportunity,0.9038,...,75.0,1.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
6,2018,13,Hidalgo,081,Zacualtipán de Ángeles,13081,7,Priority opportunity,Atomized B2B opportunity,0.8993,...,68.0,3.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
7,2018,31,Yucatán,038,Hunucmá,31038,8,Priority opportunity,Limited scaled B2B opportunity,0.8976,...,40.0,1.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
8,2018,14,Jalisco,083,Tala,14083,9,Priority opportunity,Atomized B2B opportunity,0.8967,...,97.0,12.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
9,2018,04,Campeche,001,Calkiní,04001,10,Priority opportunity,Atomized B2B opportunity,0.8940,...,70.0,3.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
10,2018,15,México,120,Zumpango,15120,11,Priority opportunity,Atomized B2B opportunity,0.8913,...,294.0,25.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
11,2018,22,Querétaro,007,Ezequiel Montes,22007,12,Priority opportunity,Atomized B2B opportunity,0.8895,...,96.0,3.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
12,2018,21,Puebla,177,Tlacotepec de Benito Juárez,21177,13,Priority opportunity,Atomized B2B opportunity,0.8891,...,48.0,2.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
13,2018,30,Veracruz de Ignacio de la Llave,160,Álamo Temapache,30160,14,Priority opportunity,Atomized B2B opportunity,0.8824,...,138.0,4.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
14,2018,21,Puebla,161,Tepanco de López,21161,15,Priority opportunity,Limited scaled B2B opportunity,0.8744,...,25.0,1.0,0.0,0.0,0.0,1.0000,1,0,0.0,top_15_by_year
15,2018,15,México,019,Capulhuac,15019,34,Priority opportunity,Limited scaled B2B opportunity,0.8494,...,77.0,1.0,0.0,0.0,0.0,1.0000,1,0,0.0,random_sample_by_year
16,2018,15,México,035,Huehuetoca,15035,76,Top priority opportunity,Low scaled B2B opportunity,0.8089,...,176.0,7.0,1.0,0.0,1.0,0.9946,0,1,65.5,examples_by_subtype
17,2018,15,México,062,Ocoyoacac,15062,82,Top priority opportunity,Low scaled B2B opportunity,0.8027,...,112.0,3.0,1.0,0.0,1.0,0.9914,0,1,65.5,examples_by_subtype
18,2018,12,Guerrero,034,Huitzuco de los Figueroa,12034,169,Developing industrial market,Atomized B2B opportunity,0.7492,...,56.0,1.0,0.0,0.0,0.0,1.0000,1,0,0.0,examples_by_category
19,2018,21,Puebla,170,Tepeyahualco,21170,170,Developing industrial market,Limited scaled B2B opportunity,0.7483,...,4.0,0.0,0.0,0.0,0.0,1.0000,1,0,0.0,examples_by_category
20,2018,15,México,113,Villa Guerrero,15113,353,Developing industrial market,Atomized B2B opportunity,0.6437,...,50.0,3.0,0.0,0.0,0.0,1.0000,1,0,0.0,random_sample_by_year
21,2018,31,Yucatán,016,Chacsinkín,31016,481,Developing industrial market,Broad B2B gap,0.5849,...,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0.0,examples_by_subtype
22,2018,20,Oaxaca,497,Santiago Yaitepec,20497,499,Developing industrial market,Broad B2B gap,0.5755,...,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0.0,examples_by_subtype
23,2018,13,Hidalgo,044,Nopala de Villagrán,13044,692,Lower initial priority,Not opportunity subtype,0.4998,...,5.0,0.0,0.0,0.0,0.0,1.0000,1,0,0.0,examples_by_category
24,2018,15,México,008,Amatepec,15008,695,Lower initial priority,Not opportunity subtype,0.4993,...,19.0,2.0,0.0,0.0,0.0,1.0000,1,0,0.0,examples_by_category
25,2018,30,Veracruz de Ignacio de la Llave,062,Chocamán,30062,780,Lower initial priority,Not opportunity subtype,0.4708,...,14.0,0.0,0.0,0.0,0.0,1.0000,1,0,0.0,random_sample_by_year
26,2018,15,México,090,Tenango del Valle,15090,841,Developing industrial market,Mixed opportunity case,0.4489,...,160.0,8.0,4.0,0.0,4.0,0.9767,0,1,262.0,examples_by_subtype
27,2018,11,Guanajuato,003,San Miguel de Allende,11003,880,Developing industrial market,Mixed opportunity case,0.4343,...,287.0,32.0,2.0,1.0,3.0,0.9907,0,1,281.0,examples_by_subtype
28,2018,20,Oaxaca,130,San Dionisio del Mar,20130,1178,Lower initial priority,Not opportunity subtype,0.3403,...,10.0,0.0,0.0,0.0,0.0,1.0000,1,0,0.0,random_sample_by_year
29,2018,08,Chihuahua,051,Ocampo,08051,1299,Lower initial priority,Not opportunity subtype,0.3016,...,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0.0,random_sample_by_year